POST http://localhost:8080/learning.v1.LearningService/ListLearnedWords
Content-Type: application/json

{"filter":"surface in [\"you\",\"do\",\"said\",\"whole\",\"principle\",\"came\",\"idea\"]"}

###

