POST http://localhost:8080/learning.v1.LearningService/ListLearnedWords
Content-Type: application/json

//{"filter":"surface in [\"governing\",\"hired\",\"Games\",\"Roots\",\"sales\",\"searching\", \"does\", \"goes\", \"easy\"]"}

{"filter":"surface in [\"book\",\"eating\", \"easy\"]"}

###

