// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/eslsoft/vocnet/internal/adapter/connectrpc"
	"github.com/eslsoft/vocnet/internal/adapter/repository"
	"github.com/eslsoft/vocnet/internal/infrastructure/config"
	"github.com/eslsoft/vocnet/internal/infrastructure/database"
	"github.com/eslsoft/vocnet/internal/infrastructure/server"
	"github.com/eslsoft/vocnet/internal/usecase"
	"github.com/eslsoft/vocnet/pkg/api/dict/v1/dictv1connect"
	"github.com/eslsoft/vocnet/pkg/api/learning/v1/learningv1connect"
	"github.com/google/wire"
)

// Injectors from wire.go:

// Initialize builds the application container using Wire.
func Initialize() (*Container, func(), error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, nil, err
	}
	logger, err := server.NewLogger(configConfig)
	if err != nil {
		return nil, nil, err
	}
	client, cleanup, err := database.NewEntClient(configConfig)
	if err != nil {
		return nil, nil, err
	}
	wordGroupRepository := repository.NewWordGroupRepository(client)
	lexemeRepository := repository.NewLexemeRepository(client)
	wordUsecase := usecase.NewWordUsecase(wordGroupRepository, lexemeRepository)
	dictServiceServer := grpc.NewDictServiceServer(wordUsecase)
	learnedWordRepository := repository.NewLearnedWordRepository(client)
	learnedWordUsecase := usecase.NewLearnedWordUsecase(learnedWordRepository)
	learningServiceServer := grpc.NewLearningServiceServer(learnedWordUsecase)
	serverServer := server.NewServer(configConfig, logger, dictServiceServer, learningServiceServer)
	container := &Container{
		Logger:    logger,
		Server:    serverServer,
		EntClient: client,
	}
	return container, func() {
		cleanup()
	}, nil
}

// wire.go:

var configSet = wire.NewSet(config.Load)

var databaseSet = wire.NewSet(database.NewEntClient)

var repositorySet = wire.NewSet(repository.NewLexemeRepository, repository.NewLearnedLexemeRepository, repository.NewLearnedWordRepository, repository.NewWordGroupRepository)

var usecaseSet = wire.NewSet(usecase.NewLexemeUsecase, usecase.NewWordUsecase, usecase.NewLearnedLexemeUsecase, usecase.NewLearnedWordUsecase)

var serviceSet = wire.NewSet(grpc.NewDictServiceServer, grpc.NewLearningServiceServer, wire.Bind(new(learningv1connect.LearningServiceHandler), new(*grpc.LearningServiceServer)), wire.Bind(new(dictv1connect.DictServiceHandler), new(*grpc.DictServiceServer)))

var serverSet = wire.NewSet(server.NewLogger, server.NewServer)
