// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: learning/v1/review_service.proto

package learningv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v11 "github.com/eslsoft/vocnet/pkg/api/common/v1"
	v1 "github.com/eslsoft/vocnet/pkg/api/learning/v1"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ReviewPlanServiceName is the fully-qualified name of the ReviewPlanService service.
	ReviewPlanServiceName = "learning.v1.ReviewPlanService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ReviewPlanServiceCreateReviewPlanProcedure is the fully-qualified name of the ReviewPlanService's
	// CreateReviewPlan RPC.
	ReviewPlanServiceCreateReviewPlanProcedure = "/learning.v1.ReviewPlanService/CreateReviewPlan"
	// ReviewPlanServiceUpdateReviewPlanProcedure is the fully-qualified name of the ReviewPlanService's
	// UpdateReviewPlan RPC.
	ReviewPlanServiceUpdateReviewPlanProcedure = "/learning.v1.ReviewPlanService/UpdateReviewPlan"
	// ReviewPlanServiceGetReviewPlanProcedure is the fully-qualified name of the ReviewPlanService's
	// GetReviewPlan RPC.
	ReviewPlanServiceGetReviewPlanProcedure = "/learning.v1.ReviewPlanService/GetReviewPlan"
	// ReviewPlanServiceListReviewPlansProcedure is the fully-qualified name of the ReviewPlanService's
	// ListReviewPlans RPC.
	ReviewPlanServiceListReviewPlansProcedure = "/learning.v1.ReviewPlanService/ListReviewPlans"
	// ReviewPlanServiceDeleteReviewPlanProcedure is the fully-qualified name of the ReviewPlanService's
	// DeleteReviewPlan RPC.
	ReviewPlanServiceDeleteReviewPlanProcedure = "/learning.v1.ReviewPlanService/DeleteReviewPlan"
	// ReviewPlanServiceGetFlashCardsProcedure is the fully-qualified name of the ReviewPlanService's
	// GetFlashCards RPC.
	ReviewPlanServiceGetFlashCardsProcedure = "/learning.v1.ReviewPlanService/GetFlashCards"
)

// ReviewPlanServiceClient is a client for the learning.v1.ReviewPlanService service.
type ReviewPlanServiceClient interface {
	CreateReviewPlan(context.Context, *connect.Request[v1.CreateReviewPlanRequest]) (*connect.Response[v1.ReviewPlan], error)
	UpdateReviewPlan(context.Context, *connect.Request[v1.UpdateReviewPlanRequest]) (*connect.Response[v1.ReviewPlan], error)
	GetReviewPlan(context.Context, *connect.Request[v11.IDRequest]) (*connect.Response[v1.ReviewPlan], error)
	ListReviewPlans(context.Context, *connect.Request[v1.ListReviewPlansRequest]) (*connect.Response[v1.ListReviewPlansResponse], error)
	DeleteReviewPlan(context.Context, *connect.Request[v11.IDRequest]) (*connect.Response[emptypb.Empty], error)
	GetFlashCards(context.Context, *connect.Request[v1.GetFlashCardsRequest]) (*connect.Response[v1.FlashCardSet], error)
}

// NewReviewPlanServiceClient constructs a client for the learning.v1.ReviewPlanService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewReviewPlanServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ReviewPlanServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	reviewPlanServiceMethods := v1.File_learning_v1_review_service_proto.Services().ByName("ReviewPlanService").Methods()
	return &reviewPlanServiceClient{
		createReviewPlan: connect.NewClient[v1.CreateReviewPlanRequest, v1.ReviewPlan](
			httpClient,
			baseURL+ReviewPlanServiceCreateReviewPlanProcedure,
			connect.WithSchema(reviewPlanServiceMethods.ByName("CreateReviewPlan")),
			connect.WithClientOptions(opts...),
		),
		updateReviewPlan: connect.NewClient[v1.UpdateReviewPlanRequest, v1.ReviewPlan](
			httpClient,
			baseURL+ReviewPlanServiceUpdateReviewPlanProcedure,
			connect.WithSchema(reviewPlanServiceMethods.ByName("UpdateReviewPlan")),
			connect.WithClientOptions(opts...),
		),
		getReviewPlan: connect.NewClient[v11.IDRequest, v1.ReviewPlan](
			httpClient,
			baseURL+ReviewPlanServiceGetReviewPlanProcedure,
			connect.WithSchema(reviewPlanServiceMethods.ByName("GetReviewPlan")),
			connect.WithClientOptions(opts...),
		),
		listReviewPlans: connect.NewClient[v1.ListReviewPlansRequest, v1.ListReviewPlansResponse](
			httpClient,
			baseURL+ReviewPlanServiceListReviewPlansProcedure,
			connect.WithSchema(reviewPlanServiceMethods.ByName("ListReviewPlans")),
			connect.WithClientOptions(opts...),
		),
		deleteReviewPlan: connect.NewClient[v11.IDRequest, emptypb.Empty](
			httpClient,
			baseURL+ReviewPlanServiceDeleteReviewPlanProcedure,
			connect.WithSchema(reviewPlanServiceMethods.ByName("DeleteReviewPlan")),
			connect.WithClientOptions(opts...),
		),
		getFlashCards: connect.NewClient[v1.GetFlashCardsRequest, v1.FlashCardSet](
			httpClient,
			baseURL+ReviewPlanServiceGetFlashCardsProcedure,
			connect.WithSchema(reviewPlanServiceMethods.ByName("GetFlashCards")),
			connect.WithClientOptions(opts...),
		),
	}
}

// reviewPlanServiceClient implements ReviewPlanServiceClient.
type reviewPlanServiceClient struct {
	createReviewPlan *connect.Client[v1.CreateReviewPlanRequest, v1.ReviewPlan]
	updateReviewPlan *connect.Client[v1.UpdateReviewPlanRequest, v1.ReviewPlan]
	getReviewPlan    *connect.Client[v11.IDRequest, v1.ReviewPlan]
	listReviewPlans  *connect.Client[v1.ListReviewPlansRequest, v1.ListReviewPlansResponse]
	deleteReviewPlan *connect.Client[v11.IDRequest, emptypb.Empty]
	getFlashCards    *connect.Client[v1.GetFlashCardsRequest, v1.FlashCardSet]
}

// CreateReviewPlan calls learning.v1.ReviewPlanService.CreateReviewPlan.
func (c *reviewPlanServiceClient) CreateReviewPlan(ctx context.Context, req *connect.Request[v1.CreateReviewPlanRequest]) (*connect.Response[v1.ReviewPlan], error) {
	return c.createReviewPlan.CallUnary(ctx, req)
}

// UpdateReviewPlan calls learning.v1.ReviewPlanService.UpdateReviewPlan.
func (c *reviewPlanServiceClient) UpdateReviewPlan(ctx context.Context, req *connect.Request[v1.UpdateReviewPlanRequest]) (*connect.Response[v1.ReviewPlan], error) {
	return c.updateReviewPlan.CallUnary(ctx, req)
}

// GetReviewPlan calls learning.v1.ReviewPlanService.GetReviewPlan.
func (c *reviewPlanServiceClient) GetReviewPlan(ctx context.Context, req *connect.Request[v11.IDRequest]) (*connect.Response[v1.ReviewPlan], error) {
	return c.getReviewPlan.CallUnary(ctx, req)
}

// ListReviewPlans calls learning.v1.ReviewPlanService.ListReviewPlans.
func (c *reviewPlanServiceClient) ListReviewPlans(ctx context.Context, req *connect.Request[v1.ListReviewPlansRequest]) (*connect.Response[v1.ListReviewPlansResponse], error) {
	return c.listReviewPlans.CallUnary(ctx, req)
}

// DeleteReviewPlan calls learning.v1.ReviewPlanService.DeleteReviewPlan.
func (c *reviewPlanServiceClient) DeleteReviewPlan(ctx context.Context, req *connect.Request[v11.IDRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteReviewPlan.CallUnary(ctx, req)
}

// GetFlashCards calls learning.v1.ReviewPlanService.GetFlashCards.
func (c *reviewPlanServiceClient) GetFlashCards(ctx context.Context, req *connect.Request[v1.GetFlashCardsRequest]) (*connect.Response[v1.FlashCardSet], error) {
	return c.getFlashCards.CallUnary(ctx, req)
}

// ReviewPlanServiceHandler is an implementation of the learning.v1.ReviewPlanService service.
type ReviewPlanServiceHandler interface {
	CreateReviewPlan(context.Context, *connect.Request[v1.CreateReviewPlanRequest]) (*connect.Response[v1.ReviewPlan], error)
	UpdateReviewPlan(context.Context, *connect.Request[v1.UpdateReviewPlanRequest]) (*connect.Response[v1.ReviewPlan], error)
	GetReviewPlan(context.Context, *connect.Request[v11.IDRequest]) (*connect.Response[v1.ReviewPlan], error)
	ListReviewPlans(context.Context, *connect.Request[v1.ListReviewPlansRequest]) (*connect.Response[v1.ListReviewPlansResponse], error)
	DeleteReviewPlan(context.Context, *connect.Request[v11.IDRequest]) (*connect.Response[emptypb.Empty], error)
	GetFlashCards(context.Context, *connect.Request[v1.GetFlashCardsRequest]) (*connect.Response[v1.FlashCardSet], error)
}

// NewReviewPlanServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewReviewPlanServiceHandler(svc ReviewPlanServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	reviewPlanServiceMethods := v1.File_learning_v1_review_service_proto.Services().ByName("ReviewPlanService").Methods()
	reviewPlanServiceCreateReviewPlanHandler := connect.NewUnaryHandler(
		ReviewPlanServiceCreateReviewPlanProcedure,
		svc.CreateReviewPlan,
		connect.WithSchema(reviewPlanServiceMethods.ByName("CreateReviewPlan")),
		connect.WithHandlerOptions(opts...),
	)
	reviewPlanServiceUpdateReviewPlanHandler := connect.NewUnaryHandler(
		ReviewPlanServiceUpdateReviewPlanProcedure,
		svc.UpdateReviewPlan,
		connect.WithSchema(reviewPlanServiceMethods.ByName("UpdateReviewPlan")),
		connect.WithHandlerOptions(opts...),
	)
	reviewPlanServiceGetReviewPlanHandler := connect.NewUnaryHandler(
		ReviewPlanServiceGetReviewPlanProcedure,
		svc.GetReviewPlan,
		connect.WithSchema(reviewPlanServiceMethods.ByName("GetReviewPlan")),
		connect.WithHandlerOptions(opts...),
	)
	reviewPlanServiceListReviewPlansHandler := connect.NewUnaryHandler(
		ReviewPlanServiceListReviewPlansProcedure,
		svc.ListReviewPlans,
		connect.WithSchema(reviewPlanServiceMethods.ByName("ListReviewPlans")),
		connect.WithHandlerOptions(opts...),
	)
	reviewPlanServiceDeleteReviewPlanHandler := connect.NewUnaryHandler(
		ReviewPlanServiceDeleteReviewPlanProcedure,
		svc.DeleteReviewPlan,
		connect.WithSchema(reviewPlanServiceMethods.ByName("DeleteReviewPlan")),
		connect.WithHandlerOptions(opts...),
	)
	reviewPlanServiceGetFlashCardsHandler := connect.NewUnaryHandler(
		ReviewPlanServiceGetFlashCardsProcedure,
		svc.GetFlashCards,
		connect.WithSchema(reviewPlanServiceMethods.ByName("GetFlashCards")),
		connect.WithHandlerOptions(opts...),
	)
	return "/learning.v1.ReviewPlanService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ReviewPlanServiceCreateReviewPlanProcedure:
			reviewPlanServiceCreateReviewPlanHandler.ServeHTTP(w, r)
		case ReviewPlanServiceUpdateReviewPlanProcedure:
			reviewPlanServiceUpdateReviewPlanHandler.ServeHTTP(w, r)
		case ReviewPlanServiceGetReviewPlanProcedure:
			reviewPlanServiceGetReviewPlanHandler.ServeHTTP(w, r)
		case ReviewPlanServiceListReviewPlansProcedure:
			reviewPlanServiceListReviewPlansHandler.ServeHTTP(w, r)
		case ReviewPlanServiceDeleteReviewPlanProcedure:
			reviewPlanServiceDeleteReviewPlanHandler.ServeHTTP(w, r)
		case ReviewPlanServiceGetFlashCardsProcedure:
			reviewPlanServiceGetFlashCardsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedReviewPlanServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedReviewPlanServiceHandler struct{}

func (UnimplementedReviewPlanServiceHandler) CreateReviewPlan(context.Context, *connect.Request[v1.CreateReviewPlanRequest]) (*connect.Response[v1.ReviewPlan], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("learning.v1.ReviewPlanService.CreateReviewPlan is not implemented"))
}

func (UnimplementedReviewPlanServiceHandler) UpdateReviewPlan(context.Context, *connect.Request[v1.UpdateReviewPlanRequest]) (*connect.Response[v1.ReviewPlan], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("learning.v1.ReviewPlanService.UpdateReviewPlan is not implemented"))
}

func (UnimplementedReviewPlanServiceHandler) GetReviewPlan(context.Context, *connect.Request[v11.IDRequest]) (*connect.Response[v1.ReviewPlan], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("learning.v1.ReviewPlanService.GetReviewPlan is not implemented"))
}

func (UnimplementedReviewPlanServiceHandler) ListReviewPlans(context.Context, *connect.Request[v1.ListReviewPlansRequest]) (*connect.Response[v1.ListReviewPlansResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("learning.v1.ReviewPlanService.ListReviewPlans is not implemented"))
}

func (UnimplementedReviewPlanServiceHandler) DeleteReviewPlan(context.Context, *connect.Request[v11.IDRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("learning.v1.ReviewPlanService.DeleteReviewPlan is not implemented"))
}

func (UnimplementedReviewPlanServiceHandler) GetFlashCards(context.Context, *connect.Request[v1.GetFlashCardsRequest]) (*connect.Response[v1.FlashCardSet], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("learning.v1.ReviewPlanService.GetFlashCards is not implemented"))
}
