// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: learning/v1/flashcard.proto

package learningv1

import (
	v1 "github.com/eslsoft/vocnet/pkg/api/dict/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============================================================================
// CardType - 题型 (决定UI渲染和验证逻辑)
// ============================================================================
type CardType int32

const (
	CardType_CARD_TYPE_UNSPECIFIED CardType = 0
	// 单选题 - 从多个选项中选择唯一正确答案
	//
	// 示例: 选择单词的正确释义
	//
	//	{
	//	  "id": "card_001",
	//	  "type": "CARD_TYPE_SINGLE_CHOICE",
	//	  "difficulty": 2,
	//	  "prompt": "选择正确的中文释义",
	//	  "question": {
	//	    "text": "apple",
	//	    "auto_play": true,
	//	    "phonetics": [{"accent": "US", "text": "/ˈæpl/"}]
	//	  },
	//	  "options": [
	//	    {"id": "A", "text": "苹果"},
	//	    {"id": "B", "text": "香蕉"},
	//	    {"id": "C", "text": "橙子"}
	//	  ],
	//	  "answer": {
	//	    "correct_values": ["A"]
	//	  }
	//	}
	//
	// UI渲染: 单选按钮 (radio buttons)
	// 验证逻辑: userAnswer == answer.correct_values[0]
	CardType_CARD_TYPE_SINGLE_CHOICE CardType = 1
	// 多选题 - 从多个选项中选择一个或多个正确答案
	//
	// 示例: 选择所有表示水果的单词
	//
	//	{
	//	  "id": "card_002",
	//	  "type": "CARD_TYPE_MULTIPLE_CHOICE",
	//	  "difficulty": 3,
	//	  "prompt": "选择所有表示水果的单词",
	//	  "question": {
	//	    "text": "Which are fruits?"
	//	  },
	//	  "options": [
	//	    {"id": "A", "text": "apple"},
	//	    {"id": "B", "text": "car"},
	//	    {"id": "C", "text": "banana"},
	//	    {"id": "D", "text": "computer"}
	//	  ],
	//	  "answer": {
	//	    "correct_values": ["A", "C"]
	//	  }
	//	}
	//
	// UI渲染: 复选框 (checkboxes)
	// 验证逻辑: set(userAnswers) == set(answer.correct_values)
	CardType_CARD_TYPE_MULTIPLE_CHOICE CardType = 2
	// 填空题 - 自由输入填入缺失的单词或短语 (支持单空和多空)
	//
	// 示例1: 单空填空
	//
	//	{
	//	  "id": "card_003",
	//	  "type": "CARD_TYPE_FILL_BLANK",
	//	  "difficulty": 2,
	//	  "prompt": "完成句子",
	//	  "question": {
	//	    "text": "I eat an ___ every day.",
	//	    "image_url": "https://example.com/apple.jpg"
	//	  },
	//	  "options": [
	//	    {"id": "blank1", "hint": "a red fruit"}
	//	  ],
	//	  "answer": {
	//	    "correct_values": ["blank1:apple"],
	//	    "config": {
	//	      "ignore_case": true
	//	    }
	//	  }
	//	}
	//
	// 示例2: 多空填空
	//
	//	{
	//	  "id": "card_003b",
	//	  "type": "CARD_TYPE_FILL_BLANK",
	//	  "difficulty": 3,
	//	  "prompt": "完成句子",
	//	  "question": {
	//	    "text": "I ___ an apple. Apples ___ healthy."
	//	  },
	//	  "options": [
	//	    {"id": "blank1", "hint": "verb"},
	//	    {"id": "blank2", "hint": "be verb"}
	//	  ],
	//	  "answer": {
	//	    "correct_values": ["blank1:eat", "blank2:are"],
	//	    "config": {
	//	      "ignore_case": true
	//	    }
	//	  }
	//	}
	//
	// UI渲染: 文本输入框 (text input)
	// 验证逻辑: correct_values 格式统一为 "blankId:answer"
	//
	//	客户端按 options 顺序匹配空位: options[0] 对应第1个 ___, options[1] 对应第2个 ___
	//
	// 注意: question.text 中用 ___ 标识空位 (按出现顺序与 options 对应)
	//
	//	options 必需, 每个 option 对应一个空位 (按顺序), 可提供 hint
	CardType_CARD_TYPE_FILL_BLANK CardType = 3
	// 选词填空题 - 从候选词中选择正确的词填入空位
	//
	// 示例: 从给定词汇中选择填空
	//
	//	{
	//	  "id": "card_004",
	//	  "type": "CARD_TYPE_WORD_SELECTION",
	//	  "difficulty": 2,
	//	  "prompt": "选择正确的单词填空",
	//	  "question": {
	//	    "text": "I eat an ___ every day."
	//	  },
	//	  "options": [
	//	    {"id": "opt1", "text": "apple"},
	//	    {"id": "opt2", "text": "car"},
	//	    {"id": "opt3", "text": "book"}
	//	  ],
	//	  "answer": {
	//	    "correct_values": ["opt1"]
	//	  }
	//	}
	//
	// UI渲染: 拖拽单词到空位 或 下拉选择 (drag-word-to-blank / dropdown)
	// 验证逻辑: userSelectedId == answer.correct_values[0]
	// 注意: 与单选题的区别是UI形态 - 选词填空强调"填入空位"的交互
	CardType_CARD_TYPE_WORD_SELECTION CardType = 4
	// 排序题 - 将打乱的单词重组成正确的句子 (支持选词+排序)
	//
	// 示例1: 句子重组 (所有词都用)
	//
	//	{
	//	  "id": "card_005",
	//	  "type": "CARD_TYPE_ORDERING",
	//	  "difficulty": 3,
	//	  "prompt": "将下列单词组成一个正确的句子",
	//	  "question": {
	//	    "text": "重组句子"
	//	  },
	//	  "options": [
	//	    {"id": "1", "text": "apple"},
	//	    {"id": "2", "text": "an"},
	//	    {"id": "3", "text": "eat"},
	//	    {"id": "4", "text": "I"},
	//	    {"id": "5", "text": "day"},
	//	    {"id": "6", "text": "every"}
	//	  ],
	//	  "answer": {
	//	    "correct_values": ["4", "3", "2", "1", "6", "5"],
	//	    "config": {
	//	      "strict_order": true
	//	    }
	//	  }
	//	}
	//
	// 示例2: 听音选词组句 (带干扰词)
	//
	//	{
	//	  "id": "card_005b",
	//	  "type": "CARD_TYPE_ORDERING",
	//	  "difficulty": 4,
	//	  "prompt": "听音频，选择正确的单词并组成句子",
	//	  "question": {
	//	    "text": "I eat an apple",
	//	    "auto_play": true
	//	  },
	//	  "options": [
	//	    {"id": "1", "text": "I"},
	//	    {"id": "2", "text": "eat"},
	//	    {"id": "3", "text": "an"},
	//	    {"id": "4", "text": "apple"},
	//	    {"id": "5", "text": "banana"},      // 干扰词
	//	    {"id": "6", "text": "drink"}        // 干扰词
	//	  ],
	//	  "answer": {
	//	    "correct_values": ["1", "2", "3", "4"],
	//	    "config": {
	//	      "strict_order": true
	//	    }
	//	  }
	//	}
	//
	// UI渲染: 可拖拽的单词卡片 (draggable word cards)
	// 验证逻辑:
	//   - 所有词都用: userOrder == answer.correct_values
	//   - 有干扰词: userOrder == answer.correct_values (未选择的词忽略)
	//
	// 注意: options 是打乱顺序的单词列表 (可能包含干扰词)
	//
	//	answer.correct_values 是正确的单词ID顺序
	//	question.auto_play=true 表示自动播放音频 (听音选词组句场景)
	CardType_CARD_TYPE_ORDERING CardType = 5
	// 匹配题 - 将左侧项与右侧项配对
	//
	// 示例: 将单词与其释义匹配
	//
	//	{
	//	  "id": "card_006",
	//	  "type": "CARD_TYPE_MATCHING",
	//	  "difficulty": 4,
	//	  "prompt": "将单词与释义匹配",
	//	  "question": {
	//	    "text": "Match words with their meanings"
	//	  },
	//	  "options": [
	//	    {"id": "w1", "text": "apple", "group": "left"},
	//	    {"id": "w2", "text": "car", "group": "left"},
	//	    {"id": "m1", "text": "苹果", "group": "right"},
	//	    {"id": "m2", "text": "汽车", "group": "right"}
	//	  ],
	//	  "answer": {
	//	    "correct_values": ["w1:m1", "w2:m2"]
	//	  }
	//	}
	//
	// UI渲染: 两列布局, 连线或拖拽配对 (two-column matching)
	// 验证逻辑: set(userPairs) == set(answer.correct_values)
	// 注意: options 必须有 group 字段 ("left" 或 "right")
	//
	//	answer.correct_values 格式为 "leftId:rightId"
	CardType_CARD_TYPE_MATCHING CardType = 6
	// 听写题 - 听音频后写出听到的内容 (单词或句子)
	//
	// 示例1: 单词听写
	//
	//	{
	//	  "id": "card_007",
	//	  "type": "CARD_TYPE_DICTATION",
	//	  "difficulty": 2,
	//	  "prompt": "听音频，写出你听到的单词",
	//	  "question": {
	//	    "text": "apple",
	//	    "auto_play": true,
	//	    "phonetics": [{"accent": "US", "text": "/ˈæpl/"}]
	//	  },
	//	  "options": [
	//	    {"id": "hint1", "hint": "5 letters"}
	//	  ],
	//	  "answer": {
	//	    "correct_values": ["apple"],
	//	    "config": {
	//	      "ignore_case": true
	//	    }
	//	  }
	//	}
	//
	// 示例2: 句子听写
	//
	//	{
	//	  "id": "card_007b",
	//	  "type": "CARD_TYPE_DICTATION",
	//	  "difficulty": 4,
	//	  "prompt": "听音频，写出你听到的句子",
	//	  "question": {
	//	    "text": "I eat an apple every day",
	//	    "auto_play": true
	//	  },
	//	  "options": [],
	//	  "answer": {
	//	    "correct_values": ["I eat an apple every day"],
	//	    "config": {
	//	      "ignore_case": true,
	//	      "ignore_punctuation": true
	//	    }
	//	  }
	//	}
	//
	// UI渲染: 音频播放按钮 + 文本输入框 (audio player + text input)
	// 验证逻辑: normalize(userInput) == normalize(answer.correct_values[0])
	// 注意: question.text 不显示给用户, 仅用于生成TTS音频
	//
	//	question.auto_play 通常为 true (自动播放音频)
	//	options 可选, 用于提供提示 (如字母数、单词数)
	CardType_CARD_TYPE_DICTATION CardType = 7
	// 语音题 - 朗读单词或句子, 通过语音识别验证
	//
	// 示例: 跟读单词
	//
	//	{
	//	  "id": "card_008",
	//	  "type": "CARD_TYPE_SPEECH",
	//	  "difficulty": 3,
	//	  "prompt": "跟读单词",
	//	  "question": {
	//	    "text": "apple",
	//	    "auto_play": true,
	//	    "phonetics": [{"accent": "US", "text": "/ˈæpl/"}]
	//	  },
	//	  "options": [],
	//	  "answer": {
	//	    "correct_values": ["apple"],
	//	    "config": {
	//	      "ignore_case": true,
	//	      "min_similarity": 0.85
	//	    }
	//	  }
	//	}
	//
	// UI渲染: 录音按钮 + 波形图 (audio recorder + waveform)
	// 验证逻辑: speech_to_text(userAudio).similarity(answer.correct_values[0]) >= min_similarity
	// 注意: options 通常为空数组
	//
	//	question.auto_play 通常为 true (自动播放目标音频)
	CardType_CARD_TYPE_SPEECH CardType = 8
)

// Enum value maps for CardType.
var (
	CardType_name = map[int32]string{
		0: "CARD_TYPE_UNSPECIFIED",
		1: "CARD_TYPE_SINGLE_CHOICE",
		2: "CARD_TYPE_MULTIPLE_CHOICE",
		3: "CARD_TYPE_FILL_BLANK",
		4: "CARD_TYPE_WORD_SELECTION",
		5: "CARD_TYPE_ORDERING",
		6: "CARD_TYPE_MATCHING",
		7: "CARD_TYPE_DICTATION",
		8: "CARD_TYPE_SPEECH",
	}
	CardType_value = map[string]int32{
		"CARD_TYPE_UNSPECIFIED":     0,
		"CARD_TYPE_SINGLE_CHOICE":   1,
		"CARD_TYPE_MULTIPLE_CHOICE": 2,
		"CARD_TYPE_FILL_BLANK":      3,
		"CARD_TYPE_WORD_SELECTION":  4,
		"CARD_TYPE_ORDERING":        5,
		"CARD_TYPE_MATCHING":        6,
		"CARD_TYPE_DICTATION":       7,
		"CARD_TYPE_SPEECH":          8,
	}
)

func (x CardType) Enum() *CardType {
	p := new(CardType)
	*p = x
	return p
}

func (x CardType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardType) Descriptor() protoreflect.EnumDescriptor {
	return file_learning_v1_flashcard_proto_enumTypes[0].Descriptor()
}

func (CardType) Type() protoreflect.EnumType {
	return &file_learning_v1_flashcard_proto_enumTypes[0]
}

func (x CardType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardType.Descriptor instead.
func (CardType) EnumDescriptor() ([]byte, []int) {
	return file_learning_v1_flashcard_proto_rawDescGZIP(), []int{0}
}

// ============================================================================
// FlashCard - 统一的卡片结构
// ============================================================================
//
// FlashCard 是一个通用的复习卡片数据结构，支持8种题型。
// 客户端根据 `type` 字段选择对应的渲染器和验证逻辑。
//
// 字段使用规范 (按 CardType):
// ┌─────────────────────┬─────────┬──────────┬─────────┬─────────┐
// │ CardType            │ prompt  │ question │ options │ answer  │
// ├─────────────────────┼─────────┼──────────┼─────────┼─────────┤
// │ SINGLE_CHOICE       │ 必需    │ 必需     │ 必需    │ 必需    │
// │ MULTIPLE_CHOICE     │ 必需    │ 必需     │ 必需    │ 必需    │
// │ FILL_BLANK          │ 必需    │ 必需     │ 必需    │ 必需    │
// │ WORD_SELECTION      │ 必需    │ 必需     │ 必需    │ 必需    │
// │ ORDERING            │ 必需    │ 必需     │ 必需    │ 必需    │
// │ MATCHING            │ 必需    │ 必需     │ 必需    │ 必需    │
// │ DICTATION           │ 必需    │ 必需     │ 可选    │ 必需    │
// │ SPEECH              │ 必需    │ 必需     │ 不使用  │ 必需    │
// └─────────────────────┴─────────┴──────────┴─────────┴─────────┘
//
// 数据约束:
//   - SINGLE_CHOICE: options 至少2项, answer.correct_values 长度=1
//   - MULTIPLE_CHOICE: options 至少2项, answer.correct_values 长度≥1
//   - FILL_BLANK: question.text 用 ___ 标识空位, options 必需 (按顺序对应每个空位)
//     answer.correct_values 格式统一为 "blankId:answer" (单空和多空同格式)
//   - WORD_SELECTION: question.text 包含占位符, options 提供候选词 (text字段), answer.correct_values 长度=1
//   - ORDERING: options 是打乱顺序的单词列表, answer.correct_values 是正确句子的单词ID顺序
//   - MATCHING: options 必须有 group 字段 ("left"/"right"), answer 格式为 "leftId:rightId"
//   - DICTATION: question.text 不显示给用户 (仅用于TTS), question.auto_play=true, options 可提供提示
//   - SPEECH: question.auto_play 通常为 true, options 为空数组
//
// 示例见各 CardType 枚举值注释。
type FlashCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                             // 卡片唯一标识
	Annotations   map[string]string      `protobuf:"bytes,2,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 卡片注解
	Type          CardType               `protobuf:"varint,3,opt,name=type,proto3,enum=learning.v1.CardType" json:"type,omitempty"`                                                              // 卡片类型 (决定UI渲染和验证逻辑)
	Difficulty    int32                  `protobuf:"varint,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`                                                                            // 难度等级 (1-5)
	Prompt        string                 `protobuf:"bytes,5,opt,name=prompt,proto3" json:"prompt,omitempty"`                                                                                     // 提示文本/指令 (如 "选择正确的中文释义", "跟读单词")
	Question      *CardQuestion          `protobuf:"bytes,6,opt,name=question,proto3" json:"question,omitempty"`                                                                                 // 具体问题内容
	Answer        *CardAnswer            `protobuf:"bytes,7,opt,name=answer,proto3" json:"answer,omitempty"`                                                                                     // 标准答案和验证规则
	Options       []*CardItem            `protobuf:"bytes,8,rep,name=options,proto3" json:"options,omitempty"`                                                                                   // 可交互项 (选项/填空位/排序项/配对项)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlashCard) Reset() {
	*x = FlashCard{}
	mi := &file_learning_v1_flashcard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlashCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashCard) ProtoMessage() {}

func (x *FlashCard) ProtoReflect() protoreflect.Message {
	mi := &file_learning_v1_flashcard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashCard.ProtoReflect.Descriptor instead.
func (*FlashCard) Descriptor() ([]byte, []int) {
	return file_learning_v1_flashcard_proto_rawDescGZIP(), []int{0}
}

func (x *FlashCard) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FlashCard) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *FlashCard) GetType() CardType {
	if x != nil {
		return x.Type
	}
	return CardType_CARD_TYPE_UNSPECIFIED
}

func (x *FlashCard) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *FlashCard) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *FlashCard) GetQuestion() *CardQuestion {
	if x != nil {
		return x.Question
	}
	return nil
}

func (x *FlashCard) GetAnswer() *CardAnswer {
	if x != nil {
		return x.Answer
	}
	return nil
}

func (x *FlashCard) GetOptions() []*CardItem {
	if x != nil {
		return x.Options
	}
	return nil
}

// ============================================================================
// CardQuestion - 问题内容
// ============================================================================
type CardQuestion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 问题文本，可以是:
	// - 单词 (如 "apple")
	// - 句子 (如 "I eat an ___ every day")
	// - 问题描述 (如 "Which are fruits?")
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// 是否自动播放音频 (通过 TTS API)
	// - 单选/多选题: 通常为 false (用户手动点击播放)
	// - 语音题: 通常为 true (自动播放示范音频)
	AutoPlay bool `protobuf:"varint,2,opt,name=auto_play,json=autoPlay,proto3" json:"auto_play,omitempty"`
	// 音标列表 (当 text 是单词时使用)
	// 示例: [{"accent": "US", "text": "/ˈæpl/"}, {"accent": "UK", "text": "/ˈæpəl/"}]
	Phonetics []*v1.Phonetic `protobuf:"bytes,3,rep,name=phonetics,proto3" json:"phonetics,omitempty"`
	// 问题配图URL (可选)
	// 用途: 帮助理解上下文, 如填空题配图、选择题场景图
	ImageUrl      string `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardQuestion) Reset() {
	*x = CardQuestion{}
	mi := &file_learning_v1_flashcard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardQuestion) ProtoMessage() {}

func (x *CardQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_learning_v1_flashcard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardQuestion.ProtoReflect.Descriptor instead.
func (*CardQuestion) Descriptor() ([]byte, []int) {
	return file_learning_v1_flashcard_proto_rawDescGZIP(), []int{1}
}

func (x *CardQuestion) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CardQuestion) GetAutoPlay() bool {
	if x != nil {
		return x.AutoPlay
	}
	return false
}

func (x *CardQuestion) GetPhonetics() []*v1.Phonetic {
	if x != nil {
		return x.Phonetics
	}
	return nil
}

func (x *CardQuestion) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

// ============================================================================
// CardAnswer - 答案和验证规则
// ============================================================================
type CardAnswer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 正确答案值 (格式因题型而异):
	//
	//   - 单选题 (SINGLE_CHOICE):
	//     选项ID, 长度必须为1
	//     示例: ["A"]
	//
	//   - 多选题 (MULTIPLE_CHOICE):
	//     选项ID列表, 长度≥1
	//     示例: ["A", "C"]
	//
	//   - 填空题 (FILL_BLANK):
	//     可接受的答案文本列表 (支持多个近义词)
	//     示例: ["blankId:apple", "blankId:apples"]
	//
	//   - 排序题 (ORDERING):
	//     排序后的选项ID列表
	//     示例: ["2", "1", "3"] 表示正确顺序是 id=2, id=1, id=3
	//
	//   - 匹配题 (MATCHING):
	//     "leftId:rightId" 格式的配对列表
	//     示例: ["w1:m1", "w2:m2"]
	//
	//   - 语音题 (SPEECH):
	//     目标发音的文本
	//     示例: ["apple"]
	CorrectValues []string `protobuf:"bytes,1,rep,name=correct_values,json=correctValues,proto3" json:"correct_values,omitempty"`
	// 验证配置 (可选)
	Config        *AnswerConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardAnswer) Reset() {
	*x = CardAnswer{}
	mi := &file_learning_v1_flashcard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardAnswer) ProtoMessage() {}

func (x *CardAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_learning_v1_flashcard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardAnswer.ProtoReflect.Descriptor instead.
func (*CardAnswer) Descriptor() ([]byte, []int) {
	return file_learning_v1_flashcard_proto_rawDescGZIP(), []int{2}
}

func (x *CardAnswer) GetCorrectValues() []string {
	if x != nil {
		return x.CorrectValues
	}
	return nil
}

func (x *CardAnswer) GetConfig() *AnswerConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// ============================================================================
// AnswerConfig - 答案验证配置
// ============================================================================
type AnswerConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 忽略大小写 (填空题、语音题常用)
	// true: "Apple" == "apple"
	IgnoreCase bool `protobuf:"varint,1,opt,name=ignore_case,json=ignoreCase,proto3" json:"ignore_case,omitempty"`
	// 忽略重音符号 (填空题常用)
	// true: "café" == "cafe"
	IgnoreAccents bool `protobuf:"varint,2,opt,name=ignore_accents,json=ignoreAccents,proto3" json:"ignore_accents,omitempty"`
	// 忽略标点符号 (听写题常用)
	// true: "Hello, world!" == "Hello world"
	IgnorePunctuation bool `protobuf:"varint,3,opt,name=ignore_punctuation,json=ignorePunctuation,proto3" json:"ignore_punctuation,omitempty"`
	// 严格顺序模式 (排序题专用)
	// true: 必须完全匹配顺序
	// false: 只要部分顺序正确即可 (宽松模式)
	StrictOrder bool `protobuf:"varint,4,opt,name=strict_order,json=strictOrder,proto3" json:"strict_order,omitempty"`
	// 最小相似度阈值 (语音题专用, 范围 0.0-1.0)
	// 通过语音识别转文本后, 计算与 correct_values 的相似度
	// 示例: 0.85 表示相似度≥85%即判定为正确
	MinSimilarity float32 `protobuf:"fixed32,5,opt,name=min_similarity,json=minSimilarity,proto3" json:"min_similarity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerConfig) Reset() {
	*x = AnswerConfig{}
	mi := &file_learning_v1_flashcard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerConfig) ProtoMessage() {}

func (x *AnswerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_learning_v1_flashcard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerConfig.ProtoReflect.Descriptor instead.
func (*AnswerConfig) Descriptor() ([]byte, []int) {
	return file_learning_v1_flashcard_proto_rawDescGZIP(), []int{3}
}

func (x *AnswerConfig) GetIgnoreCase() bool {
	if x != nil {
		return x.IgnoreCase
	}
	return false
}

func (x *AnswerConfig) GetIgnoreAccents() bool {
	if x != nil {
		return x.IgnoreAccents
	}
	return false
}

func (x *AnswerConfig) GetIgnorePunctuation() bool {
	if x != nil {
		return x.IgnorePunctuation
	}
	return false
}

func (x *AnswerConfig) GetStrictOrder() bool {
	if x != nil {
		return x.StrictOrder
	}
	return false
}

func (x *AnswerConfig) GetMinSimilarity() float32 {
	if x != nil {
		return x.MinSimilarity
	}
	return 0
}

// ============================================================================
// CardItem - 可交互项 (选项/填空位/排序项/配对项)
// ============================================================================
type CardItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 项目唯一标识
	// - 选择题: 选项ID (如 "A", "B", "C")
	// - 排序题: 项目ID (如 "1", "2", "3")
	// - 匹配题: 项目ID (如 "w1", "m1")
	// - 填空题: 填空位ID (如 "blank1", "blank2")
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 显示文本
	// - 选择题: 选项内容 (如 "苹果")
	// - 排序题: 待排序项 (如 "dog")
	// - 匹配题: 左侧单词或右侧释义 (如 "apple" / "苹果")
	// - 填空题: 通常为空 (用户输入)
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// 分组标识 (匹配题专用)
	// 值: "left" 或 "right"
	// 示例: {"id": "w1", "text": "apple", "group": "left"}
	Group string `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	// 填空提示 (填空题专用)
	// 示例: "a red fruit" (提示用户答案是一种红色水果)
	Hint string `protobuf:"bytes,4,opt,name=hint,proto3" json:"hint,omitempty"`
	// 是否点击时自动播放音频 (选择题可选)
	// 用途: 听力选择题, 点击选项播放对应音频
	// 示例: true 表示点击该选项时通过 TTS 播放 text 内容
	AutoPlay      bool `protobuf:"varint,5,opt,name=auto_play,json=autoPlay,proto3" json:"auto_play,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardItem) Reset() {
	*x = CardItem{}
	mi := &file_learning_v1_flashcard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardItem) ProtoMessage() {}

func (x *CardItem) ProtoReflect() protoreflect.Message {
	mi := &file_learning_v1_flashcard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardItem.ProtoReflect.Descriptor instead.
func (*CardItem) Descriptor() ([]byte, []int) {
	return file_learning_v1_flashcard_proto_rawDescGZIP(), []int{4}
}

func (x *CardItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CardItem) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CardItem) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *CardItem) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

func (x *CardItem) GetAutoPlay() bool {
	if x != nil {
		return x.AutoPlay
	}
	return false
}

var File_learning_v1_flashcard_proto protoreflect.FileDescriptor

const file_learning_v1_flashcard_proto_rawDesc = "" +
	"\n" +
	"\x1blearning/v1/flashcard.proto\x12\vlearning.v1\x1a\x12dict/v1/word.proto\"\xa2\x03\n" +
	"\tFlashCard\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12I\n" +
	"\vannotations\x18\x02 \x03(\v2'.learning.v1.FlashCard.AnnotationsEntryR\vannotations\x12)\n" +
	"\x04type\x18\x03 \x01(\x0e2\x15.learning.v1.CardTypeR\x04type\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\x05R\n" +
	"difficulty\x12\x16\n" +
	"\x06prompt\x18\x05 \x01(\tR\x06prompt\x125\n" +
	"\bquestion\x18\x06 \x01(\v2\x19.learning.v1.CardQuestionR\bquestion\x12/\n" +
	"\x06answer\x18\a \x01(\v2\x17.learning.v1.CardAnswerR\x06answer\x12/\n" +
	"\aoptions\x18\b \x03(\v2\x15.learning.v1.CardItemR\aoptions\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x01\n" +
	"\fCardQuestion\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1b\n" +
	"\tauto_play\x18\x02 \x01(\bR\bautoPlay\x12/\n" +
	"\tphonetics\x18\x03 \x03(\v2\x11.dict.v1.PhoneticR\tphonetics\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\"f\n" +
	"\n" +
	"CardAnswer\x12%\n" +
	"\x0ecorrect_values\x18\x01 \x03(\tR\rcorrectValues\x121\n" +
	"\x06config\x18\x02 \x01(\v2\x19.learning.v1.AnswerConfigR\x06config\"\xcf\x01\n" +
	"\fAnswerConfig\x12\x1f\n" +
	"\vignore_case\x18\x01 \x01(\bR\n" +
	"ignoreCase\x12%\n" +
	"\x0eignore_accents\x18\x02 \x01(\bR\rignoreAccents\x12-\n" +
	"\x12ignore_punctuation\x18\x03 \x01(\bR\x11ignorePunctuation\x12!\n" +
	"\fstrict_order\x18\x04 \x01(\bR\vstrictOrder\x12%\n" +
	"\x0emin_similarity\x18\x05 \x01(\x02R\rminSimilarity\"u\n" +
	"\bCardItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12\x12\n" +
	"\x04hint\x18\x04 \x01(\tR\x04hint\x12\x1b\n" +
	"\tauto_play\x18\x05 \x01(\bR\bautoPlay*\xf8\x01\n" +
	"\bCardType\x12\x19\n" +
	"\x15CARD_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CARD_TYPE_SINGLE_CHOICE\x10\x01\x12\x1d\n" +
	"\x19CARD_TYPE_MULTIPLE_CHOICE\x10\x02\x12\x18\n" +
	"\x14CARD_TYPE_FILL_BLANK\x10\x03\x12\x1c\n" +
	"\x18CARD_TYPE_WORD_SELECTION\x10\x04\x12\x16\n" +
	"\x12CARD_TYPE_ORDERING\x10\x05\x12\x16\n" +
	"\x12CARD_TYPE_MATCHING\x10\x06\x12\x17\n" +
	"\x13CARD_TYPE_DICTATION\x10\a\x12\x14\n" +
	"\x10CARD_TYPE_SPEECH\x10\bB\xa8\x01\n" +
	"\x0fcom.learning.v1B\x0eFlashcardProtoP\x01Z8github.com/eslsoft/vocnet/pkg/api/learning/v1;learningv1\xa2\x02\x03LXX\xaa\x02\vLearning.V1\xca\x02\vLearning\\V1\xe2\x02\x17Learning\\V1\\GPBMetadata\xea\x02\fLearning::V1b\x06proto3"

var (
	file_learning_v1_flashcard_proto_rawDescOnce sync.Once
	file_learning_v1_flashcard_proto_rawDescData []byte
)

func file_learning_v1_flashcard_proto_rawDescGZIP() []byte {
	file_learning_v1_flashcard_proto_rawDescOnce.Do(func() {
		file_learning_v1_flashcard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_learning_v1_flashcard_proto_rawDesc), len(file_learning_v1_flashcard_proto_rawDesc)))
	})
	return file_learning_v1_flashcard_proto_rawDescData
}

var file_learning_v1_flashcard_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_learning_v1_flashcard_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_learning_v1_flashcard_proto_goTypes = []any{
	(CardType)(0),        // 0: learning.v1.CardType
	(*FlashCard)(nil),    // 1: learning.v1.FlashCard
	(*CardQuestion)(nil), // 2: learning.v1.CardQuestion
	(*CardAnswer)(nil),   // 3: learning.v1.CardAnswer
	(*AnswerConfig)(nil), // 4: learning.v1.AnswerConfig
	(*CardItem)(nil),     // 5: learning.v1.CardItem
	nil,                  // 6: learning.v1.FlashCard.AnnotationsEntry
	(*v1.Phonetic)(nil),  // 7: dict.v1.Phonetic
}
var file_learning_v1_flashcard_proto_depIdxs = []int32{
	6, // 0: learning.v1.FlashCard.annotations:type_name -> learning.v1.FlashCard.AnnotationsEntry
	0, // 1: learning.v1.FlashCard.type:type_name -> learning.v1.CardType
	2, // 2: learning.v1.FlashCard.question:type_name -> learning.v1.CardQuestion
	3, // 3: learning.v1.FlashCard.answer:type_name -> learning.v1.CardAnswer
	5, // 4: learning.v1.FlashCard.options:type_name -> learning.v1.CardItem
	7, // 5: learning.v1.CardQuestion.phonetics:type_name -> dict.v1.Phonetic
	4, // 6: learning.v1.CardAnswer.config:type_name -> learning.v1.AnswerConfig
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_learning_v1_flashcard_proto_init() }
func file_learning_v1_flashcard_proto_init() {
	if File_learning_v1_flashcard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_learning_v1_flashcard_proto_rawDesc), len(file_learning_v1_flashcard_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_learning_v1_flashcard_proto_goTypes,
		DependencyIndexes: file_learning_v1_flashcard_proto_depIdxs,
		EnumInfos:         file_learning_v1_flashcard_proto_enumTypes,
		MessageInfos:      file_learning_v1_flashcard_proto_msgTypes,
	}.Build()
	File_learning_v1_flashcard_proto = out.File
	file_learning_v1_flashcard_proto_goTypes = nil
	file_learning_v1_flashcard_proto_depIdxs = nil
}
