// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: learning/v1/learning_service.proto

package learningv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	v1 "github.com/eslsoft/vocnet/pkg/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Key for identifying a learned lexeme entry.
type LearnedLexemeKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LexemeId      int64                  `protobuf:"varint,1,opt,name=lexeme_id,json=lexemeId,proto3" json:"lexeme_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LearnedLexemeKey) Reset() {
	*x = LearnedLexemeKey{}
	mi := &file_learning_v1_learning_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LearnedLexemeKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearnedLexemeKey) ProtoMessage() {}

func (x *LearnedLexemeKey) ProtoReflect() protoreflect.Message {
	mi := &file_learning_v1_learning_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearnedLexemeKey.ProtoReflect.Descriptor instead.
func (*LearnedLexemeKey) Descriptor() ([]byte, []int) {
	return file_learning_v1_learning_service_proto_rawDescGZIP(), []int{0}
}

func (x *LearnedLexemeKey) GetLexemeId() int64 {
	if x != nil {
		return x.LexemeId
	}
	return 0
}

// CollectLexeme request - main API for adding lexemes to the user's vocabulary.
type CollectLexemeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lexeme        *LearnedLexeme         `protobuf:"bytes,1,opt,name=lexeme,proto3" json:"lexeme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectLexemeRequest) Reset() {
	*x = CollectLexemeRequest{}
	mi := &file_learning_v1_learning_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectLexemeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectLexemeRequest) ProtoMessage() {}

func (x *CollectLexemeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_learning_v1_learning_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectLexemeRequest.ProtoReflect.Descriptor instead.
func (*CollectLexemeRequest) Descriptor() ([]byte, []int) {
	return file_learning_v1_learning_service_proto_rawDescGZIP(), []int{1}
}

func (x *CollectLexemeRequest) GetLexeme() *LearnedLexeme {
	if x != nil {
		return x.Lexeme
	}
	return nil
}

// UpdateMasteryRequest updates mastery, review schedule, and optional form mastery.
type UpdateMasteryRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	LexemeId      int64                   `protobuf:"varint,1,opt,name=lexeme_id,json=lexemeId,proto3" json:"lexeme_id,omitempty"`
	Mastery       *MasteryBreakdown       `protobuf:"bytes,2,opt,name=mastery,proto3" json:"mastery,omitempty"`
	Review        *ReviewTiming           `protobuf:"bytes,3,opt,name=review,proto3" json:"review,omitempty"`
	FormStatus    map[string]*FormMastery `protobuf:"bytes,4,rep,name=form_status,json=formStatus,proto3" json:"form_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Note          string                  `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMasteryRequest) Reset() {
	*x = UpdateMasteryRequest{}
	mi := &file_learning_v1_learning_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMasteryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMasteryRequest) ProtoMessage() {}

func (x *UpdateMasteryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_learning_v1_learning_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMasteryRequest.ProtoReflect.Descriptor instead.
func (*UpdateMasteryRequest) Descriptor() ([]byte, []int) {
	return file_learning_v1_learning_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateMasteryRequest) GetLexemeId() int64 {
	if x != nil {
		return x.LexemeId
	}
	return 0
}

func (x *UpdateMasteryRequest) GetMastery() *MasteryBreakdown {
	if x != nil {
		return x.Mastery
	}
	return nil
}

func (x *UpdateMasteryRequest) GetReview() *ReviewTiming {
	if x != nil {
		return x.Review
	}
	return nil
}

func (x *UpdateMasteryRequest) GetFormStatus() map[string]*FormMastery {
	if x != nil {
		return x.FormStatus
	}
	return nil
}

func (x *UpdateMasteryRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

// ListLearnedLexemesRequest request with comprehensive filtering.
type ListLearnedLexemesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *v1.PaginationRequest  `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Filter        string                 `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy       string                 `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	LexemeIds     []string               `protobuf:"bytes,4,rep,name=lexeme_ids,json=lexemeIds,proto3" json:"lexeme_ids,omitempty"`
	SurfaceTerms  []string               `protobuf:"bytes,5,rep,name=surface_terms,json=surfaceTerms,proto3" json:"surface_terms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLearnedLexemesRequest) Reset() {
	*x = ListLearnedLexemesRequest{}
	mi := &file_learning_v1_learning_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLearnedLexemesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLearnedLexemesRequest) ProtoMessage() {}

func (x *ListLearnedLexemesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_learning_v1_learning_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLearnedLexemesRequest.ProtoReflect.Descriptor instead.
func (*ListLearnedLexemesRequest) Descriptor() ([]byte, []int) {
	return file_learning_v1_learning_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListLearnedLexemesRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListLearnedLexemesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListLearnedLexemesRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListLearnedLexemesRequest) GetLexemeIds() []string {
	if x != nil {
		return x.LexemeIds
	}
	return nil
}

func (x *ListLearnedLexemesRequest) GetSurfaceTerms() []string {
	if x != nil {
		return x.SurfaceTerms
	}
	return nil
}

type ListLearnedLexemesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *v1.PaginationResponse `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Lexemes       []*LearnedLexeme       `protobuf:"bytes,2,rep,name=lexemes,proto3" json:"lexemes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLearnedLexemesResponse) Reset() {
	*x = ListLearnedLexemesResponse{}
	mi := &file_learning_v1_learning_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLearnedLexemesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLearnedLexemesResponse) ProtoMessage() {}

func (x *ListLearnedLexemesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_learning_v1_learning_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLearnedLexemesResponse.ProtoReflect.Descriptor instead.
func (*ListLearnedLexemesResponse) Descriptor() ([]byte, []int) {
	return file_learning_v1_learning_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListLearnedLexemesResponse) GetPagination() *v1.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListLearnedLexemesResponse) GetLexemes() []*LearnedLexeme {
	if x != nil {
		return x.Lexemes
	}
	return nil
}

var File_learning_v1_learning_service_proto protoreflect.FileDescriptor

const file_learning_v1_learning_service_proto_rawDesc = "" +
	"\n" +
	"\"learning/v1/learning_service.proto\x12\vlearning.v1\x1a\x15common/v1/types.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1alearning/v1/learning.proto\x1a\x17validate/validate.proto\"8\n" +
	"\x10LearnedLexemeKey\x12$\n" +
	"\tlexeme_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\blexemeId\"T\n" +
	"\x14CollectLexemeRequest\x12<\n" +
	"\x06lexeme\x18\x01 \x01(\v2\x1a.learning.v1.LearnedLexemeB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x06lexeme\"\xe9\x02\n" +
	"\x14UpdateMasteryRequest\x12$\n" +
	"\tlexeme_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\blexemeId\x127\n" +
	"\amastery\x18\x02 \x01(\v2\x1d.learning.v1.MasteryBreakdownR\amastery\x121\n" +
	"\x06review\x18\x03 \x01(\v2\x19.learning.v1.ReviewTimingR\x06review\x12R\n" +
	"\vform_status\x18\x04 \x03(\v21.learning.v1.UpdateMasteryRequest.FormStatusEntryR\n" +
	"formStatus\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\x1aW\n" +
	"\x0fFormStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.learning.v1.FormMasteryR\x05value:\x028\x01\"\xd0\x01\n" +
	"\x19ListLearnedLexemesRequest\x12<\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1c.common.v1.PaginationRequestR\n" +
	"pagination\x12\x16\n" +
	"\x06filter\x18\x02 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x03 \x01(\tR\aorderBy\x12\x1d\n" +
	"\n" +
	"lexeme_ids\x18\x04 \x03(\tR\tlexemeIds\x12#\n" +
	"\rsurface_terms\x18\x05 \x03(\tR\fsurfaceTerms\"\x91\x01\n" +
	"\x1aListLearnedLexemesResponse\x12=\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1d.common.v1.PaginationResponseR\n" +
	"pagination\x124\n" +
	"\alexemes\x18\x02 \x03(\v2\x1a.learning.v1.LearnedLexemeR\alexemes2\xea\x02\n" +
	"\x0fLearningService\x12P\n" +
	"\rCollectLexeme\x12!.learning.v1.CollectLexemeRequest\x1a\x1a.learning.v1.LearnedLexeme\"\x00\x12J\n" +
	"\x0fUncollectLexeme\x12\x1d.learning.v1.LearnedLexemeKey\x1a\x16.google.protobuf.Empty\"\x00\x12g\n" +
	"\x12ListLearnedLexemes\x12&.learning.v1.ListLearnedLexemesRequest\x1a'.learning.v1.ListLearnedLexemesResponse\"\x00\x12P\n" +
	"\rUpdateMastery\x12!.learning.v1.UpdateMasteryRequest\x1a\x1a.learning.v1.LearnedLexeme\"\x00B\xae\x01\n" +
	"\x0fcom.learning.v1B\x14LearningServiceProtoP\x01Z8github.com/eslsoft/vocnet/pkg/api/learning/v1;learningv1\xa2\x02\x03LXX\xaa\x02\vLearning.V1\xca\x02\vLearning\\V1\xe2\x02\x17Learning\\V1\\GPBMetadata\xea\x02\fLearning::V1b\x06proto3"

var (
	file_learning_v1_learning_service_proto_rawDescOnce sync.Once
	file_learning_v1_learning_service_proto_rawDescData []byte
)

func file_learning_v1_learning_service_proto_rawDescGZIP() []byte {
	file_learning_v1_learning_service_proto_rawDescOnce.Do(func() {
		file_learning_v1_learning_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_learning_v1_learning_service_proto_rawDesc), len(file_learning_v1_learning_service_proto_rawDesc)))
	})
	return file_learning_v1_learning_service_proto_rawDescData
}

var file_learning_v1_learning_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_learning_v1_learning_service_proto_goTypes = []any{
	(*LearnedLexemeKey)(nil),           // 0: learning.v1.LearnedLexemeKey
	(*CollectLexemeRequest)(nil),       // 1: learning.v1.CollectLexemeRequest
	(*UpdateMasteryRequest)(nil),       // 2: learning.v1.UpdateMasteryRequest
	(*ListLearnedLexemesRequest)(nil),  // 3: learning.v1.ListLearnedLexemesRequest
	(*ListLearnedLexemesResponse)(nil), // 4: learning.v1.ListLearnedLexemesResponse
	nil,                                // 5: learning.v1.UpdateMasteryRequest.FormStatusEntry
	(*LearnedLexeme)(nil),              // 6: learning.v1.LearnedLexeme
	(*MasteryBreakdown)(nil),           // 7: learning.v1.MasteryBreakdown
	(*ReviewTiming)(nil),               // 8: learning.v1.ReviewTiming
	(*v1.PaginationRequest)(nil),       // 9: common.v1.PaginationRequest
	(*v1.PaginationResponse)(nil),      // 10: common.v1.PaginationResponse
	(*FormMastery)(nil),                // 11: learning.v1.FormMastery
	(*emptypb.Empty)(nil),              // 12: google.protobuf.Empty
}
var file_learning_v1_learning_service_proto_depIdxs = []int32{
	6,  // 0: learning.v1.CollectLexemeRequest.lexeme:type_name -> learning.v1.LearnedLexeme
	7,  // 1: learning.v1.UpdateMasteryRequest.mastery:type_name -> learning.v1.MasteryBreakdown
	8,  // 2: learning.v1.UpdateMasteryRequest.review:type_name -> learning.v1.ReviewTiming
	5,  // 3: learning.v1.UpdateMasteryRequest.form_status:type_name -> learning.v1.UpdateMasteryRequest.FormStatusEntry
	9,  // 4: learning.v1.ListLearnedLexemesRequest.pagination:type_name -> common.v1.PaginationRequest
	10, // 5: learning.v1.ListLearnedLexemesResponse.pagination:type_name -> common.v1.PaginationResponse
	6,  // 6: learning.v1.ListLearnedLexemesResponse.lexemes:type_name -> learning.v1.LearnedLexeme
	11, // 7: learning.v1.UpdateMasteryRequest.FormStatusEntry.value:type_name -> learning.v1.FormMastery
	1,  // 8: learning.v1.LearningService.CollectLexeme:input_type -> learning.v1.CollectLexemeRequest
	0,  // 9: learning.v1.LearningService.UncollectLexeme:input_type -> learning.v1.LearnedLexemeKey
	3,  // 10: learning.v1.LearningService.ListLearnedLexemes:input_type -> learning.v1.ListLearnedLexemesRequest
	2,  // 11: learning.v1.LearningService.UpdateMastery:input_type -> learning.v1.UpdateMasteryRequest
	6,  // 12: learning.v1.LearningService.CollectLexeme:output_type -> learning.v1.LearnedLexeme
	12, // 13: learning.v1.LearningService.UncollectLexeme:output_type -> google.protobuf.Empty
	4,  // 14: learning.v1.LearningService.ListLearnedLexemes:output_type -> learning.v1.ListLearnedLexemesResponse
	6,  // 15: learning.v1.LearningService.UpdateMastery:output_type -> learning.v1.LearnedLexeme
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_learning_v1_learning_service_proto_init() }
func file_learning_v1_learning_service_proto_init() {
	if File_learning_v1_learning_service_proto != nil {
		return
	}
	file_learning_v1_learning_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_learning_v1_learning_service_proto_rawDesc), len(file_learning_v1_learning_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_learning_v1_learning_service_proto_goTypes,
		DependencyIndexes: file_learning_v1_learning_service_proto_depIdxs,
		MessageInfos:      file_learning_v1_learning_service_proto_msgTypes,
	}.Build()
	File_learning_v1_learning_service_proto = out.File
	file_learning_v1_learning_service_proto_goTypes = nil
	file_learning_v1_learning_service_proto_depIdxs = nil
}
