// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: learning/v1/learning_service.proto

package learningv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	v1 "github.com/eslsoft/vocnet/pkg/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Key for identifying a learned word entry.
type LearnedWordKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WordId        int64                  `protobuf:"varint,1,opt,name=word_id,json=wordId,proto3" json:"word_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LearnedWordKey) Reset() {
	*x = LearnedWordKey{}
	mi := &file_learning_v1_learning_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LearnedWordKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearnedWordKey) ProtoMessage() {}

func (x *LearnedWordKey) ProtoReflect() protoreflect.Message {
	mi := &file_learning_v1_learning_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearnedWordKey.ProtoReflect.Descriptor instead.
func (*LearnedWordKey) Descriptor() ([]byte, []int) {
	return file_learning_v1_learning_service_proto_rawDescGZIP(), []int{0}
}

func (x *LearnedWordKey) GetWordId() int64 {
	if x != nil {
		return x.WordId
	}
	return 0
}

// CollectWord request - main API for adding words to the user's vocabulary.
type CollectWordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          *LearnedWord           `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectWordRequest) Reset() {
	*x = CollectWordRequest{}
	mi := &file_learning_v1_learning_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectWordRequest) ProtoMessage() {}

func (x *CollectWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_learning_v1_learning_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectWordRequest.ProtoReflect.Descriptor instead.
func (*CollectWordRequest) Descriptor() ([]byte, []int) {
	return file_learning_v1_learning_service_proto_rawDescGZIP(), []int{1}
}

func (x *CollectWordRequest) GetWord() *LearnedWord {
	if x != nil {
		return x.Word
	}
	return nil
}

// UpdateMasteryRequest updates mastery and review schedule.
type UpdateMasteryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WordId        int64                  `protobuf:"varint,1,opt,name=word_id,json=wordId,proto3" json:"word_id,omitempty"`
	Mastery       *MasteryBreakdown      `protobuf:"bytes,2,opt,name=mastery,proto3" json:"mastery,omitempty"`
	Review        *ReviewTiming          `protobuf:"bytes,3,opt,name=review,proto3" json:"review,omitempty"`
	Note          string                 `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMasteryRequest) Reset() {
	*x = UpdateMasteryRequest{}
	mi := &file_learning_v1_learning_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMasteryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMasteryRequest) ProtoMessage() {}

func (x *UpdateMasteryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_learning_v1_learning_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMasteryRequest.ProtoReflect.Descriptor instead.
func (*UpdateMasteryRequest) Descriptor() ([]byte, []int) {
	return file_learning_v1_learning_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateMasteryRequest) GetWordId() int64 {
	if x != nil {
		return x.WordId
	}
	return 0
}

func (x *UpdateMasteryRequest) GetMastery() *MasteryBreakdown {
	if x != nil {
		return x.Mastery
	}
	return nil
}

func (x *UpdateMasteryRequest) GetReview() *ReviewTiming {
	if x != nil {
		return x.Review
	}
	return nil
}

func (x *UpdateMasteryRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

// ListLearnedWordsRequest request with comprehensive filtering.
type ListLearnedWordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *v1.PaginationRequest  `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Filter        string                 `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy       string                 `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLearnedWordsRequest) Reset() {
	*x = ListLearnedWordsRequest{}
	mi := &file_learning_v1_learning_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLearnedWordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLearnedWordsRequest) ProtoMessage() {}

func (x *ListLearnedWordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_learning_v1_learning_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLearnedWordsRequest.ProtoReflect.Descriptor instead.
func (*ListLearnedWordsRequest) Descriptor() ([]byte, []int) {
	return file_learning_v1_learning_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListLearnedWordsRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListLearnedWordsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListLearnedWordsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type ListLearnedWordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *v1.PaginationResponse `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Words         []*LearnedWord         `protobuf:"bytes,2,rep,name=words,proto3" json:"words,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLearnedWordsResponse) Reset() {
	*x = ListLearnedWordsResponse{}
	mi := &file_learning_v1_learning_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLearnedWordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLearnedWordsResponse) ProtoMessage() {}

func (x *ListLearnedWordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_learning_v1_learning_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLearnedWordsResponse.ProtoReflect.Descriptor instead.
func (*ListLearnedWordsResponse) Descriptor() ([]byte, []int) {
	return file_learning_v1_learning_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListLearnedWordsResponse) GetPagination() *v1.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListLearnedWordsResponse) GetWords() []*LearnedWord {
	if x != nil {
		return x.Words
	}
	return nil
}

var File_learning_v1_learning_service_proto protoreflect.FileDescriptor

const file_learning_v1_learning_service_proto_rawDesc = "" +
	"\n" +
	"\"learning/v1/learning_service.proto\x12\vlearning.v1\x1a\x15common/v1/types.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1alearning/v1/learning.proto\x1a\x17validate/validate.proto\"2\n" +
	"\x0eLearnedWordKey\x12 \n" +
	"\aword_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06wordId\"L\n" +
	"\x12CollectWordRequest\x126\n" +
	"\x04word\x18\x01 \x01(\v2\x18.learning.v1.LearnedWordB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x04word\"\xb8\x01\n" +
	"\x14UpdateMasteryRequest\x12 \n" +
	"\aword_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06wordId\x127\n" +
	"\amastery\x18\x02 \x01(\v2\x1d.learning.v1.MasteryBreakdownR\amastery\x121\n" +
	"\x06review\x18\x03 \x01(\v2\x19.learning.v1.ReviewTimingR\x06review\x12\x12\n" +
	"\x04note\x18\x04 \x01(\tR\x04note\"\x8a\x01\n" +
	"\x17ListLearnedWordsRequest\x12<\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1c.common.v1.PaginationRequestR\n" +
	"pagination\x12\x16\n" +
	"\x06filter\x18\x02 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x03 \x01(\tR\aorderBy\"\x89\x01\n" +
	"\x18ListLearnedWordsResponse\x12=\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1d.common.v1.PaginationResponseR\n" +
	"pagination\x12.\n" +
	"\x05words\x18\x02 \x03(\v2\x18.learning.v1.LearnedWordR\x05words2\xa3\x03\n" +
	"\x0fLearningService\x12J\n" +
	"\vCollectWord\x12\x1f.learning.v1.CollectWordRequest\x1a\x18.learning.v1.LearnedWord\"\x00\x12F\n" +
	"\rUncollectWord\x12\x1b.learning.v1.LearnedWordKey\x1a\x16.google.protobuf.Empty\"\x00\x12I\n" +
	"\x0eGetLearnedWord\x12\x1b.learning.v1.LearnedWordKey\x1a\x18.learning.v1.LearnedWord\"\x00\x12a\n" +
	"\x10ListLearnedWords\x12$.learning.v1.ListLearnedWordsRequest\x1a%.learning.v1.ListLearnedWordsResponse\"\x00\x12N\n" +
	"\rUpdateMastery\x12!.learning.v1.UpdateMasteryRequest\x1a\x18.learning.v1.LearnedWord\"\x00B\xae\x01\n" +
	"\x0fcom.learning.v1B\x14LearningServiceProtoP\x01Z8github.com/eslsoft/vocnet/pkg/api/learning/v1;learningv1\xa2\x02\x03LXX\xaa\x02\vLearning.V1\xca\x02\vLearning\\V1\xe2\x02\x17Learning\\V1\\GPBMetadata\xea\x02\fLearning::V1b\x06proto3"

var (
	file_learning_v1_learning_service_proto_rawDescOnce sync.Once
	file_learning_v1_learning_service_proto_rawDescData []byte
)

func file_learning_v1_learning_service_proto_rawDescGZIP() []byte {
	file_learning_v1_learning_service_proto_rawDescOnce.Do(func() {
		file_learning_v1_learning_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_learning_v1_learning_service_proto_rawDesc), len(file_learning_v1_learning_service_proto_rawDesc)))
	})
	return file_learning_v1_learning_service_proto_rawDescData
}

var file_learning_v1_learning_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_learning_v1_learning_service_proto_goTypes = []any{
	(*LearnedWordKey)(nil),           // 0: learning.v1.LearnedWordKey
	(*CollectWordRequest)(nil),       // 1: learning.v1.CollectWordRequest
	(*UpdateMasteryRequest)(nil),     // 2: learning.v1.UpdateMasteryRequest
	(*ListLearnedWordsRequest)(nil),  // 3: learning.v1.ListLearnedWordsRequest
	(*ListLearnedWordsResponse)(nil), // 4: learning.v1.ListLearnedWordsResponse
	(*LearnedWord)(nil),              // 5: learning.v1.LearnedWord
	(*MasteryBreakdown)(nil),         // 6: learning.v1.MasteryBreakdown
	(*ReviewTiming)(nil),             // 7: learning.v1.ReviewTiming
	(*v1.PaginationRequest)(nil),     // 8: common.v1.PaginationRequest
	(*v1.PaginationResponse)(nil),    // 9: common.v1.PaginationResponse
	(*emptypb.Empty)(nil),            // 10: google.protobuf.Empty
}
var file_learning_v1_learning_service_proto_depIdxs = []int32{
	5,  // 0: learning.v1.CollectWordRequest.word:type_name -> learning.v1.LearnedWord
	6,  // 1: learning.v1.UpdateMasteryRequest.mastery:type_name -> learning.v1.MasteryBreakdown
	7,  // 2: learning.v1.UpdateMasteryRequest.review:type_name -> learning.v1.ReviewTiming
	8,  // 3: learning.v1.ListLearnedWordsRequest.pagination:type_name -> common.v1.PaginationRequest
	9,  // 4: learning.v1.ListLearnedWordsResponse.pagination:type_name -> common.v1.PaginationResponse
	5,  // 5: learning.v1.ListLearnedWordsResponse.words:type_name -> learning.v1.LearnedWord
	1,  // 6: learning.v1.LearningService.CollectWord:input_type -> learning.v1.CollectWordRequest
	0,  // 7: learning.v1.LearningService.UncollectWord:input_type -> learning.v1.LearnedWordKey
	0,  // 8: learning.v1.LearningService.GetLearnedWord:input_type -> learning.v1.LearnedWordKey
	3,  // 9: learning.v1.LearningService.ListLearnedWords:input_type -> learning.v1.ListLearnedWordsRequest
	2,  // 10: learning.v1.LearningService.UpdateMastery:input_type -> learning.v1.UpdateMasteryRequest
	5,  // 11: learning.v1.LearningService.CollectWord:output_type -> learning.v1.LearnedWord
	10, // 12: learning.v1.LearningService.UncollectWord:output_type -> google.protobuf.Empty
	5,  // 13: learning.v1.LearningService.GetLearnedWord:output_type -> learning.v1.LearnedWord
	4,  // 14: learning.v1.LearningService.ListLearnedWords:output_type -> learning.v1.ListLearnedWordsResponse
	5,  // 15: learning.v1.LearningService.UpdateMastery:output_type -> learning.v1.LearnedWord
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_learning_v1_learning_service_proto_init() }
func file_learning_v1_learning_service_proto_init() {
	if File_learning_v1_learning_service_proto != nil {
		return
	}
	file_learning_v1_learning_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_learning_v1_learning_service_proto_rawDesc), len(file_learning_v1_learning_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_learning_v1_learning_service_proto_goTypes,
		DependencyIndexes: file_learning_v1_learning_service_proto_depIdxs,
		MessageInfos:      file_learning_v1_learning_service_proto_msgTypes,
	}.Build()
	File_learning_v1_learning_service_proto = out.File
	file_learning_v1_learning_service_proto_goTypes = nil
	file_learning_v1_learning_service_proto_depIdxs = nil
}
