// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: learning/v1/learning_service.proto

package learningv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	v1 "github.com/eslsoft/vocnet/pkg/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CollectWord request - main API for adding words to the user's vocabulary.
type CollectWordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *LearnedWordSpec       `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectWordRequest) Reset() {
	*x = CollectWordRequest{}
	mi := &file_learning_v1_learning_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectWordRequest) ProtoMessage() {}

func (x *CollectWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_learning_v1_learning_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectWordRequest.ProtoReflect.Descriptor instead.
func (*CollectWordRequest) Descriptor() ([]byte, []int) {
	return file_learning_v1_learning_service_proto_rawDescGZIP(), []int{0}
}

func (x *CollectWordRequest) GetSpec() *LearnedWordSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// UpdateMasteryRequest updates mastery using simple user perception (0-5).
// The system will automatically convert this to four-dimensional breakdown
// using the same logic as CollectWord (InitializeFromUserMasteryLevel).
type UpdateMasteryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // LearnedWord ID
	// User's overall mastery perception (0-5):
	//
	//	0 = unknown/not started
	//	1 = seen before (vague recognition)
	//	2 = recognize in context (can understand when seen/heard)
	//	3 = know meaning well (solid comprehension, limited production)
	//	4 = can use passively (excellent comprehension, emerging active use)
	//	5 = fully mastered (fluent in all skills)
	//
	// This will be expanded into four skill dimensions automatically.
	MasteryLevel  int32    `protobuf:"varint,2,opt,name=mastery_level,json=masteryLevel,proto3" json:"mastery_level,omitempty"`
	Tags          []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Notes         []string `protobuf:"bytes,4,rep,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMasteryRequest) Reset() {
	*x = UpdateMasteryRequest{}
	mi := &file_learning_v1_learning_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMasteryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMasteryRequest) ProtoMessage() {}

func (x *UpdateMasteryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_learning_v1_learning_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMasteryRequest.ProtoReflect.Descriptor instead.
func (*UpdateMasteryRequest) Descriptor() ([]byte, []int) {
	return file_learning_v1_learning_service_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateMasteryRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMasteryRequest) GetMasteryLevel() int32 {
	if x != nil {
		return x.MasteryLevel
	}
	return 0
}

func (x *UpdateMasteryRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateMasteryRequest) GetNotes() []string {
	if x != nil {
		return x.Notes
	}
	return nil
}

// ListLearnedWordsRequest request with comprehensive filtering.
type ListLearnedWordsRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Pagination *v1.PaginationRequest  `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Filter     string                 `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy    string                 `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	// auto_inherit_mastery controls whether inflected forms (e.g., "running")
	// inherit mastery from their lemma (e.g., "run") when the inflection isn't
	// directly stored. Default: false (disabled).
	AutoInheritMastery bool `protobuf:"varint,4,opt,name=auto_inherit_mastery,json=autoInheritMastery,proto3" json:"auto_inherit_mastery,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListLearnedWordsRequest) Reset() {
	*x = ListLearnedWordsRequest{}
	mi := &file_learning_v1_learning_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLearnedWordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLearnedWordsRequest) ProtoMessage() {}

func (x *ListLearnedWordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_learning_v1_learning_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLearnedWordsRequest.ProtoReflect.Descriptor instead.
func (*ListLearnedWordsRequest) Descriptor() ([]byte, []int) {
	return file_learning_v1_learning_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListLearnedWordsRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListLearnedWordsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListLearnedWordsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListLearnedWordsRequest) GetAutoInheritMastery() bool {
	if x != nil {
		return x.AutoInheritMastery
	}
	return false
}

type ListLearnedWordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *v1.PaginationResponse `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Words         []*LearnedWord         `protobuf:"bytes,2,rep,name=words,proto3" json:"words,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLearnedWordsResponse) Reset() {
	*x = ListLearnedWordsResponse{}
	mi := &file_learning_v1_learning_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLearnedWordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLearnedWordsResponse) ProtoMessage() {}

func (x *ListLearnedWordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_learning_v1_learning_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLearnedWordsResponse.ProtoReflect.Descriptor instead.
func (*ListLearnedWordsResponse) Descriptor() ([]byte, []int) {
	return file_learning_v1_learning_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListLearnedWordsResponse) GetPagination() *v1.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListLearnedWordsResponse) GetWords() []*LearnedWord {
	if x != nil {
		return x.Words
	}
	return nil
}

var File_learning_v1_learning_service_proto protoreflect.FileDescriptor

const file_learning_v1_learning_service_proto_rawDesc = "" +
	"\n" +
	"\"learning/v1/learning_service.proto\x12\vlearning.v1\x1a\x15common/v1/types.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1alearning/v1/learning.proto\x1a\x17validate/validate.proto\"P\n" +
	"\x12CollectWordRequest\x12:\n" +
	"\x04spec\x18\x01 \x01(\v2\x1c.learning.v1.LearnedWordSpecB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x04spec\"\x89\x01\n" +
	"\x14UpdateMasteryRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\x12.\n" +
	"\rmastery_level\x18\x02 \x01(\x05B\t\xfaB\x06\x1a\x04\x18\x05(\x00R\fmasteryLevel\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x14\n" +
	"\x05notes\x18\x04 \x03(\tR\x05notes\"\xbc\x01\n" +
	"\x17ListLearnedWordsRequest\x12<\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1c.common.v1.PaginationRequestR\n" +
	"pagination\x12\x16\n" +
	"\x06filter\x18\x02 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x03 \x01(\tR\aorderBy\x120\n" +
	"\x14auto_inherit_mastery\x18\x04 \x01(\bR\x12autoInheritMastery\"\x89\x01\n" +
	"\x18ListLearnedWordsResponse\x12=\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1d.common.v1.PaginationResponseR\n" +
	"pagination\x12.\n" +
	"\x05words\x18\x02 \x03(\v2\x18.learning.v1.LearnedWordR\x05words2\x95\x03\n" +
	"\x0fLearningService\x12J\n" +
	"\vCollectWord\x12\x1f.learning.v1.CollectWordRequest\x1a\x18.learning.v1.LearnedWord\"\x00\x12?\n" +
	"\rUncollectWord\x12\x14.common.v1.IDRequest\x1a\x16.google.protobuf.Empty\"\x00\x12B\n" +
	"\x0eGetLearnedWord\x12\x14.common.v1.IDRequest\x1a\x18.learning.v1.LearnedWord\"\x00\x12a\n" +
	"\x10ListLearnedWords\x12$.learning.v1.ListLearnedWordsRequest\x1a%.learning.v1.ListLearnedWordsResponse\"\x00\x12N\n" +
	"\rUpdateMastery\x12!.learning.v1.UpdateMasteryRequest\x1a\x18.learning.v1.LearnedWord\"\x00B\xae\x01\n" +
	"\x0fcom.learning.v1B\x14LearningServiceProtoP\x01Z8github.com/eslsoft/vocnet/pkg/api/learning/v1;learningv1\xa2\x02\x03LXX\xaa\x02\vLearning.V1\xca\x02\vLearning\\V1\xe2\x02\x17Learning\\V1\\GPBMetadata\xea\x02\fLearning::V1b\x06proto3"

var (
	file_learning_v1_learning_service_proto_rawDescOnce sync.Once
	file_learning_v1_learning_service_proto_rawDescData []byte
)

func file_learning_v1_learning_service_proto_rawDescGZIP() []byte {
	file_learning_v1_learning_service_proto_rawDescOnce.Do(func() {
		file_learning_v1_learning_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_learning_v1_learning_service_proto_rawDesc), len(file_learning_v1_learning_service_proto_rawDesc)))
	})
	return file_learning_v1_learning_service_proto_rawDescData
}

var file_learning_v1_learning_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_learning_v1_learning_service_proto_goTypes = []any{
	(*CollectWordRequest)(nil),       // 0: learning.v1.CollectWordRequest
	(*UpdateMasteryRequest)(nil),     // 1: learning.v1.UpdateMasteryRequest
	(*ListLearnedWordsRequest)(nil),  // 2: learning.v1.ListLearnedWordsRequest
	(*ListLearnedWordsResponse)(nil), // 3: learning.v1.ListLearnedWordsResponse
	(*LearnedWordSpec)(nil),          // 4: learning.v1.LearnedWordSpec
	(*v1.PaginationRequest)(nil),     // 5: common.v1.PaginationRequest
	(*v1.PaginationResponse)(nil),    // 6: common.v1.PaginationResponse
	(*LearnedWord)(nil),              // 7: learning.v1.LearnedWord
	(*v1.IDRequest)(nil),             // 8: common.v1.IDRequest
	(*emptypb.Empty)(nil),            // 9: google.protobuf.Empty
}
var file_learning_v1_learning_service_proto_depIdxs = []int32{
	4, // 0: learning.v1.CollectWordRequest.spec:type_name -> learning.v1.LearnedWordSpec
	5, // 1: learning.v1.ListLearnedWordsRequest.pagination:type_name -> common.v1.PaginationRequest
	6, // 2: learning.v1.ListLearnedWordsResponse.pagination:type_name -> common.v1.PaginationResponse
	7, // 3: learning.v1.ListLearnedWordsResponse.words:type_name -> learning.v1.LearnedWord
	0, // 4: learning.v1.LearningService.CollectWord:input_type -> learning.v1.CollectWordRequest
	8, // 5: learning.v1.LearningService.UncollectWord:input_type -> common.v1.IDRequest
	8, // 6: learning.v1.LearningService.GetLearnedWord:input_type -> common.v1.IDRequest
	2, // 7: learning.v1.LearningService.ListLearnedWords:input_type -> learning.v1.ListLearnedWordsRequest
	1, // 8: learning.v1.LearningService.UpdateMastery:input_type -> learning.v1.UpdateMasteryRequest
	7, // 9: learning.v1.LearningService.CollectWord:output_type -> learning.v1.LearnedWord
	9, // 10: learning.v1.LearningService.UncollectWord:output_type -> google.protobuf.Empty
	7, // 11: learning.v1.LearningService.GetLearnedWord:output_type -> learning.v1.LearnedWord
	3, // 12: learning.v1.LearningService.ListLearnedWords:output_type -> learning.v1.ListLearnedWordsResponse
	7, // 13: learning.v1.LearningService.UpdateMastery:output_type -> learning.v1.LearnedWord
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_learning_v1_learning_service_proto_init() }
func file_learning_v1_learning_service_proto_init() {
	if File_learning_v1_learning_service_proto != nil {
		return
	}
	file_learning_v1_learning_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_learning_v1_learning_service_proto_rawDesc), len(file_learning_v1_learning_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_learning_v1_learning_service_proto_goTypes,
		DependencyIndexes: file_learning_v1_learning_service_proto_depIdxs,
		MessageInfos:      file_learning_v1_learning_service_proto_msgTypes,
	}.Build()
	File_learning_v1_learning_service_proto = out.File
	file_learning_v1_learning_service_proto_goTypes = nil
	file_learning_v1_learning_service_proto_depIdxs = nil
}
