// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: learning/v1/learning.proto

package learningv1

import (
	v1 "github.com/eslsoft/vocnet/pkg/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MasteryLevel represents the user's current mastery state for a word.
// It combines the coarse stage (unknown / learning / known) with
// whether the word is known passively or actively.
type MasteryLevel int32

const (
	MasteryLevel_MASTERY_LEVEL_UNSPECIFIED MasteryLevel = 0
	MasteryLevel_MASTERY_LEVEL_UNKNOWN     MasteryLevel = 1 // Word is effectively unknown to the user.
	MasteryLevel_MASTERY_LEVEL_LEARNING    MasteryLevel = 2 // Word is in the process of being learned.
	MasteryLevel_MASTERY_LEVEL_KNOWN       MasteryLevel = 3 // User can reliably understand the word (reading/listening).
	MasteryLevel_MASTERY_LEVEL_MASTERED    MasteryLevel = 4 // User can both understand and actively use the word.
)

// Enum value maps for MasteryLevel.
var (
	MasteryLevel_name = map[int32]string{
		0: "MASTERY_LEVEL_UNSPECIFIED",
		1: "MASTERY_LEVEL_UNKNOWN",
		2: "MASTERY_LEVEL_LEARNING",
		3: "MASTERY_LEVEL_KNOWN",
		4: "MASTERY_LEVEL_MASTERED",
	}
	MasteryLevel_value = map[string]int32{
		"MASTERY_LEVEL_UNSPECIFIED": 0,
		"MASTERY_LEVEL_UNKNOWN":     1,
		"MASTERY_LEVEL_LEARNING":    2,
		"MASTERY_LEVEL_KNOWN":       3,
		"MASTERY_LEVEL_MASTERED":    4,
	}
)

func (x MasteryLevel) Enum() *MasteryLevel {
	p := new(MasteryLevel)
	*p = x
	return p
}

func (x MasteryLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MasteryLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_learning_v1_learning_proto_enumTypes[0].Descriptor()
}

func (MasteryLevel) Type() protoreflect.EnumType {
	return &file_learning_v1_learning_proto_enumTypes[0]
}

func (x MasteryLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MasteryLevel.Descriptor instead.
func (MasteryLevel) EnumDescriptor() ([]byte, []int) {
	return file_learning_v1_learning_proto_rawDescGZIP(), []int{0}
}

// LearnedWord captures a user's personalised vocabulary entry.
// This represents a user's learning record for a word (word-level, not lexeme-level).
type LearnedWord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Spec          *LearnedWordSpec       `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *LearnedWordStatus     `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LearnedWord) Reset() {
	*x = LearnedWord{}
	mi := &file_learning_v1_learning_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LearnedWord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearnedWord) ProtoMessage() {}

func (x *LearnedWord) ProtoReflect() protoreflect.Message {
	mi := &file_learning_v1_learning_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearnedWord.ProtoReflect.Descriptor instead.
func (*LearnedWord) Descriptor() ([]byte, []int) {
	return file_learning_v1_learning_proto_rawDescGZIP(), []int{0}
}

func (x *LearnedWord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LearnedWord) GetSpec() *LearnedWordSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *LearnedWord) GetStatus() *LearnedWordStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// LearnedWordSpec stores user-authored metadata.
type LearnedWordSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      v1.Language            `protobuf:"varint,1,opt,name=language,proto3,enum=common.v1.Language" json:"language,omitempty"`     // Language of the term
	Term          string                 `protobuf:"bytes,2,opt,name=term,proto3" json:"term,omitempty"`                                      // The actual word term (lemma for regular forms, or itself for irregular)
	MasteryLevel  int32                  `protobuf:"varint,3,opt,name=mastery_level,json=masteryLevel,proto3" json:"mastery_level,omitempty"` // user-assigned mastery level (0-5)
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Notes         []string               `protobuf:"bytes,6,rep,name=notes,proto3" json:"notes,omitempty"`
	Contexts      []*LearnedWordContext  `protobuf:"bytes,10,rep,name=contexts,proto3" json:"contexts,omitempty"` // Context sentences where user encountered this word
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LearnedWordSpec) Reset() {
	*x = LearnedWordSpec{}
	mi := &file_learning_v1_learning_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LearnedWordSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearnedWordSpec) ProtoMessage() {}

func (x *LearnedWordSpec) ProtoReflect() protoreflect.Message {
	mi := &file_learning_v1_learning_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearnedWordSpec.ProtoReflect.Descriptor instead.
func (*LearnedWordSpec) Descriptor() ([]byte, []int) {
	return file_learning_v1_learning_proto_rawDescGZIP(), []int{1}
}

func (x *LearnedWordSpec) GetLanguage() v1.Language {
	if x != nil {
		return x.Language
	}
	return v1.Language(0)
}

func (x *LearnedWordSpec) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *LearnedWordSpec) GetMasteryLevel() int32 {
	if x != nil {
		return x.MasteryLevel
	}
	return 0
}

func (x *LearnedWordSpec) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *LearnedWordSpec) GetNotes() []string {
	if x != nil {
		return x.Notes
	}
	return nil
}

func (x *LearnedWordSpec) GetContexts() []*LearnedWordContext {
	if x != nil {
		return x.Contexts
	}
	return nil
}

// LearnedWordStatus is maintained by the system to reflect learning progress.
type LearnedWordStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Mastery          *MasteryBreakdown      `protobuf:"bytes,1,opt,name=mastery,proto3" json:"mastery,omitempty"`
	ReviewTiming     *ReviewTiming          `protobuf:"bytes,2,opt,name=review_timing,json=reviewTiming,proto3" json:"review_timing,omitempty"`
	MatchedTerms     []string               `protobuf:"bytes,3,rep,name=matched_terms,json=matchedTerms,proto3" json:"matched_terms,omitempty"`             // All query terms that matched this word (for client-side highlighting)
	MatchedWordbooks []string               `protobuf:"bytes,4,rep,name=matched_wordbooks,json=matchedWordbooks,proto3" json:"matched_wordbooks,omitempty"` // Wordbooks that contain this word
	// MasteryLevel encodes both coarse stage (unknown/learning/known)
	// and whether the word is known passively or actively.
	Level         MasteryLevel           `protobuf:"varint,5,opt,name=level,proto3,enum=learning.v1.MasteryLevel" json:"level,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,10,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`           // username of the creator
	QueriedCount  int64                  `protobuf:"varint,11,opt,name=queried_count,json=queriedCount,proto3" json:"queried_count,omitempty"` // number of times user queried this word
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LearnedWordStatus) Reset() {
	*x = LearnedWordStatus{}
	mi := &file_learning_v1_learning_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LearnedWordStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearnedWordStatus) ProtoMessage() {}

func (x *LearnedWordStatus) ProtoReflect() protoreflect.Message {
	mi := &file_learning_v1_learning_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearnedWordStatus.ProtoReflect.Descriptor instead.
func (*LearnedWordStatus) Descriptor() ([]byte, []int) {
	return file_learning_v1_learning_proto_rawDescGZIP(), []int{2}
}

func (x *LearnedWordStatus) GetMastery() *MasteryBreakdown {
	if x != nil {
		return x.Mastery
	}
	return nil
}

func (x *LearnedWordStatus) GetReviewTiming() *ReviewTiming {
	if x != nil {
		return x.ReviewTiming
	}
	return nil
}

func (x *LearnedWordStatus) GetMatchedTerms() []string {
	if x != nil {
		return x.MatchedTerms
	}
	return nil
}

func (x *LearnedWordStatus) GetMatchedWordbooks() []string {
	if x != nil {
		return x.MatchedWordbooks
	}
	return nil
}

func (x *LearnedWordStatus) GetLevel() MasteryLevel {
	if x != nil {
		return x.Level
	}
	return MasteryLevel_MASTERY_LEVEL_UNSPECIFIED
}

func (x *LearnedWordStatus) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *LearnedWordStatus) GetQueriedCount() int64 {
	if x != nil {
		return x.QueriedCount
	}
	return 0
}

func (x *LearnedWordStatus) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *LearnedWordStatus) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Mastery breakdown for different skills
type MasteryBreakdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listening     int32                  `protobuf:"varint,1,opt,name=listening,proto3" json:"listening,omitempty"` // Listening mastery (0-5)
	Reading       int32                  `protobuf:"varint,2,opt,name=reading,proto3" json:"reading,omitempty"`     // Reading mastery (0-5)
	Spelling      int32                  `protobuf:"varint,3,opt,name=spelling,proto3" json:"spelling,omitempty"`   // Spelling mastery (0-5)
	Speaking      int32                  `protobuf:"varint,4,opt,name=speaking,proto3" json:"speaking,omitempty"`   // Pronunciation mastery (0-5)
	Overall       int32                  `protobuf:"varint,5,opt,name=overall,proto3" json:"overall,omitempty"`     // Overall mastery score (0-500, stored as *100), derived from receptive/productive scores
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasteryBreakdown) Reset() {
	*x = MasteryBreakdown{}
	mi := &file_learning_v1_learning_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasteryBreakdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasteryBreakdown) ProtoMessage() {}

func (x *MasteryBreakdown) ProtoReflect() protoreflect.Message {
	mi := &file_learning_v1_learning_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasteryBreakdown.ProtoReflect.Descriptor instead.
func (*MasteryBreakdown) Descriptor() ([]byte, []int) {
	return file_learning_v1_learning_proto_rawDescGZIP(), []int{3}
}

func (x *MasteryBreakdown) GetListening() int32 {
	if x != nil {
		return x.Listening
	}
	return 0
}

func (x *MasteryBreakdown) GetReading() int32 {
	if x != nil {
		return x.Reading
	}
	return 0
}

func (x *MasteryBreakdown) GetSpelling() int32 {
	if x != nil {
		return x.Spelling
	}
	return 0
}

func (x *MasteryBreakdown) GetSpeaking() int32 {
	if x != nil {
		return x.Speaking
	}
	return 0
}

func (x *MasteryBreakdown) GetOverall() int32 {
	if x != nil {
		return x.Overall
	}
	return 0
}

// Review timing information
type ReviewTiming struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastReviewAt  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=last_review_at,json=lastReviewAt,proto3" json:"last_review_at,omitempty"`
	NextReviewAt  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=next_review_at,json=nextReviewAt,proto3" json:"next_review_at,omitempty"`
	IntervalDays  int32                  `protobuf:"varint,3,opt,name=interval_days,json=intervalDays,proto3" json:"interval_days,omitempty"` // Current review interval
	FailCount     int32                  `protobuf:"varint,4,opt,name=fail_count,json=failCount,proto3" json:"fail_count,omitempty"`          // Consecutive failure count
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewTiming) Reset() {
	*x = ReviewTiming{}
	mi := &file_learning_v1_learning_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewTiming) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewTiming) ProtoMessage() {}

func (x *ReviewTiming) ProtoReflect() protoreflect.Message {
	mi := &file_learning_v1_learning_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewTiming.ProtoReflect.Descriptor instead.
func (*ReviewTiming) Descriptor() ([]byte, []int) {
	return file_learning_v1_learning_proto_rawDescGZIP(), []int{4}
}

func (x *ReviewTiming) GetLastReviewAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastReviewAt
	}
	return nil
}

func (x *ReviewTiming) GetNextReviewAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextReviewAt
	}
	return nil
}

func (x *ReviewTiming) GetIntervalDays() int32 {
	if x != nil {
		return x.IntervalDays
	}
	return 0
}

func (x *ReviewTiming) GetFailCount() int32 {
	if x != nil {
		return x.FailCount
	}
	return 0
}

// LearnedWordContext stores a sentence/context where user encountered the word
type LearnedWordContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sentence      string                 `protobuf:"bytes,1,opt,name=sentence,proto3" json:"sentence,omitempty"`                          // The sentence containing the word
	Source        v1.SourceType          `protobuf:"varint,2,opt,name=source,proto3,enum=common.v1.SourceType" json:"source,omitempty"`   // How this context was added (article, book, manual, etc.)
	SourceRef     string                 `protobuf:"bytes,3,opt,name=source_ref,json=sourceRef,proto3" json:"source_ref,omitempty"`       // Optional reference (article title, book name, URL, etc.)
	CollectedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"` // When this context was collected
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LearnedWordContext) Reset() {
	*x = LearnedWordContext{}
	mi := &file_learning_v1_learning_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LearnedWordContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearnedWordContext) ProtoMessage() {}

func (x *LearnedWordContext) ProtoReflect() protoreflect.Message {
	mi := &file_learning_v1_learning_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearnedWordContext.ProtoReflect.Descriptor instead.
func (*LearnedWordContext) Descriptor() ([]byte, []int) {
	return file_learning_v1_learning_proto_rawDescGZIP(), []int{5}
}

func (x *LearnedWordContext) GetSentence() string {
	if x != nil {
		return x.Sentence
	}
	return ""
}

func (x *LearnedWordContext) GetSource() v1.SourceType {
	if x != nil {
		return x.Source
	}
	return v1.SourceType(0)
}

func (x *LearnedWordContext) GetSourceRef() string {
	if x != nil {
		return x.SourceRef
	}
	return ""
}

func (x *LearnedWordContext) GetCollectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectedAt
	}
	return nil
}

var File_learning_v1_learning_proto protoreflect.FileDescriptor

const file_learning_v1_learning_proto_rawDesc = "" +
	"\n" +
	"\x1alearning/v1/learning.proto\x12\vlearning.v1\x1a\x15common/v1/types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x87\x01\n" +
	"\vLearnedWord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x120\n" +
	"\x04spec\x18\x03 \x01(\v2\x1c.learning.v1.LearnedWordSpecR\x04spec\x126\n" +
	"\x06status\x18\x04 \x01(\v2\x1e.learning.v1.LearnedWordStatusR\x06status\"\xe2\x01\n" +
	"\x0fLearnedWordSpec\x12/\n" +
	"\blanguage\x18\x01 \x01(\x0e2\x13.common.v1.LanguageR\blanguage\x12\x12\n" +
	"\x04term\x18\x02 \x01(\tR\x04term\x12#\n" +
	"\rmastery_level\x18\x03 \x01(\x05R\fmasteryLevel\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x14\n" +
	"\x05notes\x18\x06 \x03(\tR\x05notes\x12;\n" +
	"\bcontexts\x18\n" +
	" \x03(\v2\x1f.learning.v1.LearnedWordContextR\bcontexts\"\xc9\x03\n" +
	"\x11LearnedWordStatus\x127\n" +
	"\amastery\x18\x01 \x01(\v2\x1d.learning.v1.MasteryBreakdownR\amastery\x12>\n" +
	"\rreview_timing\x18\x02 \x01(\v2\x19.learning.v1.ReviewTimingR\freviewTiming\x12#\n" +
	"\rmatched_terms\x18\x03 \x03(\tR\fmatchedTerms\x12+\n" +
	"\x11matched_wordbooks\x18\x04 \x03(\tR\x10matchedWordbooks\x12/\n" +
	"\x05level\x18\x05 \x01(\x0e2\x19.learning.v1.MasteryLevelR\x05level\x12\x1d\n" +
	"\n" +
	"created_by\x18\n" +
	" \x01(\tR\tcreatedBy\x12#\n" +
	"\rqueried_count\x18\v \x01(\x03R\fqueriedCount\x129\n" +
	"\n" +
	"created_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9c\x01\n" +
	"\x10MasteryBreakdown\x12\x1c\n" +
	"\tlistening\x18\x01 \x01(\x05R\tlistening\x12\x18\n" +
	"\areading\x18\x02 \x01(\x05R\areading\x12\x1a\n" +
	"\bspelling\x18\x03 \x01(\x05R\bspelling\x12\x1a\n" +
	"\bspeaking\x18\x04 \x01(\x05R\bspeaking\x12\x18\n" +
	"\aoverall\x18\x05 \x01(\x05R\aoverall\"\xd6\x01\n" +
	"\fReviewTiming\x12@\n" +
	"\x0elast_review_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\flastReviewAt\x12@\n" +
	"\x0enext_review_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fnextReviewAt\x12#\n" +
	"\rinterval_days\x18\x03 \x01(\x05R\fintervalDays\x12\x1d\n" +
	"\n" +
	"fail_count\x18\x04 \x01(\x05R\tfailCount\"\xbd\x01\n" +
	"\x12LearnedWordContext\x12\x1a\n" +
	"\bsentence\x18\x01 \x01(\tR\bsentence\x12-\n" +
	"\x06source\x18\x02 \x01(\x0e2\x15.common.v1.SourceTypeR\x06source\x12\x1d\n" +
	"\n" +
	"source_ref\x18\x03 \x01(\tR\tsourceRef\x12=\n" +
	"\fcollected_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcollectedAt*\x99\x01\n" +
	"\fMasteryLevel\x12\x1d\n" +
	"\x19MASTERY_LEVEL_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15MASTERY_LEVEL_UNKNOWN\x10\x01\x12\x1a\n" +
	"\x16MASTERY_LEVEL_LEARNING\x10\x02\x12\x17\n" +
	"\x13MASTERY_LEVEL_KNOWN\x10\x03\x12\x1a\n" +
	"\x16MASTERY_LEVEL_MASTERED\x10\x04B\xa7\x01\n" +
	"\x0fcom.learning.v1B\rLearningProtoP\x01Z8github.com/eslsoft/vocnet/pkg/api/learning/v1;learningv1\xa2\x02\x03LXX\xaa\x02\vLearning.V1\xca\x02\vLearning\\V1\xe2\x02\x17Learning\\V1\\GPBMetadata\xea\x02\fLearning::V1b\x06proto3"

var (
	file_learning_v1_learning_proto_rawDescOnce sync.Once
	file_learning_v1_learning_proto_rawDescData []byte
)

func file_learning_v1_learning_proto_rawDescGZIP() []byte {
	file_learning_v1_learning_proto_rawDescOnce.Do(func() {
		file_learning_v1_learning_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_learning_v1_learning_proto_rawDesc), len(file_learning_v1_learning_proto_rawDesc)))
	})
	return file_learning_v1_learning_proto_rawDescData
}

var file_learning_v1_learning_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_learning_v1_learning_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_learning_v1_learning_proto_goTypes = []any{
	(MasteryLevel)(0),             // 0: learning.v1.MasteryLevel
	(*LearnedWord)(nil),           // 1: learning.v1.LearnedWord
	(*LearnedWordSpec)(nil),       // 2: learning.v1.LearnedWordSpec
	(*LearnedWordStatus)(nil),     // 3: learning.v1.LearnedWordStatus
	(*MasteryBreakdown)(nil),      // 4: learning.v1.MasteryBreakdown
	(*ReviewTiming)(nil),          // 5: learning.v1.ReviewTiming
	(*LearnedWordContext)(nil),    // 6: learning.v1.LearnedWordContext
	(v1.Language)(0),              // 7: common.v1.Language
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(v1.SourceType)(0),            // 9: common.v1.SourceType
}
var file_learning_v1_learning_proto_depIdxs = []int32{
	2,  // 0: learning.v1.LearnedWord.spec:type_name -> learning.v1.LearnedWordSpec
	3,  // 1: learning.v1.LearnedWord.status:type_name -> learning.v1.LearnedWordStatus
	7,  // 2: learning.v1.LearnedWordSpec.language:type_name -> common.v1.Language
	6,  // 3: learning.v1.LearnedWordSpec.contexts:type_name -> learning.v1.LearnedWordContext
	4,  // 4: learning.v1.LearnedWordStatus.mastery:type_name -> learning.v1.MasteryBreakdown
	5,  // 5: learning.v1.LearnedWordStatus.review_timing:type_name -> learning.v1.ReviewTiming
	0,  // 6: learning.v1.LearnedWordStatus.level:type_name -> learning.v1.MasteryLevel
	8,  // 7: learning.v1.LearnedWordStatus.created_at:type_name -> google.protobuf.Timestamp
	8,  // 8: learning.v1.LearnedWordStatus.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 9: learning.v1.ReviewTiming.last_review_at:type_name -> google.protobuf.Timestamp
	8,  // 10: learning.v1.ReviewTiming.next_review_at:type_name -> google.protobuf.Timestamp
	9,  // 11: learning.v1.LearnedWordContext.source:type_name -> common.v1.SourceType
	8,  // 12: learning.v1.LearnedWordContext.collected_at:type_name -> google.protobuf.Timestamp
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_learning_v1_learning_proto_init() }
func file_learning_v1_learning_proto_init() {
	if File_learning_v1_learning_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_learning_v1_learning_proto_rawDesc), len(file_learning_v1_learning_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_learning_v1_learning_proto_goTypes,
		DependencyIndexes: file_learning_v1_learning_proto_depIdxs,
		EnumInfos:         file_learning_v1_learning_proto_enumTypes,
		MessageInfos:      file_learning_v1_learning_proto_msgTypes,
	}.Build()
	File_learning_v1_learning_proto = out.File
	file_learning_v1_learning_proto_goTypes = nil
	file_learning_v1_learning_proto_depIdxs = nil
}
