syntax = "proto3";

package learning.v1;

import "google/protobuf/timestamp.proto";
import "wordbook/v1/wordbook.proto";

// ReviewPlan represents a user's plan for reviewing words.
message ReviewPlan {
  int64 id = 1;
  string name = 2;
  string description = 3;

  string created_by = 20; // username of the creator
  google.protobuf.Timestamp created_at = 21;
  google.protobuf.Timestamp updated_at = 22;
}

message ReviewPlanStatus {
  int32 total_words = 1;
  int32 reviewed_words = 2;
  int32 pending_words = 3;

  repeated wordbook.v1.Wordbook wordbooks = 10;
  google.protobuf.Timestamp last_reviewed_at = 11;
}
