syntax = "proto3";

package learning.v1;

import "google/protobuf/timestamp.proto";
import "wordbook/v1/wordbook.proto";

// ReviewPlan represents a user's plan for reviewing words.
message ReviewPlan {
  int64 id = 1;
  string name = 2;
  string description = 3;

  ReviewPlanStatus status = 10;

  string created_by = 20; // username of the creator
  google.protobuf.Timestamp created_at = 21;
  google.protobuf.Timestamp updated_at = 22;
}

message ReviewPlanStatus {
  int32 pending_words = 1; // Words pending review

  int32 mastered_words = 2; // Words with overall mastery >= 4
  int32 learning_words = 3; // Words with 1 <= overall mastery < 4
  int32 unknown_words = 4; // Words with overall mastery < 1

  repeated wordbook.v1.Wordbook wordbooks = 10;
  // google.protobuf.Timestamp last_reviewed_at = 11;
}
