package usecase

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/eslsoft/vocnet/internal/entity"
	"github.com/eslsoft/vocnet/internal/repository"
)

//go:generate mockgen -source=lexeme_usecase.go -destination=../mocks/mock_lexeme_usecase.go -package=mocks

// LexemeUsecase exposes high-level dictionary operations backed by lexemes.
type LexemeUsecase interface {
	Create(ctx context.Context, lexeme *entity.Lexeme) (*entity.Lexeme, error)
	Update(ctx context.Context, lexeme *entity.Lexeme) (*entity.Lexeme, error)
	Get(ctx context.Context, lexemeID int64) (*entity.Lexeme, error)
	Lookup(ctx context.Context, surface string, language entity.Language) (*entity.Lexeme, error)
	List(ctx context.Context, filter *repository.ListLexemeQuery) ([]*entity.Lexeme, int64, error)
	Delete(ctx context.Context, lexemeID int64) error
}

type lexemeUsecase struct {
	repo   repository.LexemeRepository
	lemmas repository.LemmaRepository
}

// NewLexemeUsecase wires the repository with domain rules.
func NewLexemeUsecase(repo repository.LexemeRepository, lemmas repository.LemmaRepository) LexemeUsecase {
	return &lexemeUsecase{repo: repo, lemmas: lemmas}
}

func (u *lexemeUsecase) Create(ctx context.Context, lexeme *entity.Lexeme) (*entity.Lexeme, error) {
	norm, err := normalizeLexemePayload(lexeme)
	if err != nil {
		return nil, err
	}
	// Normalize forms with lexeme ID after creation
	norm.Forms = normalizeLexemeForms(norm.ID, norm.Forms)
	created, err := u.repo.Create(ctx, norm)
	if err != nil {
		return nil, err
	}
	// Update forms with the created lexeme's ID
	created.Forms = normalizeLexemeForms(created.ID, created.Forms)
	if created.LemmaID > 0 {
		_ = u.refreshLemma(ctx, created.LemmaID) // best-effort
	}
	return created, nil
}

func (u *lexemeUsecase) Update(ctx context.Context, lexeme *entity.Lexeme) (*entity.Lexeme, error) {
	norm, err := normalizeLexemePayload(lexeme)
	if err != nil {
		return nil, err
	}
	updated, err := u.repo.Update(ctx, norm)
	if err != nil {
		return nil, err
	}
	if updated.LemmaID > 0 {
		_ = u.refreshLemma(ctx, updated.LemmaID)
	}
	return updated, nil
}

func (u *lexemeUsecase) Get(ctx context.Context, lexemeID int64) (*entity.Lexeme, error) {
	if lexemeID == 0 {
		return nil, entity.ErrInvalidLexemeID
	}
	return u.repo.GetByID(ctx, lexemeID)
}

func (u *lexemeUsecase) Lookup(ctx context.Context, surface string, language entity.Language) (*entity.Lexeme, error) {
	surface = strings.TrimSpace(surface)
	if surface == "" {
		return nil, entity.ErrInvalidLexemeText
	}
	return u.repo.Lookup(ctx, surface, language)
}

func (u *lexemeUsecase) List(ctx context.Context, filter *repository.ListLexemeQuery) ([]*entity.Lexeme, int64, error) {
	return u.repo.List(ctx, filter)
}

func (u *lexemeUsecase) Delete(ctx context.Context, lexemeID int64) error {
	if lexemeID == 0 {
		return entity.ErrInvalidLexemeID
	}
	lex, err := u.repo.GetByID(ctx, lexemeID)
	if err != nil {
		return err
	}
	if err := u.repo.Delete(ctx, lexemeID); err != nil {
		return err
	}
	if lex.LemmaID > 0 {
		_ = u.refreshLemma(ctx, lex.LemmaID)
	}
	return nil
}

func normalizeLexemePayload(in *entity.Lexeme) (*entity.Lexeme, error) {
	if in == nil {
		return nil, errors.New("lexeme payload required")
	}
	out := *in
	// ID will be auto-generated by database as int64
	if out.Language == entity.LanguageUnspecified {
		out.Language = entity.LanguageEnglish
	}
	if out.EntryType == entity.LexemeEntryTypeUnspecified {
		out.EntryType = entity.LexemeEntryTypeWord
	}
	out.Lemma = strings.TrimSpace(out.Lemma)

	// ExternalID must be provided (from Wikidata)
	if out.ExternalID == "" {
		return nil, fmt.Errorf("lexeme external_id is required")
	}

	// Note: LemmaID will be set later when associating with Lemma
	// Forms will be handled separately after lexeme is created
	out.Senses = normalizeLexemeSenses(out.ExternalID, out.Senses)
	out.Relations = normalizeLexemeRelations(out.ExternalID, out.Relations)

	return &out, nil
}

func normalizeLexemeForms(lexemeID int64, forms []entity.LexemeForm) []entity.LexemeForm {
	if len(forms) == 0 {
		return []entity.LexemeForm{}
	}
	out := make([]entity.LexemeForm, 0, len(forms))
	for _, form := range forms {
		out = append(out, entity.LexemeForm{
			ID:          form.ID,
			LexemeID:    lexemeID,
			Text:        strings.TrimSpace(form.Text),
			FormType:    defaultFormType(form.FormType),
			IsIrregular: form.IsIrregular,
		})
	}
	return out
}

func normalizeLexemeSenses(lexemeLID string, senses []entity.LexemeSense) []entity.LexemeSense {
	if len(senses) == 0 {
		return []entity.LexemeSense{}
	}
	out := make([]entity.LexemeSense, 0, len(senses))
	for _, sense := range senses {
		out = append(out, entity.LexemeSense{
			Language: sense.Language,
			Gloss:    strings.TrimSpace(sense.Gloss),
			Examples: append([]entity.SenseExample{}, sense.Examples...),
		})
	}
	return out
}

func normalizeLexemeRelations(lexemeLID string, relations []entity.LexemeRelation) []entity.LexemeRelation {
	if len(relations) == 0 {
		return []entity.LexemeRelation{}
	}
	out := make([]entity.LexemeRelation, 0, len(relations))
	for _, rel := range relations {
		out = append(out, entity.LexemeRelation{
			LexemeID:       lexemeLID,
			TargetLexemeID: strings.TrimSpace(rel.TargetLexemeID),
			RelationType:   rel.RelationType,
		})
	}
	return out
}

func defaultFormType(ft entity.LexemeFormType) entity.LexemeFormType {
	if ft == entity.LexemeFormTypeUnspecified {
		return entity.LexemeFormTypeLemma
	}
	return ft
}

func (u *lexemeUsecase) refreshLemma(ctx context.Context, lemmaID int64) error {
	if u.lemmas == nil || lemmaID == 0 {
		return nil
	}
	lexemes, err := u.repo.ListByLemmaID(ctx, lemmaID)
	if err != nil {
		return err
	}
	if len(lexemes) == 0 {
		// If no lexemes, get lemma and delete by WID
		lemma, err := u.lemmas.GetByID(ctx, lemmaID)
		if err != nil {
			return err
		}
		return u.lemmas.DeleteByWID(ctx, lemma.WID)
	}
	lemma := &entity.Lemma{
		ID:           lemmaID,
		WID:          makeWID(lexemes[0].Language, lexemes[0].Lemma),
		Text:         lexemes[0].Lemma,
		Language:     lexemes[0].Language,
		Completeness: computeWordCompleteness(lexemes),
		// TODO: Aggregate Categories from lexemes if needed
	}
	_, err = u.lemmas.Upsert(ctx, lemma)
	return err
}

func computeWordCompleteness(lexemes []*entity.Lexeme) int32 {
	if len(lexemes) == 0 {
		return 0
	}
	var score int32
	hasForms := false
	hasSenses := false
	for _, lex := range lexemes {
		if len(lex.Forms) > 0 {
			hasForms = true
		}
		if len(lex.Senses) > 0 {
			hasSenses = true
		}
	}
	if hasForms {
		score += 40
	}
	if hasSenses {
		score += 60
	}
	if score > 100 {
		return 100
	}
	return score
}
