package usecase

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/eslsoft/vocnet/internal/entity"
	"github.com/eslsoft/vocnet/internal/repository"
)

//go:generate mockgen -source=lexeme_usecase.go -destination=../mocks/mock_lexeme_usecase.go -package=mocks

// LexemeUsecase exposes high-level dictionary operations backed by lexemes.
type LexemeUsecase interface {
	Create(ctx context.Context, lexeme *entity.Lexeme) (*entity.Lexeme, error)
	Update(ctx context.Context, lexeme *entity.Lexeme) (*entity.Lexeme, error)
	Get(ctx context.Context, lexemeID int64) (*entity.Lexeme, error)
	Lookup(ctx context.Context, surface string, language entity.Language) (*entity.Lexeme, error)
	List(ctx context.Context, filter *repository.ListLexemeQuery) ([]*entity.Lexeme, int64, error)
	Delete(ctx context.Context, lexemeID int64) error
}

type lexemeUsecase struct {
	repo repository.LexemeRepository
}

// NewLexemeUsecase wires the repository with domain rules.
func NewLexemeUsecase(repo repository.LexemeRepository) LexemeUsecase {
	return &lexemeUsecase{repo: repo}
}

func (u *lexemeUsecase) Create(ctx context.Context, lexeme *entity.Lexeme) (*entity.Lexeme, error) {
	norm, err := normalizeLexemePayload(lexeme)
	if err != nil {
		return nil, err
	}
	created, err := u.repo.Create(ctx, norm)
	if err != nil {
		return nil, err
	}
	// Note: Forms normalization removed as Forms field no longer exists
	return created, nil
}

func (u *lexemeUsecase) Update(ctx context.Context, lexeme *entity.Lexeme) (*entity.Lexeme, error) {
	norm, err := normalizeLexemePayload(lexeme)
	if err != nil {
		return nil, err
	}
	updated, err := u.repo.Update(ctx, norm)
	if err != nil {
		return nil, err
	}
	return updated, nil
}

func (u *lexemeUsecase) Get(ctx context.Context, lexemeID int64) (*entity.Lexeme, error) {
	if lexemeID == 0 {
		return nil, entity.ErrInvalidLexemeID
	}
	return u.repo.GetByID(ctx, lexemeID)
}

func (u *lexemeUsecase) Lookup(ctx context.Context, surface string, language entity.Language) (*entity.Lexeme, error) {
	surface = strings.TrimSpace(surface)
	if surface == "" {
		return nil, entity.ErrInvalidLexemeText
	}
	return u.repo.Lookup(ctx, surface, language)
}

func (u *lexemeUsecase) List(ctx context.Context, filter *repository.ListLexemeQuery) ([]*entity.Lexeme, int64, error) {
	return u.repo.List(ctx, filter)
}

func (u *lexemeUsecase) Delete(ctx context.Context, lexemeID int64) error {
	if lexemeID == 0 {
		return entity.ErrInvalidLexemeID
	}
	if err := u.repo.Delete(ctx, lexemeID); err != nil {
		return err
	}
	return nil
}

func normalizeLexemePayload(in *entity.Lexeme) (*entity.Lexeme, error) {
	if in == nil {
		return nil, errors.New("lexeme payload required")
	}
	out := *in
	// ID will be auto-generated by database as int64
	if out.Language == entity.LanguageUnspecified {
		out.Language = entity.LanguageEnglish
	}
	if out.EntryType == entity.LexemeEntryTypeUnspecified {
		out.EntryType = entity.LexemeEntryTypeWord
	}
	// Note: LemmaText field removed from entity.Lexeme
	out.Level = strings.TrimSpace(out.Level)
	out.SenseGloss = strings.TrimSpace(out.SenseGloss)
	out.Frequencies = append([]entity.Frequency{}, out.Frequencies...)
	out.Categories = append([]string{}, out.Categories...)

	// ExternalID must be provided (from Wikidata)
	if out.ExternalID == "" {
		return nil, fmt.Errorf("lexeme external_id is required")
	}

	// Forms will be handled separately after lexeme is created
	out.Senses = normalizeLexemeSenses(out.ExternalID, out.Senses)
	out.Relations = normalizeLexemeRelations(out.ExternalID, out.Relations)

	return &out, nil
}

// normalizeLexemeForms removed as Forms field no longer exists in entity.Lexeme

func normalizeLexemeSenses(lexemeLID string, senses []entity.LexemeSense) []entity.LexemeSense {
	if len(senses) == 0 {
		return []entity.LexemeSense{}
	}
	out := make([]entity.LexemeSense, 0, len(senses))
	for _, sense := range senses {
		out = append(out, entity.LexemeSense{
			Language: sense.Language,
			Gloss:    strings.TrimSpace(sense.Gloss),
			Examples: append([]entity.SenseExample{}, sense.Examples...),
		})
	}
	return out
}

func normalizeLexemeRelations(lexemeLID string, relations []entity.LexemeRelation) []entity.LexemeRelation {
	if len(relations) == 0 {
		return []entity.LexemeRelation{}
	}
	out := make([]entity.LexemeRelation, 0, len(relations))
	for _, rel := range relations {
		out = append(out, entity.LexemeRelation{
			LexemeID:       lexemeLID,
			TargetLexemeID: strings.TrimSpace(rel.TargetLexemeID),
			RelationType:   rel.RelationType,
		})
	}
	return out
}
