// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pipeline/v1/lemma_service.proto

package pipelinev1

import (
	v1 "github.com/eslsoft/vocnet/pkg/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LemmaLevel int32

const (
	LemmaLevel_LEMMA_LEVEL_UNSPECIFIED LemmaLevel = 0
	LemmaLevel_LEMMA_LEVEL_A1          LemmaLevel = 1
	LemmaLevel_LEMMA_LEVEL_A2          LemmaLevel = 2
	LemmaLevel_LEMMA_LEVEL_B1          LemmaLevel = 3
	LemmaLevel_LEMMA_LEVEL_B2          LemmaLevel = 4
	LemmaLevel_LEMMA_LEVEL_C1          LemmaLevel = 5
	LemmaLevel_LEMMA_LEVEL_C2          LemmaLevel = 6
	LemmaLevel_LEMMA_LEVEL_OTHER       LemmaLevel = 99
)

// Enum value maps for LemmaLevel.
var (
	LemmaLevel_name = map[int32]string{
		0:  "LEMMA_LEVEL_UNSPECIFIED",
		1:  "LEMMA_LEVEL_A1",
		2:  "LEMMA_LEVEL_A2",
		3:  "LEMMA_LEVEL_B1",
		4:  "LEMMA_LEVEL_B2",
		5:  "LEMMA_LEVEL_C1",
		6:  "LEMMA_LEVEL_C2",
		99: "LEMMA_LEVEL_OTHER",
	}
	LemmaLevel_value = map[string]int32{
		"LEMMA_LEVEL_UNSPECIFIED": 0,
		"LEMMA_LEVEL_A1":          1,
		"LEMMA_LEVEL_A2":          2,
		"LEMMA_LEVEL_B1":          3,
		"LEMMA_LEVEL_B2":          4,
		"LEMMA_LEVEL_C1":          5,
		"LEMMA_LEVEL_C2":          6,
		"LEMMA_LEVEL_OTHER":       99,
	}
)

func (x LemmaLevel) Enum() *LemmaLevel {
	p := new(LemmaLevel)
	*p = x
	return p
}

func (x LemmaLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LemmaLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_pipeline_v1_lemma_service_proto_enumTypes[0].Descriptor()
}

func (LemmaLevel) Type() protoreflect.EnumType {
	return &file_pipeline_v1_lemma_service_proto_enumTypes[0]
}

func (x LemmaLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LemmaLevel.Descriptor instead.
func (LemmaLevel) EnumDescriptor() ([]byte, []int) {
	return file_pipeline_v1_lemma_service_proto_rawDescGZIP(), []int{0}
}

type ListLemmasRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Pagination *v1.PaginationRequest  `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// Optional fuzzy search on lemma surface / normalized form.
	Keyword       string `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLemmasRequest) Reset() {
	*x = ListLemmasRequest{}
	mi := &file_pipeline_v1_lemma_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLemmasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLemmasRequest) ProtoMessage() {}

func (x *ListLemmasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_v1_lemma_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLemmasRequest.ProtoReflect.Descriptor instead.
func (*ListLemmasRequest) Descriptor() ([]byte, []int) {
	return file_pipeline_v1_lemma_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListLemmasRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListLemmasRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type LemmaItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Surface       string                 `protobuf:"bytes,2,opt,name=surface,proto3" json:"surface,omitempty"`
	Normalized    string                 `protobuf:"bytes,3,opt,name=normalized,proto3" json:"normalized,omitempty"`
	Level         LemmaLevel             `protobuf:"varint,4,opt,name=level,proto3,enum=pipeline.v1.LemmaLevel" json:"level,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LemmaItem) Reset() {
	*x = LemmaItem{}
	mi := &file_pipeline_v1_lemma_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LemmaItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LemmaItem) ProtoMessage() {}

func (x *LemmaItem) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_v1_lemma_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LemmaItem.ProtoReflect.Descriptor instead.
func (*LemmaItem) Descriptor() ([]byte, []int) {
	return file_pipeline_v1_lemma_service_proto_rawDescGZIP(), []int{1}
}

func (x *LemmaItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LemmaItem) GetSurface() string {
	if x != nil {
		return x.Surface
	}
	return ""
}

func (x *LemmaItem) GetNormalized() string {
	if x != nil {
		return x.Normalized
	}
	return ""
}

func (x *LemmaItem) GetLevel() LemmaLevel {
	if x != nil {
		return x.Level
	}
	return LemmaLevel_LEMMA_LEVEL_UNSPECIFIED
}

func (x *LemmaItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *LemmaItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListLemmasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lemmas        []*LemmaItem           `protobuf:"bytes,1,rep,name=lemmas,proto3" json:"lemmas,omitempty"`
	Pagination    *v1.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLemmasResponse) Reset() {
	*x = ListLemmasResponse{}
	mi := &file_pipeline_v1_lemma_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLemmasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLemmasResponse) ProtoMessage() {}

func (x *ListLemmasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_v1_lemma_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLemmasResponse.ProtoReflect.Descriptor instead.
func (*ListLemmasResponse) Descriptor() ([]byte, []int) {
	return file_pipeline_v1_lemma_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListLemmasResponse) GetLemmas() []*LemmaItem {
	if x != nil {
		return x.Lemmas
	}
	return nil
}

func (x *ListLemmasResponse) GetPagination() *v1.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_pipeline_v1_lemma_service_proto protoreflect.FileDescriptor

const file_pipeline_v1_lemma_service_proto_rawDesc = "" +
	"\n" +
	"\x1fpipeline/v1/lemma_service.proto\x12\vpipeline.v1\x1a\x15common/v1/types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1apipeline/v1/pipeline.proto\"k\n" +
	"\x11ListLemmasRequest\x12<\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1c.common.v1.PaginationRequestR\n" +
	"pagination\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\"\xfa\x01\n" +
	"\tLemmaItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\asurface\x18\x02 \x01(\tR\asurface\x12\x1e\n" +
	"\n" +
	"normalized\x18\x03 \x01(\tR\n" +
	"normalized\x12-\n" +
	"\x05level\x18\x04 \x01(\x0e2\x17.pipeline.v1.LemmaLevelR\x05level\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x83\x01\n" +
	"\x12ListLemmasResponse\x12.\n" +
	"\x06lemmas\x18\x01 \x03(\v2\x16.pipeline.v1.LemmaItemR\x06lemmas\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.common.v1.PaginationResponseR\n" +
	"pagination*\xb8\x01\n" +
	"\n" +
	"LemmaLevel\x12\x1b\n" +
	"\x17LEMMA_LEVEL_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eLEMMA_LEVEL_A1\x10\x01\x12\x12\n" +
	"\x0eLEMMA_LEVEL_A2\x10\x02\x12\x12\n" +
	"\x0eLEMMA_LEVEL_B1\x10\x03\x12\x12\n" +
	"\x0eLEMMA_LEVEL_B2\x10\x04\x12\x12\n" +
	"\x0eLEMMA_LEVEL_C1\x10\x05\x12\x12\n" +
	"\x0eLEMMA_LEVEL_C2\x10\x06\x12\x15\n" +
	"\x11LEMMA_LEVEL_OTHER\x10c2]\n" +
	"\fLemmaService\x12M\n" +
	"\n" +
	"ListLemmas\x12\x1e.pipeline.v1.ListLemmasRequest\x1a\x1f.pipeline.v1.ListLemmasResponseB\xab\x01\n" +
	"\x0fcom.pipeline.v1B\x11LemmaServiceProtoP\x01Z8github.com/eslsoft/vocnet/pkg/api/pipeline/v1;pipelinev1\xa2\x02\x03PXX\xaa\x02\vPipeline.V1\xca\x02\vPipeline\\V1\xe2\x02\x17Pipeline\\V1\\GPBMetadata\xea\x02\fPipeline::V1b\x06proto3"

var (
	file_pipeline_v1_lemma_service_proto_rawDescOnce sync.Once
	file_pipeline_v1_lemma_service_proto_rawDescData []byte
)

func file_pipeline_v1_lemma_service_proto_rawDescGZIP() []byte {
	file_pipeline_v1_lemma_service_proto_rawDescOnce.Do(func() {
		file_pipeline_v1_lemma_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pipeline_v1_lemma_service_proto_rawDesc), len(file_pipeline_v1_lemma_service_proto_rawDesc)))
	})
	return file_pipeline_v1_lemma_service_proto_rawDescData
}

var file_pipeline_v1_lemma_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pipeline_v1_lemma_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pipeline_v1_lemma_service_proto_goTypes = []any{
	(LemmaLevel)(0),               // 0: pipeline.v1.LemmaLevel
	(*ListLemmasRequest)(nil),     // 1: pipeline.v1.ListLemmasRequest
	(*LemmaItem)(nil),             // 2: pipeline.v1.LemmaItem
	(*ListLemmasResponse)(nil),    // 3: pipeline.v1.ListLemmasResponse
	(*v1.PaginationRequest)(nil),  // 4: common.v1.PaginationRequest
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*v1.PaginationResponse)(nil), // 6: common.v1.PaginationResponse
}
var file_pipeline_v1_lemma_service_proto_depIdxs = []int32{
	4, // 0: pipeline.v1.ListLemmasRequest.pagination:type_name -> common.v1.PaginationRequest
	0, // 1: pipeline.v1.LemmaItem.level:type_name -> pipeline.v1.LemmaLevel
	5, // 2: pipeline.v1.LemmaItem.created_at:type_name -> google.protobuf.Timestamp
	5, // 3: pipeline.v1.LemmaItem.updated_at:type_name -> google.protobuf.Timestamp
	2, // 4: pipeline.v1.ListLemmasResponse.lemmas:type_name -> pipeline.v1.LemmaItem
	6, // 5: pipeline.v1.ListLemmasResponse.pagination:type_name -> common.v1.PaginationResponse
	1, // 6: pipeline.v1.LemmaService.ListLemmas:input_type -> pipeline.v1.ListLemmasRequest
	3, // 7: pipeline.v1.LemmaService.ListLemmas:output_type -> pipeline.v1.ListLemmasResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pipeline_v1_lemma_service_proto_init() }
func file_pipeline_v1_lemma_service_proto_init() {
	if File_pipeline_v1_lemma_service_proto != nil {
		return
	}
	file_pipeline_v1_pipeline_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pipeline_v1_lemma_service_proto_rawDesc), len(file_pipeline_v1_lemma_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pipeline_v1_lemma_service_proto_goTypes,
		DependencyIndexes: file_pipeline_v1_lemma_service_proto_depIdxs,
		EnumInfos:         file_pipeline_v1_lemma_service_proto_enumTypes,
		MessageInfos:      file_pipeline_v1_lemma_service_proto_msgTypes,
	}.Build()
	File_pipeline_v1_lemma_service_proto = out.File
	file_pipeline_v1_lemma_service_proto_goTypes = nil
	file_pipeline_v1_lemma_service_proto_depIdxs = nil
}
