// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pipeline/v1/lemma_service.proto

package pipelinev1

import (
	v1 "github.com/eslsoft/vocnet/pkg/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LemmaLevel int32

const (
	LemmaLevel_LEMMA_LEVEL_UNSPECIFIED LemmaLevel = 0
	LemmaLevel_LEMMA_LEVEL_A1          LemmaLevel = 1
	LemmaLevel_LEMMA_LEVEL_A2          LemmaLevel = 2
	LemmaLevel_LEMMA_LEVEL_B1          LemmaLevel = 3
	LemmaLevel_LEMMA_LEVEL_B2          LemmaLevel = 4
	LemmaLevel_LEMMA_LEVEL_C1          LemmaLevel = 5
	LemmaLevel_LEMMA_LEVEL_C2          LemmaLevel = 6
)

// Enum value maps for LemmaLevel.
var (
	LemmaLevel_name = map[int32]string{
		0: "LEMMA_LEVEL_UNSPECIFIED",
		1: "LEMMA_LEVEL_A1",
		2: "LEMMA_LEVEL_A2",
		3: "LEMMA_LEVEL_B1",
		4: "LEMMA_LEVEL_B2",
		5: "LEMMA_LEVEL_C1",
		6: "LEMMA_LEVEL_C2",
	}
	LemmaLevel_value = map[string]int32{
		"LEMMA_LEVEL_UNSPECIFIED": 0,
		"LEMMA_LEVEL_A1":          1,
		"LEMMA_LEVEL_A2":          2,
		"LEMMA_LEVEL_B1":          3,
		"LEMMA_LEVEL_B2":          4,
		"LEMMA_LEVEL_C1":          5,
		"LEMMA_LEVEL_C2":          6,
	}
)

func (x LemmaLevel) Enum() *LemmaLevel {
	p := new(LemmaLevel)
	*p = x
	return p
}

func (x LemmaLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LemmaLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_pipeline_v1_lemma_service_proto_enumTypes[0].Descriptor()
}

func (LemmaLevel) Type() protoreflect.EnumType {
	return &file_pipeline_v1_lemma_service_proto_enumTypes[0]
}

func (x LemmaLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LemmaLevel.Descriptor instead.
func (LemmaLevel) EnumDescriptor() ([]byte, []int) {
	return file_pipeline_v1_lemma_service_proto_rawDescGZIP(), []int{0}
}

type ListLemmasRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Pagination *v1.PaginationRequest  `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// Optional fuzzy search on lemma surface / normalized form.
	Keyword       string `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLemmasRequest) Reset() {
	*x = ListLemmasRequest{}
	mi := &file_pipeline_v1_lemma_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLemmasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLemmasRequest) ProtoMessage() {}

func (x *ListLemmasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_v1_lemma_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLemmasRequest.ProtoReflect.Descriptor instead.
func (*ListLemmasRequest) Descriptor() ([]byte, []int) {
	return file_pipeline_v1_lemma_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListLemmasRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListLemmasRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type LemmaItem struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Surface    string                 `protobuf:"bytes,2,opt,name=surface,proto3" json:"surface,omitempty"`
	Normalized string                 `protobuf:"bytes,3,opt,name=normalized,proto3" json:"normalized,omitempty"`
	Level      LemmaLevel             `protobuf:"varint,4,opt,name=level,proto3,enum=pipeline.v1.LemmaLevel" json:"level,omitempty"`
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Latest materialized snapshot for this lemma. Nil when not synthesized yet.
	Snapshot      *LemmaSnapshot `protobuf:"bytes,7,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LemmaItem) Reset() {
	*x = LemmaItem{}
	mi := &file_pipeline_v1_lemma_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LemmaItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LemmaItem) ProtoMessage() {}

func (x *LemmaItem) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_v1_lemma_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LemmaItem.ProtoReflect.Descriptor instead.
func (*LemmaItem) Descriptor() ([]byte, []int) {
	return file_pipeline_v1_lemma_service_proto_rawDescGZIP(), []int{1}
}

func (x *LemmaItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LemmaItem) GetSurface() string {
	if x != nil {
		return x.Surface
	}
	return ""
}

func (x *LemmaItem) GetNormalized() string {
	if x != nil {
		return x.Normalized
	}
	return ""
}

func (x *LemmaItem) GetLevel() LemmaLevel {
	if x != nil {
		return x.Level
	}
	return LemmaLevel_LEMMA_LEVEL_UNSPECIFIED
}

func (x *LemmaItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *LemmaItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *LemmaItem) GetSnapshot() *LemmaSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type LemmaSnapshotPhonetic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ipa           string                 `protobuf:"bytes,1,opt,name=ipa,proto3" json:"ipa,omitempty"`
	Dialect       string                 `protobuf:"bytes,2,opt,name=dialect,proto3" json:"dialect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LemmaSnapshotPhonetic) Reset() {
	*x = LemmaSnapshotPhonetic{}
	mi := &file_pipeline_v1_lemma_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LemmaSnapshotPhonetic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LemmaSnapshotPhonetic) ProtoMessage() {}

func (x *LemmaSnapshotPhonetic) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_v1_lemma_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LemmaSnapshotPhonetic.ProtoReflect.Descriptor instead.
func (*LemmaSnapshotPhonetic) Descriptor() ([]byte, []int) {
	return file_pipeline_v1_lemma_service_proto_rawDescGZIP(), []int{2}
}

func (x *LemmaSnapshotPhonetic) GetIpa() string {
	if x != nil {
		return x.Ipa
	}
	return ""
}

func (x *LemmaSnapshotPhonetic) GetDialect() string {
	if x != nil {
		return x.Dialect
	}
	return ""
}

type LemmaSnapshotSense struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Gloss         string                 `protobuf:"bytes,2,opt,name=gloss,proto3" json:"gloss,omitempty"`
	Examples      []string               `protobuf:"bytes,3,rep,name=examples,proto3" json:"examples,omitempty"`
	Provider      string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	TrustWeight   float64                `protobuf:"fixed64,5,opt,name=trust_weight,json=trustWeight,proto3" json:"trust_weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LemmaSnapshotSense) Reset() {
	*x = LemmaSnapshotSense{}
	mi := &file_pipeline_v1_lemma_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LemmaSnapshotSense) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LemmaSnapshotSense) ProtoMessage() {}

func (x *LemmaSnapshotSense) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_v1_lemma_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LemmaSnapshotSense.ProtoReflect.Descriptor instead.
func (*LemmaSnapshotSense) Descriptor() ([]byte, []int) {
	return file_pipeline_v1_lemma_service_proto_rawDescGZIP(), []int{3}
}

func (x *LemmaSnapshotSense) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *LemmaSnapshotSense) GetGloss() string {
	if x != nil {
		return x.Gloss
	}
	return ""
}

func (x *LemmaSnapshotSense) GetExamples() []string {
	if x != nil {
		return x.Examples
	}
	return nil
}

func (x *LemmaSnapshotSense) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LemmaSnapshotSense) GetTrustWeight() float64 {
	if x != nil {
		return x.TrustWeight
	}
	return 0
}

type LemmaSnapshotForm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Surface       string                 `protobuf:"bytes,1,opt,name=surface,proto3" json:"surface,omitempty"`
	FormType      string                 `protobuf:"bytes,2,opt,name=form_type,json=formType,proto3" json:"form_type,omitempty"`
	IsIrregular   bool                   `protobuf:"varint,3,opt,name=is_irregular,json=isIrregular,proto3" json:"is_irregular,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LemmaSnapshotForm) Reset() {
	*x = LemmaSnapshotForm{}
	mi := &file_pipeline_v1_lemma_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LemmaSnapshotForm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LemmaSnapshotForm) ProtoMessage() {}

func (x *LemmaSnapshotForm) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_v1_lemma_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LemmaSnapshotForm.ProtoReflect.Descriptor instead.
func (*LemmaSnapshotForm) Descriptor() ([]byte, []int) {
	return file_pipeline_v1_lemma_service_proto_rawDescGZIP(), []int{4}
}

func (x *LemmaSnapshotForm) GetSurface() string {
	if x != nil {
		return x.Surface
	}
	return ""
}

func (x *LemmaSnapshotForm) GetFormType() string {
	if x != nil {
		return x.FormType
	}
	return ""
}

func (x *LemmaSnapshotForm) GetIsIrregular() bool {
	if x != nil {
		return x.IsIrregular
	}
	return false
}

type LemmaSnapshotLexeme struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Pos           string                   `protobuf:"bytes,1,opt,name=pos,proto3" json:"pos,omitempty"`
	Senses        []*LemmaSnapshotSense    `protobuf:"bytes,2,rep,name=senses,proto3" json:"senses,omitempty"`
	Forms         []*LemmaSnapshotForm     `protobuf:"bytes,3,rep,name=forms,proto3" json:"forms,omitempty"`
	Phonetics     []*LemmaSnapshotPhonetic `protobuf:"bytes,4,rep,name=phonetics,proto3" json:"phonetics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LemmaSnapshotLexeme) Reset() {
	*x = LemmaSnapshotLexeme{}
	mi := &file_pipeline_v1_lemma_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LemmaSnapshotLexeme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LemmaSnapshotLexeme) ProtoMessage() {}

func (x *LemmaSnapshotLexeme) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_v1_lemma_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LemmaSnapshotLexeme.ProtoReflect.Descriptor instead.
func (*LemmaSnapshotLexeme) Descriptor() ([]byte, []int) {
	return file_pipeline_v1_lemma_service_proto_rawDescGZIP(), []int{5}
}

func (x *LemmaSnapshotLexeme) GetPos() string {
	if x != nil {
		return x.Pos
	}
	return ""
}

func (x *LemmaSnapshotLexeme) GetSenses() []*LemmaSnapshotSense {
	if x != nil {
		return x.Senses
	}
	return nil
}

func (x *LemmaSnapshotLexeme) GetForms() []*LemmaSnapshotForm {
	if x != nil {
		return x.Forms
	}
	return nil
}

func (x *LemmaSnapshotLexeme) GetPhonetics() []*LemmaSnapshotPhonetic {
	if x != nil {
		return x.Phonetics
	}
	return nil
}

type LemmaSnapshotRelation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RelationType   string                 `protobuf:"bytes,1,opt,name=relation_type,json=relationType,proto3" json:"relation_type,omitempty"`
	TargetTerm     string                 `protobuf:"bytes,2,opt,name=target_term,json=targetTerm,proto3" json:"target_term,omitempty"`
	TargetRef      string                 `protobuf:"bytes,3,opt,name=target_ref,json=targetRef,proto3" json:"target_ref,omitempty"`
	Provider       string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	Strength       float64                `protobuf:"fixed64,5,opt,name=strength,proto3" json:"strength,omitempty"`
	SenseMapped    bool                   `protobuf:"varint,6,opt,name=sense_mapped,json=senseMapped,proto3" json:"sense_mapped,omitempty"`
	TargetResolved bool                   `protobuf:"varint,7,opt,name=target_resolved,json=targetResolved,proto3" json:"target_resolved,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LemmaSnapshotRelation) Reset() {
	*x = LemmaSnapshotRelation{}
	mi := &file_pipeline_v1_lemma_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LemmaSnapshotRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LemmaSnapshotRelation) ProtoMessage() {}

func (x *LemmaSnapshotRelation) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_v1_lemma_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LemmaSnapshotRelation.ProtoReflect.Descriptor instead.
func (*LemmaSnapshotRelation) Descriptor() ([]byte, []int) {
	return file_pipeline_v1_lemma_service_proto_rawDescGZIP(), []int{6}
}

func (x *LemmaSnapshotRelation) GetRelationType() string {
	if x != nil {
		return x.RelationType
	}
	return ""
}

func (x *LemmaSnapshotRelation) GetTargetTerm() string {
	if x != nil {
		return x.TargetTerm
	}
	return ""
}

func (x *LemmaSnapshotRelation) GetTargetRef() string {
	if x != nil {
		return x.TargetRef
	}
	return ""
}

func (x *LemmaSnapshotRelation) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LemmaSnapshotRelation) GetStrength() float64 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *LemmaSnapshotRelation) GetSenseMapped() bool {
	if x != nil {
		return x.SenseMapped
	}
	return false
}

func (x *LemmaSnapshotRelation) GetTargetResolved() bool {
	if x != nil {
		return x.TargetResolved
	}
	return false
}

type LemmaSnapshotData struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Lexemes       []*LemmaSnapshotLexeme   `protobuf:"bytes,1,rep,name=lexemes,proto3" json:"lexemes,omitempty"`
	Relations     []*LemmaSnapshotRelation `protobuf:"bytes,2,rep,name=relations,proto3" json:"relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LemmaSnapshotData) Reset() {
	*x = LemmaSnapshotData{}
	mi := &file_pipeline_v1_lemma_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LemmaSnapshotData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LemmaSnapshotData) ProtoMessage() {}

func (x *LemmaSnapshotData) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_v1_lemma_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LemmaSnapshotData.ProtoReflect.Descriptor instead.
func (*LemmaSnapshotData) Descriptor() ([]byte, []int) {
	return file_pipeline_v1_lemma_service_proto_rawDescGZIP(), []int{7}
}

func (x *LemmaSnapshotData) GetLexemes() []*LemmaSnapshotLexeme {
	if x != nil {
		return x.Lexemes
	}
	return nil
}

func (x *LemmaSnapshotData) GetRelations() []*LemmaSnapshotRelation {
	if x != nil {
		return x.Relations
	}
	return nil
}

type LemmaSnapshot struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LemmaId            int64                  `protobuf:"varint,2,opt,name=lemma_id,json=lemmaId,proto3" json:"lemma_id,omitempty"`
	JobId              *int64                 `protobuf:"varint,3,opt,name=job_id,json=jobId,proto3,oneof" json:"job_id,omitempty"`
	Term               string                 `protobuf:"bytes,4,opt,name=term,proto3" json:"term,omitempty"`
	Terms              []string               `protobuf:"bytes,5,rep,name=terms,proto3" json:"terms,omitempty"`
	Language           string                 `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	Latest             bool                   `protobuf:"varint,7,opt,name=latest,proto3" json:"latest,omitempty"`
	Version            int32                  `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	Data               *LemmaSnapshotData     `protobuf:"bytes,9,opt,name=data,proto3" json:"data,omitempty"`
	QScore             float64                `protobuf:"fixed64,10,opt,name=q_score,json=qScore,proto3" json:"q_score,omitempty"`
	QScoreCompleteness float64                `protobuf:"fixed64,11,opt,name=q_score_completeness,json=qScoreCompleteness,proto3" json:"q_score_completeness,omitempty"`
	QScoreDepth        float64                `protobuf:"fixed64,12,opt,name=q_score_depth,json=qScoreDepth,proto3" json:"q_score_depth,omitempty"`
	QScoreDensity      float64                `protobuf:"fixed64,13,opt,name=q_score_density,json=qScoreDensity,proto3" json:"q_score_density,omitempty"`
	QScoreValidity     float64                `protobuf:"fixed64,14,opt,name=q_score_validity,json=qScoreValidity,proto3" json:"q_score_validity,omitempty"`
	SynthesizedAt      *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=synthesized_at,json=synthesizedAt,proto3" json:"synthesized_at,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LemmaSnapshot) Reset() {
	*x = LemmaSnapshot{}
	mi := &file_pipeline_v1_lemma_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LemmaSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LemmaSnapshot) ProtoMessage() {}

func (x *LemmaSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_v1_lemma_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LemmaSnapshot.ProtoReflect.Descriptor instead.
func (*LemmaSnapshot) Descriptor() ([]byte, []int) {
	return file_pipeline_v1_lemma_service_proto_rawDescGZIP(), []int{8}
}

func (x *LemmaSnapshot) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LemmaSnapshot) GetLemmaId() int64 {
	if x != nil {
		return x.LemmaId
	}
	return 0
}

func (x *LemmaSnapshot) GetJobId() int64 {
	if x != nil && x.JobId != nil {
		return *x.JobId
	}
	return 0
}

func (x *LemmaSnapshot) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *LemmaSnapshot) GetTerms() []string {
	if x != nil {
		return x.Terms
	}
	return nil
}

func (x *LemmaSnapshot) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *LemmaSnapshot) GetLatest() bool {
	if x != nil {
		return x.Latest
	}
	return false
}

func (x *LemmaSnapshot) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *LemmaSnapshot) GetData() *LemmaSnapshotData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LemmaSnapshot) GetQScore() float64 {
	if x != nil {
		return x.QScore
	}
	return 0
}

func (x *LemmaSnapshot) GetQScoreCompleteness() float64 {
	if x != nil {
		return x.QScoreCompleteness
	}
	return 0
}

func (x *LemmaSnapshot) GetQScoreDepth() float64 {
	if x != nil {
		return x.QScoreDepth
	}
	return 0
}

func (x *LemmaSnapshot) GetQScoreDensity() float64 {
	if x != nil {
		return x.QScoreDensity
	}
	return 0
}

func (x *LemmaSnapshot) GetQScoreValidity() float64 {
	if x != nil {
		return x.QScoreValidity
	}
	return 0
}

func (x *LemmaSnapshot) GetSynthesizedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SynthesizedAt
	}
	return nil
}

func (x *LemmaSnapshot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *LemmaSnapshot) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListLemmasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lemmas        []*LemmaItem           `protobuf:"bytes,1,rep,name=lemmas,proto3" json:"lemmas,omitempty"`
	Pagination    *v1.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLemmasResponse) Reset() {
	*x = ListLemmasResponse{}
	mi := &file_pipeline_v1_lemma_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLemmasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLemmasResponse) ProtoMessage() {}

func (x *ListLemmasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_v1_lemma_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLemmasResponse.ProtoReflect.Descriptor instead.
func (*ListLemmasResponse) Descriptor() ([]byte, []int) {
	return file_pipeline_v1_lemma_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListLemmasResponse) GetLemmas() []*LemmaItem {
	if x != nil {
		return x.Lemmas
	}
	return nil
}

func (x *ListLemmasResponse) GetPagination() *v1.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_pipeline_v1_lemma_service_proto protoreflect.FileDescriptor

const file_pipeline_v1_lemma_service_proto_rawDesc = "" +
	"\n" +
	"\x1fpipeline/v1/lemma_service.proto\x12\vpipeline.v1\x1a\x15common/v1/types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1apipeline/v1/pipeline.proto\"k\n" +
	"\x11ListLemmasRequest\x12<\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1c.common.v1.PaginationRequestR\n" +
	"pagination\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\"\xb2\x02\n" +
	"\tLemmaItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\asurface\x18\x02 \x01(\tR\asurface\x12\x1e\n" +
	"\n" +
	"normalized\x18\x03 \x01(\tR\n" +
	"normalized\x12-\n" +
	"\x05level\x18\x04 \x01(\x0e2\x17.pipeline.v1.LemmaLevelR\x05level\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x126\n" +
	"\bsnapshot\x18\a \x01(\v2\x1a.pipeline.v1.LemmaSnapshotR\bsnapshot\"C\n" +
	"\x15LemmaSnapshotPhonetic\x12\x10\n" +
	"\x03ipa\x18\x01 \x01(\tR\x03ipa\x12\x18\n" +
	"\adialect\x18\x02 \x01(\tR\adialect\"\xa1\x01\n" +
	"\x12LemmaSnapshotSense\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x14\n" +
	"\x05gloss\x18\x02 \x01(\tR\x05gloss\x12\x1a\n" +
	"\bexamples\x18\x03 \x03(\tR\bexamples\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12!\n" +
	"\ftrust_weight\x18\x05 \x01(\x01R\vtrustWeight\"m\n" +
	"\x11LemmaSnapshotForm\x12\x18\n" +
	"\asurface\x18\x01 \x01(\tR\asurface\x12\x1b\n" +
	"\tform_type\x18\x02 \x01(\tR\bformType\x12!\n" +
	"\fis_irregular\x18\x03 \x01(\bR\visIrregular\"\xd8\x01\n" +
	"\x13LemmaSnapshotLexeme\x12\x10\n" +
	"\x03pos\x18\x01 \x01(\tR\x03pos\x127\n" +
	"\x06senses\x18\x02 \x03(\v2\x1f.pipeline.v1.LemmaSnapshotSenseR\x06senses\x124\n" +
	"\x05forms\x18\x03 \x03(\v2\x1e.pipeline.v1.LemmaSnapshotFormR\x05forms\x12@\n" +
	"\tphonetics\x18\x04 \x03(\v2\".pipeline.v1.LemmaSnapshotPhoneticR\tphonetics\"\x80\x02\n" +
	"\x15LemmaSnapshotRelation\x12#\n" +
	"\rrelation_type\x18\x01 \x01(\tR\frelationType\x12\x1f\n" +
	"\vtarget_term\x18\x02 \x01(\tR\n" +
	"targetTerm\x12\x1d\n" +
	"\n" +
	"target_ref\x18\x03 \x01(\tR\ttargetRef\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12\x1a\n" +
	"\bstrength\x18\x05 \x01(\x01R\bstrength\x12!\n" +
	"\fsense_mapped\x18\x06 \x01(\bR\vsenseMapped\x12'\n" +
	"\x0ftarget_resolved\x18\a \x01(\bR\x0etargetResolved\"\x91\x01\n" +
	"\x11LemmaSnapshotData\x12:\n" +
	"\alexemes\x18\x01 \x03(\v2 .pipeline.v1.LemmaSnapshotLexemeR\alexemes\x12@\n" +
	"\trelations\x18\x02 \x03(\v2\".pipeline.v1.LemmaSnapshotRelationR\trelations\"\x87\x05\n" +
	"\rLemmaSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\blemma_id\x18\x02 \x01(\x03R\alemmaId\x12\x1a\n" +
	"\x06job_id\x18\x03 \x01(\x03H\x00R\x05jobId\x88\x01\x01\x12\x12\n" +
	"\x04term\x18\x04 \x01(\tR\x04term\x12\x14\n" +
	"\x05terms\x18\x05 \x03(\tR\x05terms\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\x12\x16\n" +
	"\x06latest\x18\a \x01(\bR\x06latest\x12\x18\n" +
	"\aversion\x18\b \x01(\x05R\aversion\x122\n" +
	"\x04data\x18\t \x01(\v2\x1e.pipeline.v1.LemmaSnapshotDataR\x04data\x12\x17\n" +
	"\aq_score\x18\n" +
	" \x01(\x01R\x06qScore\x120\n" +
	"\x14q_score_completeness\x18\v \x01(\x01R\x12qScoreCompleteness\x12\"\n" +
	"\rq_score_depth\x18\f \x01(\x01R\vqScoreDepth\x12&\n" +
	"\x0fq_score_density\x18\r \x01(\x01R\rqScoreDensity\x12(\n" +
	"\x10q_score_validity\x18\x0e \x01(\x01R\x0eqScoreValidity\x12A\n" +
	"\x0esynthesized_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\rsynthesizedAt\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\t\n" +
	"\a_job_id\"\x83\x01\n" +
	"\x12ListLemmasResponse\x12.\n" +
	"\x06lemmas\x18\x01 \x03(\v2\x16.pipeline.v1.LemmaItemR\x06lemmas\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.common.v1.PaginationResponseR\n" +
	"pagination*\xa1\x01\n" +
	"\n" +
	"LemmaLevel\x12\x1b\n" +
	"\x17LEMMA_LEVEL_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eLEMMA_LEVEL_A1\x10\x01\x12\x12\n" +
	"\x0eLEMMA_LEVEL_A2\x10\x02\x12\x12\n" +
	"\x0eLEMMA_LEVEL_B1\x10\x03\x12\x12\n" +
	"\x0eLEMMA_LEVEL_B2\x10\x04\x12\x12\n" +
	"\x0eLEMMA_LEVEL_C1\x10\x05\x12\x12\n" +
	"\x0eLEMMA_LEVEL_C2\x10\x062]\n" +
	"\fLemmaService\x12M\n" +
	"\n" +
	"ListLemmas\x12\x1e.pipeline.v1.ListLemmasRequest\x1a\x1f.pipeline.v1.ListLemmasResponseB\xab\x01\n" +
	"\x0fcom.pipeline.v1B\x11LemmaServiceProtoP\x01Z8github.com/eslsoft/vocnet/pkg/api/pipeline/v1;pipelinev1\xa2\x02\x03PXX\xaa\x02\vPipeline.V1\xca\x02\vPipeline\\V1\xe2\x02\x17Pipeline\\V1\\GPBMetadata\xea\x02\fPipeline::V1b\x06proto3"

var (
	file_pipeline_v1_lemma_service_proto_rawDescOnce sync.Once
	file_pipeline_v1_lemma_service_proto_rawDescData []byte
)

func file_pipeline_v1_lemma_service_proto_rawDescGZIP() []byte {
	file_pipeline_v1_lemma_service_proto_rawDescOnce.Do(func() {
		file_pipeline_v1_lemma_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pipeline_v1_lemma_service_proto_rawDesc), len(file_pipeline_v1_lemma_service_proto_rawDesc)))
	})
	return file_pipeline_v1_lemma_service_proto_rawDescData
}

var file_pipeline_v1_lemma_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pipeline_v1_lemma_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pipeline_v1_lemma_service_proto_goTypes = []any{
	(LemmaLevel)(0),               // 0: pipeline.v1.LemmaLevel
	(*ListLemmasRequest)(nil),     // 1: pipeline.v1.ListLemmasRequest
	(*LemmaItem)(nil),             // 2: pipeline.v1.LemmaItem
	(*LemmaSnapshotPhonetic)(nil), // 3: pipeline.v1.LemmaSnapshotPhonetic
	(*LemmaSnapshotSense)(nil),    // 4: pipeline.v1.LemmaSnapshotSense
	(*LemmaSnapshotForm)(nil),     // 5: pipeline.v1.LemmaSnapshotForm
	(*LemmaSnapshotLexeme)(nil),   // 6: pipeline.v1.LemmaSnapshotLexeme
	(*LemmaSnapshotRelation)(nil), // 7: pipeline.v1.LemmaSnapshotRelation
	(*LemmaSnapshotData)(nil),     // 8: pipeline.v1.LemmaSnapshotData
	(*LemmaSnapshot)(nil),         // 9: pipeline.v1.LemmaSnapshot
	(*ListLemmasResponse)(nil),    // 10: pipeline.v1.ListLemmasResponse
	(*v1.PaginationRequest)(nil),  // 11: common.v1.PaginationRequest
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*v1.PaginationResponse)(nil), // 13: common.v1.PaginationResponse
}
var file_pipeline_v1_lemma_service_proto_depIdxs = []int32{
	11, // 0: pipeline.v1.ListLemmasRequest.pagination:type_name -> common.v1.PaginationRequest
	0,  // 1: pipeline.v1.LemmaItem.level:type_name -> pipeline.v1.LemmaLevel
	12, // 2: pipeline.v1.LemmaItem.created_at:type_name -> google.protobuf.Timestamp
	12, // 3: pipeline.v1.LemmaItem.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 4: pipeline.v1.LemmaItem.snapshot:type_name -> pipeline.v1.LemmaSnapshot
	4,  // 5: pipeline.v1.LemmaSnapshotLexeme.senses:type_name -> pipeline.v1.LemmaSnapshotSense
	5,  // 6: pipeline.v1.LemmaSnapshotLexeme.forms:type_name -> pipeline.v1.LemmaSnapshotForm
	3,  // 7: pipeline.v1.LemmaSnapshotLexeme.phonetics:type_name -> pipeline.v1.LemmaSnapshotPhonetic
	6,  // 8: pipeline.v1.LemmaSnapshotData.lexemes:type_name -> pipeline.v1.LemmaSnapshotLexeme
	7,  // 9: pipeline.v1.LemmaSnapshotData.relations:type_name -> pipeline.v1.LemmaSnapshotRelation
	8,  // 10: pipeline.v1.LemmaSnapshot.data:type_name -> pipeline.v1.LemmaSnapshotData
	12, // 11: pipeline.v1.LemmaSnapshot.synthesized_at:type_name -> google.protobuf.Timestamp
	12, // 12: pipeline.v1.LemmaSnapshot.created_at:type_name -> google.protobuf.Timestamp
	12, // 13: pipeline.v1.LemmaSnapshot.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 14: pipeline.v1.ListLemmasResponse.lemmas:type_name -> pipeline.v1.LemmaItem
	13, // 15: pipeline.v1.ListLemmasResponse.pagination:type_name -> common.v1.PaginationResponse
	1,  // 16: pipeline.v1.LemmaService.ListLemmas:input_type -> pipeline.v1.ListLemmasRequest
	10, // 17: pipeline.v1.LemmaService.ListLemmas:output_type -> pipeline.v1.ListLemmasResponse
	17, // [17:18] is the sub-list for method output_type
	16, // [16:17] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_pipeline_v1_lemma_service_proto_init() }
func file_pipeline_v1_lemma_service_proto_init() {
	if File_pipeline_v1_lemma_service_proto != nil {
		return
	}
	file_pipeline_v1_pipeline_proto_init()
	file_pipeline_v1_lemma_service_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pipeline_v1_lemma_service_proto_rawDesc), len(file_pipeline_v1_lemma_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pipeline_v1_lemma_service_proto_goTypes,
		DependencyIndexes: file_pipeline_v1_lemma_service_proto_depIdxs,
		EnumInfos:         file_pipeline_v1_lemma_service_proto_enumTypes,
		MessageInfos:      file_pipeline_v1_lemma_service_proto_msgTypes,
	}.Build()
	File_pipeline_v1_lemma_service_proto = out.File
	file_pipeline_v1_lemma_service_proto_goTypes = nil
	file_pipeline_v1_lemma_service_proto_depIdxs = nil
}
