// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pipeline/v1/pipeline.proto

package pipelinev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PipelineJobType int32

const (
	PipelineJobType_PIPELINE_JOB_TYPE_UNSPECIFIED PipelineJobType = 0
	PipelineJobType_PIPELINE_JOB_TYPE_SINGLE_WORD PipelineJobType = 1
	PipelineJobType_PIPELINE_JOB_TYPE_WORDBOOK    PipelineJobType = 2
)

// Enum value maps for PipelineJobType.
var (
	PipelineJobType_name = map[int32]string{
		0: "PIPELINE_JOB_TYPE_UNSPECIFIED",
		1: "PIPELINE_JOB_TYPE_SINGLE_WORD",
		2: "PIPELINE_JOB_TYPE_WORDBOOK",
	}
	PipelineJobType_value = map[string]int32{
		"PIPELINE_JOB_TYPE_UNSPECIFIED": 0,
		"PIPELINE_JOB_TYPE_SINGLE_WORD": 1,
		"PIPELINE_JOB_TYPE_WORDBOOK":    2,
	}
)

func (x PipelineJobType) Enum() *PipelineJobType {
	p := new(PipelineJobType)
	*p = x
	return p
}

func (x PipelineJobType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PipelineJobType) Descriptor() protoreflect.EnumDescriptor {
	return file_pipeline_v1_pipeline_proto_enumTypes[0].Descriptor()
}

func (PipelineJobType) Type() protoreflect.EnumType {
	return &file_pipeline_v1_pipeline_proto_enumTypes[0]
}

func (x PipelineJobType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PipelineJobType.Descriptor instead.
func (PipelineJobType) EnumDescriptor() ([]byte, []int) {
	return file_pipeline_v1_pipeline_proto_rawDescGZIP(), []int{0}
}

type PipelineJobStatus int32

const (
	PipelineJobStatus_PIPELINE_JOB_STATUS_UNSPECIFIED PipelineJobStatus = 0
	PipelineJobStatus_PIPELINE_JOB_STATUS_PENDING     PipelineJobStatus = 1
	PipelineJobStatus_PIPELINE_JOB_STATUS_RUNNING     PipelineJobStatus = 2
	PipelineJobStatus_PIPELINE_JOB_STATUS_PAUSED      PipelineJobStatus = 3
	PipelineJobStatus_PIPELINE_JOB_STATUS_COMPLETED   PipelineJobStatus = 4
	PipelineJobStatus_PIPELINE_JOB_STATUS_FAILED      PipelineJobStatus = 5
	PipelineJobStatus_PIPELINE_JOB_STATUS_CANCELLED   PipelineJobStatus = 6
)

// Enum value maps for PipelineJobStatus.
var (
	PipelineJobStatus_name = map[int32]string{
		0: "PIPELINE_JOB_STATUS_UNSPECIFIED",
		1: "PIPELINE_JOB_STATUS_PENDING",
		2: "PIPELINE_JOB_STATUS_RUNNING",
		3: "PIPELINE_JOB_STATUS_PAUSED",
		4: "PIPELINE_JOB_STATUS_COMPLETED",
		5: "PIPELINE_JOB_STATUS_FAILED",
		6: "PIPELINE_JOB_STATUS_CANCELLED",
	}
	PipelineJobStatus_value = map[string]int32{
		"PIPELINE_JOB_STATUS_UNSPECIFIED": 0,
		"PIPELINE_JOB_STATUS_PENDING":     1,
		"PIPELINE_JOB_STATUS_RUNNING":     2,
		"PIPELINE_JOB_STATUS_PAUSED":      3,
		"PIPELINE_JOB_STATUS_COMPLETED":   4,
		"PIPELINE_JOB_STATUS_FAILED":      5,
		"PIPELINE_JOB_STATUS_CANCELLED":   6,
	}
)

func (x PipelineJobStatus) Enum() *PipelineJobStatus {
	p := new(PipelineJobStatus)
	*p = x
	return p
}

func (x PipelineJobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PipelineJobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pipeline_v1_pipeline_proto_enumTypes[1].Descriptor()
}

func (PipelineJobStatus) Type() protoreflect.EnumType {
	return &file_pipeline_v1_pipeline_proto_enumTypes[1]
}

func (x PipelineJobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PipelineJobStatus.Descriptor instead.
func (PipelineJobStatus) EnumDescriptor() ([]byte, []int) {
	return file_pipeline_v1_pipeline_proto_rawDescGZIP(), []int{1}
}

type PipelinePhase int32

const (
	PipelinePhase_PIPELINE_PHASE_UNSPECIFIED  PipelinePhase = 0
	PipelinePhase_PIPELINE_PHASE_DISCOVERY    PipelinePhase = 1
	PipelinePhase_PIPELINE_PHASE_LEXICAL      PipelinePhase = 2
	PipelinePhase_PIPELINE_PHASE_RELATIONAL   PipelinePhase = 3
	PipelinePhase_PIPELINE_PHASE_INTELLECTUAL PipelinePhase = 4
	PipelinePhase_PIPELINE_PHASE_SYNTHESIS    PipelinePhase = 5
)

// Enum value maps for PipelinePhase.
var (
	PipelinePhase_name = map[int32]string{
		0: "PIPELINE_PHASE_UNSPECIFIED",
		1: "PIPELINE_PHASE_DISCOVERY",
		2: "PIPELINE_PHASE_LEXICAL",
		3: "PIPELINE_PHASE_RELATIONAL",
		4: "PIPELINE_PHASE_INTELLECTUAL",
		5: "PIPELINE_PHASE_SYNTHESIS",
	}
	PipelinePhase_value = map[string]int32{
		"PIPELINE_PHASE_UNSPECIFIED":  0,
		"PIPELINE_PHASE_DISCOVERY":    1,
		"PIPELINE_PHASE_LEXICAL":      2,
		"PIPELINE_PHASE_RELATIONAL":   3,
		"PIPELINE_PHASE_INTELLECTUAL": 4,
		"PIPELINE_PHASE_SYNTHESIS":    5,
	}
)

func (x PipelinePhase) Enum() *PipelinePhase {
	p := new(PipelinePhase)
	*p = x
	return p
}

func (x PipelinePhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PipelinePhase) Descriptor() protoreflect.EnumDescriptor {
	return file_pipeline_v1_pipeline_proto_enumTypes[2].Descriptor()
}

func (PipelinePhase) Type() protoreflect.EnumType {
	return &file_pipeline_v1_pipeline_proto_enumTypes[2]
}

func (x PipelinePhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PipelinePhase.Descriptor instead.
func (PipelinePhase) EnumDescriptor() ([]byte, []int) {
	return file_pipeline_v1_pipeline_proto_rawDescGZIP(), []int{2}
}

type PipelineStageStatus int32

const (
	PipelineStageStatus_PIPELINE_STAGE_STATUS_UNSPECIFIED PipelineStageStatus = 0
	PipelineStageStatus_PIPELINE_STAGE_STATUS_PENDING     PipelineStageStatus = 1
	PipelineStageStatus_PIPELINE_STAGE_STATUS_RUNNING     PipelineStageStatus = 2
	PipelineStageStatus_PIPELINE_STAGE_STATUS_COMPLETED   PipelineStageStatus = 3
	PipelineStageStatus_PIPELINE_STAGE_STATUS_FAILED      PipelineStageStatus = 4
	PipelineStageStatus_PIPELINE_STAGE_STATUS_SKIPPED     PipelineStageStatus = 5
)

// Enum value maps for PipelineStageStatus.
var (
	PipelineStageStatus_name = map[int32]string{
		0: "PIPELINE_STAGE_STATUS_UNSPECIFIED",
		1: "PIPELINE_STAGE_STATUS_PENDING",
		2: "PIPELINE_STAGE_STATUS_RUNNING",
		3: "PIPELINE_STAGE_STATUS_COMPLETED",
		4: "PIPELINE_STAGE_STATUS_FAILED",
		5: "PIPELINE_STAGE_STATUS_SKIPPED",
	}
	PipelineStageStatus_value = map[string]int32{
		"PIPELINE_STAGE_STATUS_UNSPECIFIED": 0,
		"PIPELINE_STAGE_STATUS_PENDING":     1,
		"PIPELINE_STAGE_STATUS_RUNNING":     2,
		"PIPELINE_STAGE_STATUS_COMPLETED":   3,
		"PIPELINE_STAGE_STATUS_FAILED":      4,
		"PIPELINE_STAGE_STATUS_SKIPPED":     5,
	}
)

func (x PipelineStageStatus) Enum() *PipelineStageStatus {
	p := new(PipelineStageStatus)
	*p = x
	return p
}

func (x PipelineStageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PipelineStageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pipeline_v1_pipeline_proto_enumTypes[3].Descriptor()
}

func (PipelineStageStatus) Type() protoreflect.EnumType {
	return &file_pipeline_v1_pipeline_proto_enumTypes[3]
}

func (x PipelineStageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PipelineStageStatus.Descriptor instead.
func (PipelineStageStatus) EnumDescriptor() ([]byte, []int) {
	return file_pipeline_v1_pipeline_proto_rawDescGZIP(), []int{3}
}

type PipelineActionType int32

const (
	PipelineActionType_PIPELINE_ACTION_TYPE_UNSPECIFIED PipelineActionType = 0
	PipelineActionType_PIPELINE_ACTION_TYPE_CANCEL      PipelineActionType = 1
	// Retry creates a new pipeline run/job; it does not mutate stage execution of old job.
	PipelineActionType_PIPELINE_ACTION_TYPE_RETRY PipelineActionType = 2
)

// Enum value maps for PipelineActionType.
var (
	PipelineActionType_name = map[int32]string{
		0: "PIPELINE_ACTION_TYPE_UNSPECIFIED",
		1: "PIPELINE_ACTION_TYPE_CANCEL",
		2: "PIPELINE_ACTION_TYPE_RETRY",
	}
	PipelineActionType_value = map[string]int32{
		"PIPELINE_ACTION_TYPE_UNSPECIFIED": 0,
		"PIPELINE_ACTION_TYPE_CANCEL":      1,
		"PIPELINE_ACTION_TYPE_RETRY":       2,
	}
)

func (x PipelineActionType) Enum() *PipelineActionType {
	p := new(PipelineActionType)
	*p = x
	return p
}

func (x PipelineActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PipelineActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_pipeline_v1_pipeline_proto_enumTypes[4].Descriptor()
}

func (PipelineActionType) Type() protoreflect.EnumType {
	return &file_pipeline_v1_pipeline_proto_enumTypes[4]
}

func (x PipelineActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PipelineActionType.Descriptor instead.
func (PipelineActionType) EnumDescriptor() ([]byte, []int) {
	return file_pipeline_v1_pipeline_proto_rawDescGZIP(), []int{4}
}

type PipelineJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	JobType       PipelineJobType        `protobuf:"varint,2,opt,name=job_type,json=jobType,proto3,enum=pipeline.v1.PipelineJobType" json:"job_type,omitempty"`
	Status        PipelineJobStatus      `protobuf:"varint,3,opt,name=status,proto3,enum=pipeline.v1.PipelineJobStatus" json:"status,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Language      string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	Tier          int32                  `protobuf:"varint,6,opt,name=tier,proto3" json:"tier,omitempty"`
	Term          string                 `protobuf:"bytes,7,opt,name=term,proto3" json:"term,omitempty"`
	TotalTerms    int32                  `protobuf:"varint,8,opt,name=total_terms,json=totalTerms,proto3" json:"total_terms,omitempty"`
	Processed     int32                  `protobuf:"varint,9,opt,name=processed,proto3" json:"processed,omitempty"`
	Skipped       int32                  `protobuf:"varint,10,opt,name=skipped,proto3" json:"skipped,omitempty"`
	Failed        int32                  `protobuf:"varint,11,opt,name=failed,proto3" json:"failed,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,12,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineJob) Reset() {
	*x = PipelineJob{}
	mi := &file_pipeline_v1_pipeline_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineJob) ProtoMessage() {}

func (x *PipelineJob) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_v1_pipeline_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineJob.ProtoReflect.Descriptor instead.
func (*PipelineJob) Descriptor() ([]byte, []int) {
	return file_pipeline_v1_pipeline_proto_rawDescGZIP(), []int{0}
}

func (x *PipelineJob) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PipelineJob) GetJobType() PipelineJobType {
	if x != nil {
		return x.JobType
	}
	return PipelineJobType_PIPELINE_JOB_TYPE_UNSPECIFIED
}

func (x *PipelineJob) GetStatus() PipelineJobStatus {
	if x != nil {
		return x.Status
	}
	return PipelineJobStatus_PIPELINE_JOB_STATUS_UNSPECIFIED
}

func (x *PipelineJob) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PipelineJob) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *PipelineJob) GetTier() int32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

func (x *PipelineJob) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *PipelineJob) GetTotalTerms() int32 {
	if x != nil {
		return x.TotalTerms
	}
	return 0
}

func (x *PipelineJob) GetProcessed() int32 {
	if x != nil {
		return x.Processed
	}
	return 0
}

func (x *PipelineJob) GetSkipped() int32 {
	if x != nil {
		return x.Skipped
	}
	return 0
}

func (x *PipelineJob) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *PipelineJob) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PipelineJob) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *PipelineJob) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *PipelineJob) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PipelineJob) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type PipelineDropStage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	JobId         int64                  `protobuf:"varint,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	LemmaId       int64                  `protobuf:"varint,3,opt,name=lemma_id,json=lemmaId,proto3" json:"lemma_id,omitempty"`
	Phase         PipelinePhase          `protobuf:"varint,4,opt,name=phase,proto3,enum=pipeline.v1.PipelinePhase" json:"phase,omitempty"`
	Status        PipelineStageStatus    `protobuf:"varint,5,opt,name=status,proto3,enum=pipeline.v1.PipelineStageStatus" json:"status,omitempty"`
	Attempts      int32                  `protobuf:"varint,6,opt,name=attempts,proto3" json:"attempts,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineDropStage) Reset() {
	*x = PipelineDropStage{}
	mi := &file_pipeline_v1_pipeline_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineDropStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineDropStage) ProtoMessage() {}

func (x *PipelineDropStage) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_v1_pipeline_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineDropStage.ProtoReflect.Descriptor instead.
func (*PipelineDropStage) Descriptor() ([]byte, []int) {
	return file_pipeline_v1_pipeline_proto_rawDescGZIP(), []int{1}
}

func (x *PipelineDropStage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PipelineDropStage) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *PipelineDropStage) GetLemmaId() int64 {
	if x != nil {
		return x.LemmaId
	}
	return 0
}

func (x *PipelineDropStage) GetPhase() PipelinePhase {
	if x != nil {
		return x.Phase
	}
	return PipelinePhase_PIPELINE_PHASE_UNSPECIFIED
}

func (x *PipelineDropStage) GetStatus() PipelineStageStatus {
	if x != nil {
		return x.Status
	}
	return PipelineStageStatus_PIPELINE_STAGE_STATUS_UNSPECIFIED
}

func (x *PipelineDropStage) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *PipelineDropStage) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PipelineDropStage) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *PipelineDropStage) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *PipelineDropStage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PipelineDropStage) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_pipeline_v1_pipeline_proto protoreflect.FileDescriptor

const file_pipeline_v1_pipeline_proto_rawDesc = "" +
	"\n" +
	"\x1apipeline/v1/pipeline.proto\x12\vpipeline.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xec\x04\n" +
	"\vPipelineJob\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x127\n" +
	"\bjob_type\x18\x02 \x01(\x0e2\x1c.pipeline.v1.PipelineJobTypeR\ajobType\x126\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1e.pipeline.v1.PipelineJobStatusR\x06status\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\x12\x12\n" +
	"\x04tier\x18\x06 \x01(\x05R\x04tier\x12\x12\n" +
	"\x04term\x18\a \x01(\tR\x04term\x12\x1f\n" +
	"\vtotal_terms\x18\b \x01(\x05R\n" +
	"totalTerms\x12\x1c\n" +
	"\tprocessed\x18\t \x01(\x05R\tprocessed\x12\x18\n" +
	"\askipped\x18\n" +
	" \x01(\x05R\askipped\x12\x16\n" +
	"\x06failed\x18\v \x01(\x05R\x06failed\x12#\n" +
	"\rerror_message\x18\f \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"started_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf2\x03\n" +
	"\x11PipelineDropStage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\x03R\x05jobId\x12\x19\n" +
	"\blemma_id\x18\x03 \x01(\x03R\alemmaId\x120\n" +
	"\x05phase\x18\x04 \x01(\x0e2\x1a.pipeline.v1.PipelinePhaseR\x05phase\x128\n" +
	"\x06status\x18\x05 \x01(\x0e2 .pipeline.v1.PipelineStageStatusR\x06status\x12\x1a\n" +
	"\battempts\x18\x06 \x01(\x05R\battempts\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*w\n" +
	"\x0fPipelineJobType\x12!\n" +
	"\x1dPIPELINE_JOB_TYPE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dPIPELINE_JOB_TYPE_SINGLE_WORD\x10\x01\x12\x1e\n" +
	"\x1aPIPELINE_JOB_TYPE_WORDBOOK\x10\x02*\x80\x02\n" +
	"\x11PipelineJobStatus\x12#\n" +
	"\x1fPIPELINE_JOB_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bPIPELINE_JOB_STATUS_PENDING\x10\x01\x12\x1f\n" +
	"\x1bPIPELINE_JOB_STATUS_RUNNING\x10\x02\x12\x1e\n" +
	"\x1aPIPELINE_JOB_STATUS_PAUSED\x10\x03\x12!\n" +
	"\x1dPIPELINE_JOB_STATUS_COMPLETED\x10\x04\x12\x1e\n" +
	"\x1aPIPELINE_JOB_STATUS_FAILED\x10\x05\x12!\n" +
	"\x1dPIPELINE_JOB_STATUS_CANCELLED\x10\x06*\xc7\x01\n" +
	"\rPipelinePhase\x12\x1e\n" +
	"\x1aPIPELINE_PHASE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18PIPELINE_PHASE_DISCOVERY\x10\x01\x12\x1a\n" +
	"\x16PIPELINE_PHASE_LEXICAL\x10\x02\x12\x1d\n" +
	"\x19PIPELINE_PHASE_RELATIONAL\x10\x03\x12\x1f\n" +
	"\x1bPIPELINE_PHASE_INTELLECTUAL\x10\x04\x12\x1c\n" +
	"\x18PIPELINE_PHASE_SYNTHESIS\x10\x05*\xec\x01\n" +
	"\x13PipelineStageStatus\x12%\n" +
	"!PIPELINE_STAGE_STATUS_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dPIPELINE_STAGE_STATUS_PENDING\x10\x01\x12!\n" +
	"\x1dPIPELINE_STAGE_STATUS_RUNNING\x10\x02\x12#\n" +
	"\x1fPIPELINE_STAGE_STATUS_COMPLETED\x10\x03\x12 \n" +
	"\x1cPIPELINE_STAGE_STATUS_FAILED\x10\x04\x12!\n" +
	"\x1dPIPELINE_STAGE_STATUS_SKIPPED\x10\x05*{\n" +
	"\x12PipelineActionType\x12$\n" +
	" PIPELINE_ACTION_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bPIPELINE_ACTION_TYPE_CANCEL\x10\x01\x12\x1e\n" +
	"\x1aPIPELINE_ACTION_TYPE_RETRY\x10\x02B\xa7\x01\n" +
	"\x0fcom.pipeline.v1B\rPipelineProtoP\x01Z8github.com/eslsoft/vocnet/pkg/api/pipeline/v1;pipelinev1\xa2\x02\x03PXX\xaa\x02\vPipeline.V1\xca\x02\vPipeline\\V1\xe2\x02\x17Pipeline\\V1\\GPBMetadata\xea\x02\fPipeline::V1b\x06proto3"

var (
	file_pipeline_v1_pipeline_proto_rawDescOnce sync.Once
	file_pipeline_v1_pipeline_proto_rawDescData []byte
)

func file_pipeline_v1_pipeline_proto_rawDescGZIP() []byte {
	file_pipeline_v1_pipeline_proto_rawDescOnce.Do(func() {
		file_pipeline_v1_pipeline_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pipeline_v1_pipeline_proto_rawDesc), len(file_pipeline_v1_pipeline_proto_rawDesc)))
	})
	return file_pipeline_v1_pipeline_proto_rawDescData
}

var file_pipeline_v1_pipeline_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_pipeline_v1_pipeline_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pipeline_v1_pipeline_proto_goTypes = []any{
	(PipelineJobType)(0),          // 0: pipeline.v1.PipelineJobType
	(PipelineJobStatus)(0),        // 1: pipeline.v1.PipelineJobStatus
	(PipelinePhase)(0),            // 2: pipeline.v1.PipelinePhase
	(PipelineStageStatus)(0),      // 3: pipeline.v1.PipelineStageStatus
	(PipelineActionType)(0),       // 4: pipeline.v1.PipelineActionType
	(*PipelineJob)(nil),           // 5: pipeline.v1.PipelineJob
	(*PipelineDropStage)(nil),     // 6: pipeline.v1.PipelineDropStage
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_pipeline_v1_pipeline_proto_depIdxs = []int32{
	0,  // 0: pipeline.v1.PipelineJob.job_type:type_name -> pipeline.v1.PipelineJobType
	1,  // 1: pipeline.v1.PipelineJob.status:type_name -> pipeline.v1.PipelineJobStatus
	7,  // 2: pipeline.v1.PipelineJob.started_at:type_name -> google.protobuf.Timestamp
	7,  // 3: pipeline.v1.PipelineJob.completed_at:type_name -> google.protobuf.Timestamp
	7,  // 4: pipeline.v1.PipelineJob.created_at:type_name -> google.protobuf.Timestamp
	7,  // 5: pipeline.v1.PipelineJob.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 6: pipeline.v1.PipelineDropStage.phase:type_name -> pipeline.v1.PipelinePhase
	3,  // 7: pipeline.v1.PipelineDropStage.status:type_name -> pipeline.v1.PipelineStageStatus
	7,  // 8: pipeline.v1.PipelineDropStage.started_at:type_name -> google.protobuf.Timestamp
	7,  // 9: pipeline.v1.PipelineDropStage.completed_at:type_name -> google.protobuf.Timestamp
	7,  // 10: pipeline.v1.PipelineDropStage.created_at:type_name -> google.protobuf.Timestamp
	7,  // 11: pipeline.v1.PipelineDropStage.updated_at:type_name -> google.protobuf.Timestamp
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_pipeline_v1_pipeline_proto_init() }
func file_pipeline_v1_pipeline_proto_init() {
	if File_pipeline_v1_pipeline_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pipeline_v1_pipeline_proto_rawDesc), len(file_pipeline_v1_pipeline_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pipeline_v1_pipeline_proto_goTypes,
		DependencyIndexes: file_pipeline_v1_pipeline_proto_depIdxs,
		EnumInfos:         file_pipeline_v1_pipeline_proto_enumTypes,
		MessageInfos:      file_pipeline_v1_pipeline_proto_msgTypes,
	}.Build()
	File_pipeline_v1_pipeline_proto = out.File
	file_pipeline_v1_pipeline_proto_goTypes = nil
	file_pipeline_v1_pipeline_proto_depIdxs = nil
}
