// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: pipeline/v1/pipeline_service.proto

package pipelinev1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SubmitJobRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SubmitJobRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SubmitJobRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SubmitJobRequestMultiError, or nil if none found.
func (m *SubmitJobRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SubmitJobRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetTerm()) < 1 {
		err := SubmitJobRequestValidationError{
			field:  "Term",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Language

	// no validation rules for Tier

	// no validation rules for Name

	if len(errors) > 0 {
		return SubmitJobRequestMultiError(errors)
	}

	return nil
}

// SubmitJobRequestMultiError is an error wrapping multiple validation errors
// returned by SubmitJobRequest.ValidateAll() if the designated constraints
// aren't met.
type SubmitJobRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SubmitJobRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SubmitJobRequestMultiError) AllErrors() []error { return m }

// SubmitJobRequestValidationError is the validation error returned by
// SubmitJobRequest.Validate if the designated constraints aren't met.
type SubmitJobRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SubmitJobRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SubmitJobRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SubmitJobRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SubmitJobRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SubmitJobRequestValidationError) ErrorName() string { return "SubmitJobRequestValidationError" }

// Error satisfies the builtin error interface
func (e SubmitJobRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSubmitJobRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SubmitJobRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SubmitJobRequestValidationError{}

// Validate checks the field values on SubmitJobResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SubmitJobResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SubmitJobResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SubmitJobResponseMultiError, or nil if none found.
func (m *SubmitJobResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SubmitJobResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetJob()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SubmitJobResponseValidationError{
					field:  "Job",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SubmitJobResponseValidationError{
					field:  "Job",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetJob()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SubmitJobResponseValidationError{
				field:  "Job",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SubmitJobResponseMultiError(errors)
	}

	return nil
}

// SubmitJobResponseMultiError is an error wrapping multiple validation errors
// returned by SubmitJobResponse.ValidateAll() if the designated constraints
// aren't met.
type SubmitJobResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SubmitJobResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SubmitJobResponseMultiError) AllErrors() []error { return m }

// SubmitJobResponseValidationError is the validation error returned by
// SubmitJobResponse.Validate if the designated constraints aren't met.
type SubmitJobResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SubmitJobResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SubmitJobResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SubmitJobResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SubmitJobResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SubmitJobResponseValidationError) ErrorName() string {
	return "SubmitJobResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SubmitJobResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSubmitJobResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SubmitJobResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SubmitJobResponseValidationError{}

// Validate checks the field values on ActionJobRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ActionJobRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ActionJobRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ActionJobRequestMultiError, or nil if none found.
func (m *ActionJobRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ActionJobRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetJobId() <= 0 {
		err := ActionJobRequestValidationError{
			field:  "JobId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := PipelineActionType_name[int32(m.GetAction())]; !ok {
		err := ActionJobRequestValidationError{
			field:  "Action",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ActionJobRequestMultiError(errors)
	}

	return nil
}

// ActionJobRequestMultiError is an error wrapping multiple validation errors
// returned by ActionJobRequest.ValidateAll() if the designated constraints
// aren't met.
type ActionJobRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ActionJobRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ActionJobRequestMultiError) AllErrors() []error { return m }

// ActionJobRequestValidationError is the validation error returned by
// ActionJobRequest.Validate if the designated constraints aren't met.
type ActionJobRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ActionJobRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ActionJobRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ActionJobRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ActionJobRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ActionJobRequestValidationError) ErrorName() string { return "ActionJobRequestValidationError" }

// Error satisfies the builtin error interface
func (e ActionJobRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sActionJobRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ActionJobRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ActionJobRequestValidationError{}

// Validate checks the field values on ActionJobResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ActionJobResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ActionJobResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ActionJobResponseMultiError, or nil if none found.
func (m *ActionJobResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ActionJobResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetJob()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ActionJobResponseValidationError{
					field:  "Job",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ActionJobResponseValidationError{
					field:  "Job",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetJob()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ActionJobResponseValidationError{
				field:  "Job",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetNewJob()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ActionJobResponseValidationError{
					field:  "NewJob",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ActionJobResponseValidationError{
					field:  "NewJob",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetNewJob()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ActionJobResponseValidationError{
				field:  "NewJob",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ActionJobResponseMultiError(errors)
	}

	return nil
}

// ActionJobResponseMultiError is an error wrapping multiple validation errors
// returned by ActionJobResponse.ValidateAll() if the designated constraints
// aren't met.
type ActionJobResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ActionJobResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ActionJobResponseMultiError) AllErrors() []error { return m }

// ActionJobResponseValidationError is the validation error returned by
// ActionJobResponse.Validate if the designated constraints aren't met.
type ActionJobResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ActionJobResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ActionJobResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ActionJobResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ActionJobResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ActionJobResponseValidationError) ErrorName() string {
	return "ActionJobResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ActionJobResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sActionJobResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ActionJobResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ActionJobResponseValidationError{}

// Validate checks the field values on ListJobsRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListJobsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListJobsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListJobsRequestMultiError, or nil if none found.
func (m *ListJobsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListJobsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetPagination()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListJobsRequestValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListJobsRequestValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListJobsRequestValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Status

	if m.GetLemmaId() < 0 {
		err := ListJobsRequestValidationError{
			field:  "LemmaId",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ListJobsRequestMultiError(errors)
	}

	return nil
}

// ListJobsRequestMultiError is an error wrapping multiple validation errors
// returned by ListJobsRequest.ValidateAll() if the designated constraints
// aren't met.
type ListJobsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListJobsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListJobsRequestMultiError) AllErrors() []error { return m }

// ListJobsRequestValidationError is the validation error returned by
// ListJobsRequest.Validate if the designated constraints aren't met.
type ListJobsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListJobsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListJobsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListJobsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListJobsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListJobsRequestValidationError) ErrorName() string { return "ListJobsRequestValidationError" }

// Error satisfies the builtin error interface
func (e ListJobsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListJobsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListJobsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListJobsRequestValidationError{}

// Validate checks the field values on PipelineJob with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PipelineJob) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PipelineJob with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PipelineJobMultiError, or
// nil if none found.
func (m *PipelineJob) ValidateAll() error {
	return m.validate(true)
}

func (m *PipelineJob) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for JobType

	// no validation rules for Status

	// no validation rules for Name

	// no validation rules for Language

	// no validation rules for Tier

	// no validation rules for Term

	// no validation rules for TotalTerms

	// no validation rules for Processed

	// no validation rules for Skipped

	// no validation rules for Failed

	// no validation rules for ErrorMessage

	if all {
		switch v := interface{}(m.GetStartedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PipelineJobValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PipelineJobValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PipelineJobValidationError{
				field:  "StartedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCompletedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PipelineJobValidationError{
					field:  "CompletedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PipelineJobValidationError{
					field:  "CompletedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCompletedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PipelineJobValidationError{
				field:  "CompletedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PipelineJobValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PipelineJobValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PipelineJobValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PipelineJobValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PipelineJobValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PipelineJobValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return PipelineJobMultiError(errors)
	}

	return nil
}

// PipelineJobMultiError is an error wrapping multiple validation errors
// returned by PipelineJob.ValidateAll() if the designated constraints aren't met.
type PipelineJobMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PipelineJobMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PipelineJobMultiError) AllErrors() []error { return m }

// PipelineJobValidationError is the validation error returned by
// PipelineJob.Validate if the designated constraints aren't met.
type PipelineJobValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PipelineJobValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PipelineJobValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PipelineJobValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PipelineJobValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PipelineJobValidationError) ErrorName() string { return "PipelineJobValidationError" }

// Error satisfies the builtin error interface
func (e PipelineJobValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPipelineJob.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PipelineJobValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PipelineJobValidationError{}

// Validate checks the field values on ListJobsResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListJobsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListJobsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListJobsResponseMultiError, or nil if none found.
func (m *ListJobsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListJobsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetJobs() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListJobsResponseValidationError{
						field:  fmt.Sprintf("Jobs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListJobsResponseValidationError{
						field:  fmt.Sprintf("Jobs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListJobsResponseValidationError{
					field:  fmt.Sprintf("Jobs[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPagination()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListJobsResponseValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListJobsResponseValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListJobsResponseValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListJobsResponseMultiError(errors)
	}

	return nil
}

// ListJobsResponseMultiError is an error wrapping multiple validation errors
// returned by ListJobsResponse.ValidateAll() if the designated constraints
// aren't met.
type ListJobsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListJobsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListJobsResponseMultiError) AllErrors() []error { return m }

// ListJobsResponseValidationError is the validation error returned by
// ListJobsResponse.Validate if the designated constraints aren't met.
type ListJobsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListJobsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListJobsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListJobsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListJobsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListJobsResponseValidationError) ErrorName() string { return "ListJobsResponseValidationError" }

// Error satisfies the builtin error interface
func (e ListJobsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListJobsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListJobsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListJobsResponseValidationError{}

// Validate checks the field values on ListJobStagesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListJobStagesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListJobStagesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListJobStagesRequestMultiError, or nil if none found.
func (m *ListJobStagesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListJobStagesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetJobId() <= 0 {
		err := ListJobStagesRequestValidationError{
			field:  "JobId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ListJobStagesRequestMultiError(errors)
	}

	return nil
}

// ListJobStagesRequestMultiError is an error wrapping multiple validation
// errors returned by ListJobStagesRequest.ValidateAll() if the designated
// constraints aren't met.
type ListJobStagesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListJobStagesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListJobStagesRequestMultiError) AllErrors() []error { return m }

// ListJobStagesRequestValidationError is the validation error returned by
// ListJobStagesRequest.Validate if the designated constraints aren't met.
type ListJobStagesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListJobStagesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListJobStagesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListJobStagesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListJobStagesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListJobStagesRequestValidationError) ErrorName() string {
	return "ListJobStagesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListJobStagesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListJobStagesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListJobStagesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListJobStagesRequestValidationError{}

// Validate checks the field values on PipelineStage with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PipelineStage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PipelineStage with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PipelineStageMultiError, or
// nil if none found.
func (m *PipelineStage) ValidateAll() error {
	return m.validate(true)
}

func (m *PipelineStage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for JobId

	// no validation rules for LemmaId

	// no validation rules for Phase

	// no validation rules for PhaseName

	// no validation rules for Status

	// no validation rules for Attempts

	// no validation rules for ErrorMessage

	if all {
		switch v := interface{}(m.GetStartedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PipelineStageValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PipelineStageValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PipelineStageValidationError{
				field:  "StartedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCompletedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PipelineStageValidationError{
					field:  "CompletedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PipelineStageValidationError{
					field:  "CompletedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCompletedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PipelineStageValidationError{
				field:  "CompletedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PipelineStageValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PipelineStageValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PipelineStageValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PipelineStageValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PipelineStageValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PipelineStageValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return PipelineStageMultiError(errors)
	}

	return nil
}

// PipelineStageMultiError is an error wrapping multiple validation errors
// returned by PipelineStage.ValidateAll() if the designated constraints
// aren't met.
type PipelineStageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PipelineStageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PipelineStageMultiError) AllErrors() []error { return m }

// PipelineStageValidationError is the validation error returned by
// PipelineStage.Validate if the designated constraints aren't met.
type PipelineStageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PipelineStageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PipelineStageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PipelineStageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PipelineStageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PipelineStageValidationError) ErrorName() string { return "PipelineStageValidationError" }

// Error satisfies the builtin error interface
func (e PipelineStageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPipelineStage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PipelineStageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PipelineStageValidationError{}

// Validate checks the field values on ListJobStagesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListJobStagesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListJobStagesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListJobStagesResponseMultiError, or nil if none found.
func (m *ListJobStagesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListJobStagesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetStages() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListJobStagesResponseValidationError{
						field:  fmt.Sprintf("Stages[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListJobStagesResponseValidationError{
						field:  fmt.Sprintf("Stages[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListJobStagesResponseValidationError{
					field:  fmt.Sprintf("Stages[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListJobStagesResponseMultiError(errors)
	}

	return nil
}

// ListJobStagesResponseMultiError is an error wrapping multiple validation
// errors returned by ListJobStagesResponse.ValidateAll() if the designated
// constraints aren't met.
type ListJobStagesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListJobStagesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListJobStagesResponseMultiError) AllErrors() []error { return m }

// ListJobStagesResponseValidationError is the validation error returned by
// ListJobStagesResponse.Validate if the designated constraints aren't met.
type ListJobStagesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListJobStagesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListJobStagesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListJobStagesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListJobStagesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListJobStagesResponseValidationError) ErrorName() string {
	return "ListJobStagesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListJobStagesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListJobStagesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListJobStagesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListJobStagesResponseValidationError{}

// Validate checks the field values on ListLemmasRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListLemmasRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListLemmasRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListLemmasRequestMultiError, or nil if none found.
func (m *ListLemmasRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListLemmasRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetPagination()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListLemmasRequestValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListLemmasRequestValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListLemmasRequestValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Keyword

	if len(errors) > 0 {
		return ListLemmasRequestMultiError(errors)
	}

	return nil
}

// ListLemmasRequestMultiError is an error wrapping multiple validation errors
// returned by ListLemmasRequest.ValidateAll() if the designated constraints
// aren't met.
type ListLemmasRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListLemmasRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListLemmasRequestMultiError) AllErrors() []error { return m }

// ListLemmasRequestValidationError is the validation error returned by
// ListLemmasRequest.Validate if the designated constraints aren't met.
type ListLemmasRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListLemmasRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListLemmasRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListLemmasRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListLemmasRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListLemmasRequestValidationError) ErrorName() string {
	return "ListLemmasRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListLemmasRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListLemmasRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListLemmasRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListLemmasRequestValidationError{}

// Validate checks the field values on LemmaItem with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LemmaItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LemmaItem with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LemmaItemMultiError, or nil
// if none found.
func (m *LemmaItem) ValidateAll() error {
	return m.validate(true)
}

func (m *LemmaItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Surface

	// no validation rules for Normalized

	// no validation rules for Level

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LemmaItemValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LemmaItemValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LemmaItemValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LemmaItemValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LemmaItemValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LemmaItemValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return LemmaItemMultiError(errors)
	}

	return nil
}

// LemmaItemMultiError is an error wrapping multiple validation errors returned
// by LemmaItem.ValidateAll() if the designated constraints aren't met.
type LemmaItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LemmaItemMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LemmaItemMultiError) AllErrors() []error { return m }

// LemmaItemValidationError is the validation error returned by
// LemmaItem.Validate if the designated constraints aren't met.
type LemmaItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LemmaItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LemmaItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LemmaItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LemmaItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LemmaItemValidationError) ErrorName() string { return "LemmaItemValidationError" }

// Error satisfies the builtin error interface
func (e LemmaItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLemmaItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LemmaItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LemmaItemValidationError{}

// Validate checks the field values on ListLemmasResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListLemmasResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListLemmasResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListLemmasResponseMultiError, or nil if none found.
func (m *ListLemmasResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListLemmasResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetLemmas() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListLemmasResponseValidationError{
						field:  fmt.Sprintf("Lemmas[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListLemmasResponseValidationError{
						field:  fmt.Sprintf("Lemmas[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListLemmasResponseValidationError{
					field:  fmt.Sprintf("Lemmas[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPagination()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListLemmasResponseValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListLemmasResponseValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListLemmasResponseValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListLemmasResponseMultiError(errors)
	}

	return nil
}

// ListLemmasResponseMultiError is an error wrapping multiple validation errors
// returned by ListLemmasResponse.ValidateAll() if the designated constraints
// aren't met.
type ListLemmasResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListLemmasResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListLemmasResponseMultiError) AllErrors() []error { return m }

// ListLemmasResponseValidationError is the validation error returned by
// ListLemmasResponse.Validate if the designated constraints aren't met.
type ListLemmasResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListLemmasResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListLemmasResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListLemmasResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListLemmasResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListLemmasResponseValidationError) ErrorName() string {
	return "ListLemmasResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListLemmasResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListLemmasResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListLemmasResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListLemmasResponseValidationError{}
