// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: dict/v1/lemma_service.proto

package dictv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/eslsoft/vocnet/pkg/api/dict/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LemmaServiceName is the fully-qualified name of the LemmaService service.
	LemmaServiceName = "dict.v1.LemmaService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LemmaServiceListLemmasProcedure is the fully-qualified name of the LemmaService's ListLemmas RPC.
	LemmaServiceListLemmasProcedure = "/dict.v1.LemmaService/ListLemmas"
	// LemmaServiceListLemmaSnapshotsProcedure is the fully-qualified name of the LemmaService's
	// ListLemmaSnapshots RPC.
	LemmaServiceListLemmaSnapshotsProcedure = "/dict.v1.LemmaService/ListLemmaSnapshots"
)

// LemmaServiceClient is a client for the dict.v1.LemmaService service.
type LemmaServiceClient interface {
	// ListLemmas lists lemmas with optional fuzzy keyword matching.
	ListLemmas(context.Context, *connect.Request[v1.ListLemmasRequest]) (*connect.Response[v1.ListLemmasResponse], error)
	// ListLemmaSnapshots lists all snapshots for one lemma.
	ListLemmaSnapshots(context.Context, *connect.Request[v1.ListSnapshotsRequest]) (*connect.Response[v1.ListLemmaSnapshotsResponse], error)
}

// NewLemmaServiceClient constructs a client for the dict.v1.LemmaService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLemmaServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LemmaServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	lemmaServiceMethods := v1.File_dict_v1_lemma_service_proto.Services().ByName("LemmaService").Methods()
	return &lemmaServiceClient{
		listLemmas: connect.NewClient[v1.ListLemmasRequest, v1.ListLemmasResponse](
			httpClient,
			baseURL+LemmaServiceListLemmasProcedure,
			connect.WithSchema(lemmaServiceMethods.ByName("ListLemmas")),
			connect.WithClientOptions(opts...),
		),
		listLemmaSnapshots: connect.NewClient[v1.ListSnapshotsRequest, v1.ListLemmaSnapshotsResponse](
			httpClient,
			baseURL+LemmaServiceListLemmaSnapshotsProcedure,
			connect.WithSchema(lemmaServiceMethods.ByName("ListLemmaSnapshots")),
			connect.WithClientOptions(opts...),
		),
	}
}

// lemmaServiceClient implements LemmaServiceClient.
type lemmaServiceClient struct {
	listLemmas         *connect.Client[v1.ListLemmasRequest, v1.ListLemmasResponse]
	listLemmaSnapshots *connect.Client[v1.ListSnapshotsRequest, v1.ListLemmaSnapshotsResponse]
}

// ListLemmas calls dict.v1.LemmaService.ListLemmas.
func (c *lemmaServiceClient) ListLemmas(ctx context.Context, req *connect.Request[v1.ListLemmasRequest]) (*connect.Response[v1.ListLemmasResponse], error) {
	return c.listLemmas.CallUnary(ctx, req)
}

// ListLemmaSnapshots calls dict.v1.LemmaService.ListLemmaSnapshots.
func (c *lemmaServiceClient) ListLemmaSnapshots(ctx context.Context, req *connect.Request[v1.ListSnapshotsRequest]) (*connect.Response[v1.ListLemmaSnapshotsResponse], error) {
	return c.listLemmaSnapshots.CallUnary(ctx, req)
}

// LemmaServiceHandler is an implementation of the dict.v1.LemmaService service.
type LemmaServiceHandler interface {
	// ListLemmas lists lemmas with optional fuzzy keyword matching.
	ListLemmas(context.Context, *connect.Request[v1.ListLemmasRequest]) (*connect.Response[v1.ListLemmasResponse], error)
	// ListLemmaSnapshots lists all snapshots for one lemma.
	ListLemmaSnapshots(context.Context, *connect.Request[v1.ListSnapshotsRequest]) (*connect.Response[v1.ListLemmaSnapshotsResponse], error)
}

// NewLemmaServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLemmaServiceHandler(svc LemmaServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	lemmaServiceMethods := v1.File_dict_v1_lemma_service_proto.Services().ByName("LemmaService").Methods()
	lemmaServiceListLemmasHandler := connect.NewUnaryHandler(
		LemmaServiceListLemmasProcedure,
		svc.ListLemmas,
		connect.WithSchema(lemmaServiceMethods.ByName("ListLemmas")),
		connect.WithHandlerOptions(opts...),
	)
	lemmaServiceListLemmaSnapshotsHandler := connect.NewUnaryHandler(
		LemmaServiceListLemmaSnapshotsProcedure,
		svc.ListLemmaSnapshots,
		connect.WithSchema(lemmaServiceMethods.ByName("ListLemmaSnapshots")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dict.v1.LemmaService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LemmaServiceListLemmasProcedure:
			lemmaServiceListLemmasHandler.ServeHTTP(w, r)
		case LemmaServiceListLemmaSnapshotsProcedure:
			lemmaServiceListLemmaSnapshotsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLemmaServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLemmaServiceHandler struct{}

func (UnimplementedLemmaServiceHandler) ListLemmas(context.Context, *connect.Request[v1.ListLemmasRequest]) (*connect.Response[v1.ListLemmasResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dict.v1.LemmaService.ListLemmas is not implemented"))
}

func (UnimplementedLemmaServiceHandler) ListLemmaSnapshots(context.Context, *connect.Request[v1.ListSnapshotsRequest]) (*connect.Response[v1.ListLemmaSnapshotsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dict.v1.LemmaService.ListLemmaSnapshots is not implemented"))
}
