// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pipeline/v1/pipeline_service.proto

package pipelinev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/eslsoft/vocnet/pkg/api/pipeline/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PipelineServiceName is the fully-qualified name of the PipelineService service.
	PipelineServiceName = "pipeline.v1.PipelineService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PipelineServiceProcessWordProcedure is the fully-qualified name of the PipelineService's
	// ProcessWord RPC.
	PipelineServiceProcessWordProcedure = "/pipeline.v1.PipelineService/ProcessWord"
	// PipelineServiceGetPipelineStatusProcedure is the fully-qualified name of the PipelineService's
	// GetPipelineStatus RPC.
	PipelineServiceGetPipelineStatusProcedure = "/pipeline.v1.PipelineService/GetPipelineStatus"
	// PipelineServiceRetryPhaseProcedure is the fully-qualified name of the PipelineService's
	// RetryPhase RPC.
	PipelineServiceRetryPhaseProcedure = "/pipeline.v1.PipelineService/RetryPhase"
	// PipelineServiceGetWordSnapshotProcedure is the fully-qualified name of the PipelineService's
	// GetWordSnapshot RPC.
	PipelineServiceGetWordSnapshotProcedure = "/pipeline.v1.PipelineService/GetWordSnapshot"
	// PipelineServiceListWordSnapshotsProcedure is the fully-qualified name of the PipelineService's
	// ListWordSnapshots RPC.
	PipelineServiceListWordSnapshotsProcedure = "/pipeline.v1.PipelineService/ListWordSnapshots"
	// PipelineServiceGetEvidenceProcedure is the fully-qualified name of the PipelineService's
	// GetEvidence RPC.
	PipelineServiceGetEvidenceProcedure = "/pipeline.v1.PipelineService/GetEvidence"
	// PipelineServiceSubmitJobProcedure is the fully-qualified name of the PipelineService's SubmitJob
	// RPC.
	PipelineServiceSubmitJobProcedure = "/pipeline.v1.PipelineService/SubmitJob"
	// PipelineServiceGetJobProcedure is the fully-qualified name of the PipelineService's GetJob RPC.
	PipelineServiceGetJobProcedure = "/pipeline.v1.PipelineService/GetJob"
	// PipelineServiceListJobsProcedure is the fully-qualified name of the PipelineService's ListJobs
	// RPC.
	PipelineServiceListJobsProcedure = "/pipeline.v1.PipelineService/ListJobs"
	// PipelineServiceCancelJobProcedure is the fully-qualified name of the PipelineService's CancelJob
	// RPC.
	PipelineServiceCancelJobProcedure = "/pipeline.v1.PipelineService/CancelJob"
	// PipelineServiceListDataSourcesProcedure is the fully-qualified name of the PipelineService's
	// ListDataSources RPC.
	PipelineServiceListDataSourcesProcedure = "/pipeline.v1.PipelineService/ListDataSources"
	// PipelineServiceDownloadDataSourceProcedure is the fully-qualified name of the PipelineService's
	// DownloadDataSource RPC.
	PipelineServiceDownloadDataSourceProcedure = "/pipeline.v1.PipelineService/DownloadDataSource"
)

// PipelineServiceClient is a client for the pipeline.v1.PipelineService service.
type PipelineServiceClient interface {
	// ProcessWord runs the full pipeline for a given term (synchronous).
	ProcessWord(context.Context, *connect.Request[v1.ProcessWordRequest]) (*connect.Response[v1.ProcessWordResponse], error)
	// GetPipelineStatus returns the status of pipeline tasks for a word.
	GetPipelineStatus(context.Context, *connect.Request[v1.GetPipelineStatusRequest]) (*connect.Response[v1.PipelineStatus], error)
	// RetryPhase retries a failed phase for a word.
	RetryPhase(context.Context, *connect.Request[v1.RetryPhaseRequest]) (*connect.Response[v1.PipelineStatus], error)
	// GetWordSnapshot returns the materialized snapshot for a word.
	GetWordSnapshot(context.Context, *connect.Request[v1.GetWordSnapshotRequest]) (*connect.Response[v1.WordSnapshotResponse], error)
	// ListWordSnapshots returns a paginated list of word snapshots.
	ListWordSnapshots(context.Context, *connect.Request[v1.ListWordSnapshotsRequest]) (*connect.Response[v1.ListWordSnapshotsResponse], error)
	// GetEvidence returns raw evidence for a word.
	GetEvidence(context.Context, *connect.Request[v1.GetEvidenceRequest]) (*connect.Response[v1.GetEvidenceResponse], error)
	// SubmitJob creates an async pipeline job for one or more terms.
	SubmitJob(context.Context, *connect.Request[v1.SubmitJobRequest]) (*connect.Response[v1.PipelineJob], error)
	// GetJob returns the details of a pipeline job.
	GetJob(context.Context, *connect.Request[v1.GetJobRequest]) (*connect.Response[v1.PipelineJob], error)
	// ListJobs returns a list of pipeline jobs.
	ListJobs(context.Context, *connect.Request[v1.ListJobsRequest]) (*connect.Response[v1.ListJobsResponse], error)
	// CancelJob cancels a pending or running pipeline job.
	CancelJob(context.Context, *connect.Request[v1.CancelJobRequest]) (*connect.Response[v1.PipelineJob], error)
	// ListDataSources returns the status of all pipeline data sources.
	ListDataSources(context.Context, *connect.Request[v1.ListDataSourcesRequest]) (*connect.Response[v1.ListDataSourcesResponse], error)
	// DownloadDataSource downloads a specific data source.
	DownloadDataSource(context.Context, *connect.Request[v1.DownloadDataSourceRequest]) (*connect.Response[v1.DownloadDataSourceResponse], error)
}

// NewPipelineServiceClient constructs a client for the pipeline.v1.PipelineService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPipelineServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PipelineServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	pipelineServiceMethods := v1.File_pipeline_v1_pipeline_service_proto.Services().ByName("PipelineService").Methods()
	return &pipelineServiceClient{
		processWord: connect.NewClient[v1.ProcessWordRequest, v1.ProcessWordResponse](
			httpClient,
			baseURL+PipelineServiceProcessWordProcedure,
			connect.WithSchema(pipelineServiceMethods.ByName("ProcessWord")),
			connect.WithClientOptions(opts...),
		),
		getPipelineStatus: connect.NewClient[v1.GetPipelineStatusRequest, v1.PipelineStatus](
			httpClient,
			baseURL+PipelineServiceGetPipelineStatusProcedure,
			connect.WithSchema(pipelineServiceMethods.ByName("GetPipelineStatus")),
			connect.WithClientOptions(opts...),
		),
		retryPhase: connect.NewClient[v1.RetryPhaseRequest, v1.PipelineStatus](
			httpClient,
			baseURL+PipelineServiceRetryPhaseProcedure,
			connect.WithSchema(pipelineServiceMethods.ByName("RetryPhase")),
			connect.WithClientOptions(opts...),
		),
		getWordSnapshot: connect.NewClient[v1.GetWordSnapshotRequest, v1.WordSnapshotResponse](
			httpClient,
			baseURL+PipelineServiceGetWordSnapshotProcedure,
			connect.WithSchema(pipelineServiceMethods.ByName("GetWordSnapshot")),
			connect.WithClientOptions(opts...),
		),
		listWordSnapshots: connect.NewClient[v1.ListWordSnapshotsRequest, v1.ListWordSnapshotsResponse](
			httpClient,
			baseURL+PipelineServiceListWordSnapshotsProcedure,
			connect.WithSchema(pipelineServiceMethods.ByName("ListWordSnapshots")),
			connect.WithClientOptions(opts...),
		),
		getEvidence: connect.NewClient[v1.GetEvidenceRequest, v1.GetEvidenceResponse](
			httpClient,
			baseURL+PipelineServiceGetEvidenceProcedure,
			connect.WithSchema(pipelineServiceMethods.ByName("GetEvidence")),
			connect.WithClientOptions(opts...),
		),
		submitJob: connect.NewClient[v1.SubmitJobRequest, v1.PipelineJob](
			httpClient,
			baseURL+PipelineServiceSubmitJobProcedure,
			connect.WithSchema(pipelineServiceMethods.ByName("SubmitJob")),
			connect.WithClientOptions(opts...),
		),
		getJob: connect.NewClient[v1.GetJobRequest, v1.PipelineJob](
			httpClient,
			baseURL+PipelineServiceGetJobProcedure,
			connect.WithSchema(pipelineServiceMethods.ByName("GetJob")),
			connect.WithClientOptions(opts...),
		),
		listJobs: connect.NewClient[v1.ListJobsRequest, v1.ListJobsResponse](
			httpClient,
			baseURL+PipelineServiceListJobsProcedure,
			connect.WithSchema(pipelineServiceMethods.ByName("ListJobs")),
			connect.WithClientOptions(opts...),
		),
		cancelJob: connect.NewClient[v1.CancelJobRequest, v1.PipelineJob](
			httpClient,
			baseURL+PipelineServiceCancelJobProcedure,
			connect.WithSchema(pipelineServiceMethods.ByName("CancelJob")),
			connect.WithClientOptions(opts...),
		),
		listDataSources: connect.NewClient[v1.ListDataSourcesRequest, v1.ListDataSourcesResponse](
			httpClient,
			baseURL+PipelineServiceListDataSourcesProcedure,
			connect.WithSchema(pipelineServiceMethods.ByName("ListDataSources")),
			connect.WithClientOptions(opts...),
		),
		downloadDataSource: connect.NewClient[v1.DownloadDataSourceRequest, v1.DownloadDataSourceResponse](
			httpClient,
			baseURL+PipelineServiceDownloadDataSourceProcedure,
			connect.WithSchema(pipelineServiceMethods.ByName("DownloadDataSource")),
			connect.WithClientOptions(opts...),
		),
	}
}

// pipelineServiceClient implements PipelineServiceClient.
type pipelineServiceClient struct {
	processWord        *connect.Client[v1.ProcessWordRequest, v1.ProcessWordResponse]
	getPipelineStatus  *connect.Client[v1.GetPipelineStatusRequest, v1.PipelineStatus]
	retryPhase         *connect.Client[v1.RetryPhaseRequest, v1.PipelineStatus]
	getWordSnapshot    *connect.Client[v1.GetWordSnapshotRequest, v1.WordSnapshotResponse]
	listWordSnapshots  *connect.Client[v1.ListWordSnapshotsRequest, v1.ListWordSnapshotsResponse]
	getEvidence        *connect.Client[v1.GetEvidenceRequest, v1.GetEvidenceResponse]
	submitJob          *connect.Client[v1.SubmitJobRequest, v1.PipelineJob]
	getJob             *connect.Client[v1.GetJobRequest, v1.PipelineJob]
	listJobs           *connect.Client[v1.ListJobsRequest, v1.ListJobsResponse]
	cancelJob          *connect.Client[v1.CancelJobRequest, v1.PipelineJob]
	listDataSources    *connect.Client[v1.ListDataSourcesRequest, v1.ListDataSourcesResponse]
	downloadDataSource *connect.Client[v1.DownloadDataSourceRequest, v1.DownloadDataSourceResponse]
}

// ProcessWord calls pipeline.v1.PipelineService.ProcessWord.
func (c *pipelineServiceClient) ProcessWord(ctx context.Context, req *connect.Request[v1.ProcessWordRequest]) (*connect.Response[v1.ProcessWordResponse], error) {
	return c.processWord.CallUnary(ctx, req)
}

// GetPipelineStatus calls pipeline.v1.PipelineService.GetPipelineStatus.
func (c *pipelineServiceClient) GetPipelineStatus(ctx context.Context, req *connect.Request[v1.GetPipelineStatusRequest]) (*connect.Response[v1.PipelineStatus], error) {
	return c.getPipelineStatus.CallUnary(ctx, req)
}

// RetryPhase calls pipeline.v1.PipelineService.RetryPhase.
func (c *pipelineServiceClient) RetryPhase(ctx context.Context, req *connect.Request[v1.RetryPhaseRequest]) (*connect.Response[v1.PipelineStatus], error) {
	return c.retryPhase.CallUnary(ctx, req)
}

// GetWordSnapshot calls pipeline.v1.PipelineService.GetWordSnapshot.
func (c *pipelineServiceClient) GetWordSnapshot(ctx context.Context, req *connect.Request[v1.GetWordSnapshotRequest]) (*connect.Response[v1.WordSnapshotResponse], error) {
	return c.getWordSnapshot.CallUnary(ctx, req)
}

// ListWordSnapshots calls pipeline.v1.PipelineService.ListWordSnapshots.
func (c *pipelineServiceClient) ListWordSnapshots(ctx context.Context, req *connect.Request[v1.ListWordSnapshotsRequest]) (*connect.Response[v1.ListWordSnapshotsResponse], error) {
	return c.listWordSnapshots.CallUnary(ctx, req)
}

// GetEvidence calls pipeline.v1.PipelineService.GetEvidence.
func (c *pipelineServiceClient) GetEvidence(ctx context.Context, req *connect.Request[v1.GetEvidenceRequest]) (*connect.Response[v1.GetEvidenceResponse], error) {
	return c.getEvidence.CallUnary(ctx, req)
}

// SubmitJob calls pipeline.v1.PipelineService.SubmitJob.
func (c *pipelineServiceClient) SubmitJob(ctx context.Context, req *connect.Request[v1.SubmitJobRequest]) (*connect.Response[v1.PipelineJob], error) {
	return c.submitJob.CallUnary(ctx, req)
}

// GetJob calls pipeline.v1.PipelineService.GetJob.
func (c *pipelineServiceClient) GetJob(ctx context.Context, req *connect.Request[v1.GetJobRequest]) (*connect.Response[v1.PipelineJob], error) {
	return c.getJob.CallUnary(ctx, req)
}

// ListJobs calls pipeline.v1.PipelineService.ListJobs.
func (c *pipelineServiceClient) ListJobs(ctx context.Context, req *connect.Request[v1.ListJobsRequest]) (*connect.Response[v1.ListJobsResponse], error) {
	return c.listJobs.CallUnary(ctx, req)
}

// CancelJob calls pipeline.v1.PipelineService.CancelJob.
func (c *pipelineServiceClient) CancelJob(ctx context.Context, req *connect.Request[v1.CancelJobRequest]) (*connect.Response[v1.PipelineJob], error) {
	return c.cancelJob.CallUnary(ctx, req)
}

// ListDataSources calls pipeline.v1.PipelineService.ListDataSources.
func (c *pipelineServiceClient) ListDataSources(ctx context.Context, req *connect.Request[v1.ListDataSourcesRequest]) (*connect.Response[v1.ListDataSourcesResponse], error) {
	return c.listDataSources.CallUnary(ctx, req)
}

// DownloadDataSource calls pipeline.v1.PipelineService.DownloadDataSource.
func (c *pipelineServiceClient) DownloadDataSource(ctx context.Context, req *connect.Request[v1.DownloadDataSourceRequest]) (*connect.Response[v1.DownloadDataSourceResponse], error) {
	return c.downloadDataSource.CallUnary(ctx, req)
}

// PipelineServiceHandler is an implementation of the pipeline.v1.PipelineService service.
type PipelineServiceHandler interface {
	// ProcessWord runs the full pipeline for a given term (synchronous).
	ProcessWord(context.Context, *connect.Request[v1.ProcessWordRequest]) (*connect.Response[v1.ProcessWordResponse], error)
	// GetPipelineStatus returns the status of pipeline tasks for a word.
	GetPipelineStatus(context.Context, *connect.Request[v1.GetPipelineStatusRequest]) (*connect.Response[v1.PipelineStatus], error)
	// RetryPhase retries a failed phase for a word.
	RetryPhase(context.Context, *connect.Request[v1.RetryPhaseRequest]) (*connect.Response[v1.PipelineStatus], error)
	// GetWordSnapshot returns the materialized snapshot for a word.
	GetWordSnapshot(context.Context, *connect.Request[v1.GetWordSnapshotRequest]) (*connect.Response[v1.WordSnapshotResponse], error)
	// ListWordSnapshots returns a paginated list of word snapshots.
	ListWordSnapshots(context.Context, *connect.Request[v1.ListWordSnapshotsRequest]) (*connect.Response[v1.ListWordSnapshotsResponse], error)
	// GetEvidence returns raw evidence for a word.
	GetEvidence(context.Context, *connect.Request[v1.GetEvidenceRequest]) (*connect.Response[v1.GetEvidenceResponse], error)
	// SubmitJob creates an async pipeline job for one or more terms.
	SubmitJob(context.Context, *connect.Request[v1.SubmitJobRequest]) (*connect.Response[v1.PipelineJob], error)
	// GetJob returns the details of a pipeline job.
	GetJob(context.Context, *connect.Request[v1.GetJobRequest]) (*connect.Response[v1.PipelineJob], error)
	// ListJobs returns a list of pipeline jobs.
	ListJobs(context.Context, *connect.Request[v1.ListJobsRequest]) (*connect.Response[v1.ListJobsResponse], error)
	// CancelJob cancels a pending or running pipeline job.
	CancelJob(context.Context, *connect.Request[v1.CancelJobRequest]) (*connect.Response[v1.PipelineJob], error)
	// ListDataSources returns the status of all pipeline data sources.
	ListDataSources(context.Context, *connect.Request[v1.ListDataSourcesRequest]) (*connect.Response[v1.ListDataSourcesResponse], error)
	// DownloadDataSource downloads a specific data source.
	DownloadDataSource(context.Context, *connect.Request[v1.DownloadDataSourceRequest]) (*connect.Response[v1.DownloadDataSourceResponse], error)
}

// NewPipelineServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPipelineServiceHandler(svc PipelineServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	pipelineServiceMethods := v1.File_pipeline_v1_pipeline_service_proto.Services().ByName("PipelineService").Methods()
	pipelineServiceProcessWordHandler := connect.NewUnaryHandler(
		PipelineServiceProcessWordProcedure,
		svc.ProcessWord,
		connect.WithSchema(pipelineServiceMethods.ByName("ProcessWord")),
		connect.WithHandlerOptions(opts...),
	)
	pipelineServiceGetPipelineStatusHandler := connect.NewUnaryHandler(
		PipelineServiceGetPipelineStatusProcedure,
		svc.GetPipelineStatus,
		connect.WithSchema(pipelineServiceMethods.ByName("GetPipelineStatus")),
		connect.WithHandlerOptions(opts...),
	)
	pipelineServiceRetryPhaseHandler := connect.NewUnaryHandler(
		PipelineServiceRetryPhaseProcedure,
		svc.RetryPhase,
		connect.WithSchema(pipelineServiceMethods.ByName("RetryPhase")),
		connect.WithHandlerOptions(opts...),
	)
	pipelineServiceGetWordSnapshotHandler := connect.NewUnaryHandler(
		PipelineServiceGetWordSnapshotProcedure,
		svc.GetWordSnapshot,
		connect.WithSchema(pipelineServiceMethods.ByName("GetWordSnapshot")),
		connect.WithHandlerOptions(opts...),
	)
	pipelineServiceListWordSnapshotsHandler := connect.NewUnaryHandler(
		PipelineServiceListWordSnapshotsProcedure,
		svc.ListWordSnapshots,
		connect.WithSchema(pipelineServiceMethods.ByName("ListWordSnapshots")),
		connect.WithHandlerOptions(opts...),
	)
	pipelineServiceGetEvidenceHandler := connect.NewUnaryHandler(
		PipelineServiceGetEvidenceProcedure,
		svc.GetEvidence,
		connect.WithSchema(pipelineServiceMethods.ByName("GetEvidence")),
		connect.WithHandlerOptions(opts...),
	)
	pipelineServiceSubmitJobHandler := connect.NewUnaryHandler(
		PipelineServiceSubmitJobProcedure,
		svc.SubmitJob,
		connect.WithSchema(pipelineServiceMethods.ByName("SubmitJob")),
		connect.WithHandlerOptions(opts...),
	)
	pipelineServiceGetJobHandler := connect.NewUnaryHandler(
		PipelineServiceGetJobProcedure,
		svc.GetJob,
		connect.WithSchema(pipelineServiceMethods.ByName("GetJob")),
		connect.WithHandlerOptions(opts...),
	)
	pipelineServiceListJobsHandler := connect.NewUnaryHandler(
		PipelineServiceListJobsProcedure,
		svc.ListJobs,
		connect.WithSchema(pipelineServiceMethods.ByName("ListJobs")),
		connect.WithHandlerOptions(opts...),
	)
	pipelineServiceCancelJobHandler := connect.NewUnaryHandler(
		PipelineServiceCancelJobProcedure,
		svc.CancelJob,
		connect.WithSchema(pipelineServiceMethods.ByName("CancelJob")),
		connect.WithHandlerOptions(opts...),
	)
	pipelineServiceListDataSourcesHandler := connect.NewUnaryHandler(
		PipelineServiceListDataSourcesProcedure,
		svc.ListDataSources,
		connect.WithSchema(pipelineServiceMethods.ByName("ListDataSources")),
		connect.WithHandlerOptions(opts...),
	)
	pipelineServiceDownloadDataSourceHandler := connect.NewUnaryHandler(
		PipelineServiceDownloadDataSourceProcedure,
		svc.DownloadDataSource,
		connect.WithSchema(pipelineServiceMethods.ByName("DownloadDataSource")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pipeline.v1.PipelineService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PipelineServiceProcessWordProcedure:
			pipelineServiceProcessWordHandler.ServeHTTP(w, r)
		case PipelineServiceGetPipelineStatusProcedure:
			pipelineServiceGetPipelineStatusHandler.ServeHTTP(w, r)
		case PipelineServiceRetryPhaseProcedure:
			pipelineServiceRetryPhaseHandler.ServeHTTP(w, r)
		case PipelineServiceGetWordSnapshotProcedure:
			pipelineServiceGetWordSnapshotHandler.ServeHTTP(w, r)
		case PipelineServiceListWordSnapshotsProcedure:
			pipelineServiceListWordSnapshotsHandler.ServeHTTP(w, r)
		case PipelineServiceGetEvidenceProcedure:
			pipelineServiceGetEvidenceHandler.ServeHTTP(w, r)
		case PipelineServiceSubmitJobProcedure:
			pipelineServiceSubmitJobHandler.ServeHTTP(w, r)
		case PipelineServiceGetJobProcedure:
			pipelineServiceGetJobHandler.ServeHTTP(w, r)
		case PipelineServiceListJobsProcedure:
			pipelineServiceListJobsHandler.ServeHTTP(w, r)
		case PipelineServiceCancelJobProcedure:
			pipelineServiceCancelJobHandler.ServeHTTP(w, r)
		case PipelineServiceListDataSourcesProcedure:
			pipelineServiceListDataSourcesHandler.ServeHTTP(w, r)
		case PipelineServiceDownloadDataSourceProcedure:
			pipelineServiceDownloadDataSourceHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPipelineServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPipelineServiceHandler struct{}

func (UnimplementedPipelineServiceHandler) ProcessWord(context.Context, *connect.Request[v1.ProcessWordRequest]) (*connect.Response[v1.ProcessWordResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pipeline.v1.PipelineService.ProcessWord is not implemented"))
}

func (UnimplementedPipelineServiceHandler) GetPipelineStatus(context.Context, *connect.Request[v1.GetPipelineStatusRequest]) (*connect.Response[v1.PipelineStatus], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pipeline.v1.PipelineService.GetPipelineStatus is not implemented"))
}

func (UnimplementedPipelineServiceHandler) RetryPhase(context.Context, *connect.Request[v1.RetryPhaseRequest]) (*connect.Response[v1.PipelineStatus], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pipeline.v1.PipelineService.RetryPhase is not implemented"))
}

func (UnimplementedPipelineServiceHandler) GetWordSnapshot(context.Context, *connect.Request[v1.GetWordSnapshotRequest]) (*connect.Response[v1.WordSnapshotResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pipeline.v1.PipelineService.GetWordSnapshot is not implemented"))
}

func (UnimplementedPipelineServiceHandler) ListWordSnapshots(context.Context, *connect.Request[v1.ListWordSnapshotsRequest]) (*connect.Response[v1.ListWordSnapshotsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pipeline.v1.PipelineService.ListWordSnapshots is not implemented"))
}

func (UnimplementedPipelineServiceHandler) GetEvidence(context.Context, *connect.Request[v1.GetEvidenceRequest]) (*connect.Response[v1.GetEvidenceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pipeline.v1.PipelineService.GetEvidence is not implemented"))
}

func (UnimplementedPipelineServiceHandler) SubmitJob(context.Context, *connect.Request[v1.SubmitJobRequest]) (*connect.Response[v1.PipelineJob], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pipeline.v1.PipelineService.SubmitJob is not implemented"))
}

func (UnimplementedPipelineServiceHandler) GetJob(context.Context, *connect.Request[v1.GetJobRequest]) (*connect.Response[v1.PipelineJob], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pipeline.v1.PipelineService.GetJob is not implemented"))
}

func (UnimplementedPipelineServiceHandler) ListJobs(context.Context, *connect.Request[v1.ListJobsRequest]) (*connect.Response[v1.ListJobsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pipeline.v1.PipelineService.ListJobs is not implemented"))
}

func (UnimplementedPipelineServiceHandler) CancelJob(context.Context, *connect.Request[v1.CancelJobRequest]) (*connect.Response[v1.PipelineJob], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pipeline.v1.PipelineService.CancelJob is not implemented"))
}

func (UnimplementedPipelineServiceHandler) ListDataSources(context.Context, *connect.Request[v1.ListDataSourcesRequest]) (*connect.Response[v1.ListDataSourcesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pipeline.v1.PipelineService.ListDataSources is not implemented"))
}

func (UnimplementedPipelineServiceHandler) DownloadDataSource(context.Context, *connect.Request[v1.DownloadDataSourceRequest]) (*connect.Response[v1.DownloadDataSourceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pipeline.v1.PipelineService.DownloadDataSource is not implemented"))
}
