// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: dict/v1/lemma.proto

package dictv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on LemmaData with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LemmaData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LemmaData with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LemmaDataMultiError, or nil
// if none found.
func (m *LemmaData) ValidateAll() error {
	return m.validate(true)
}

func (m *LemmaData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetLexemes() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, LemmaDataValidationError{
						field:  fmt.Sprintf("Lexemes[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, LemmaDataValidationError{
						field:  fmt.Sprintf("Lexemes[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return LemmaDataValidationError{
					field:  fmt.Sprintf("Lexemes[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetRelations() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, LemmaDataValidationError{
						field:  fmt.Sprintf("Relations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, LemmaDataValidationError{
						field:  fmt.Sprintf("Relations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return LemmaDataValidationError{
					field:  fmt.Sprintf("Relations[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return LemmaDataMultiError(errors)
	}

	return nil
}

// LemmaDataMultiError is an error wrapping multiple validation errors returned
// by LemmaData.ValidateAll() if the designated constraints aren't met.
type LemmaDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LemmaDataMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LemmaDataMultiError) AllErrors() []error { return m }

// LemmaDataValidationError is the validation error returned by
// LemmaData.Validate if the designated constraints aren't met.
type LemmaDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LemmaDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LemmaDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LemmaDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LemmaDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LemmaDataValidationError) ErrorName() string { return "LemmaDataValidationError" }

// Error satisfies the builtin error interface
func (e LemmaDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLemmaData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LemmaDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LemmaDataValidationError{}

// Validate checks the field values on Lemma with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Lemma) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Lemma with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in LemmaMultiError, or nil if none found.
func (m *Lemma) ValidateAll() error {
	return m.validate(true)
}

func (m *Lemma) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Surface

	// no validation rules for Normalized

	// no validation rules for Level

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LemmaValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LemmaValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LemmaValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LemmaValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LemmaValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LemmaValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for SnapshotTerm

	// no validation rules for SnapshotLanguage

	// no validation rules for SnapshotLatest

	// no validation rules for SnapshotVersion

	if all {
		switch v := interface{}(m.GetSnapshotData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LemmaValidationError{
					field:  "SnapshotData",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LemmaValidationError{
					field:  "SnapshotData",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSnapshotData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LemmaValidationError{
				field:  "SnapshotData",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for SnapshotQScore

	// no validation rules for SnapshotQScoreCompleteness

	// no validation rules for SnapshotQScoreDepth

	// no validation rules for SnapshotQScoreDensity

	// no validation rules for SnapshotQScoreValidity

	if all {
		switch v := interface{}(m.GetSnapshotSynthesizedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LemmaValidationError{
					field:  "SnapshotSynthesizedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LemmaValidationError{
					field:  "SnapshotSynthesizedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSnapshotSynthesizedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LemmaValidationError{
				field:  "SnapshotSynthesizedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetSnapshotCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LemmaValidationError{
					field:  "SnapshotCreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LemmaValidationError{
					field:  "SnapshotCreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSnapshotCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LemmaValidationError{
				field:  "SnapshotCreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetSnapshotUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LemmaValidationError{
					field:  "SnapshotUpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LemmaValidationError{
					field:  "SnapshotUpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSnapshotUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LemmaValidationError{
				field:  "SnapshotUpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.SnapshotId != nil {
		// no validation rules for SnapshotId
	}

	if m.SnapshotJobId != nil {
		// no validation rules for SnapshotJobId
	}

	if len(errors) > 0 {
		return LemmaMultiError(errors)
	}

	return nil
}

// LemmaMultiError is an error wrapping multiple validation errors returned by
// Lemma.ValidateAll() if the designated constraints aren't met.
type LemmaMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LemmaMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LemmaMultiError) AllErrors() []error { return m }

// LemmaValidationError is the validation error returned by Lemma.Validate if
// the designated constraints aren't met.
type LemmaValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LemmaValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LemmaValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LemmaValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LemmaValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LemmaValidationError) ErrorName() string { return "LemmaValidationError" }

// Error satisfies the builtin error interface
func (e LemmaValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLemma.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LemmaValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LemmaValidationError{}
