// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: dict/v1/lemma_service.proto

package dictv1

import (
	v1 "github.com/eslsoft/vocnet/pkg/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListLemmasRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Pagination *v1.PaginationRequest  `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// Optional fuzzy search on lemma surface / normalized form.
	Keyword       string `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLemmasRequest) Reset() {
	*x = ListLemmasRequest{}
	mi := &file_dict_v1_lemma_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLemmasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLemmasRequest) ProtoMessage() {}

func (x *ListLemmasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dict_v1_lemma_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLemmasRequest.ProtoReflect.Descriptor instead.
func (*ListLemmasRequest) Descriptor() ([]byte, []int) {
	return file_dict_v1_lemma_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListLemmasRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListLemmasRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type ListLemmasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lemmas        []*Lemma               `protobuf:"bytes,1,rep,name=lemmas,proto3" json:"lemmas,omitempty"`
	Pagination    *v1.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLemmasResponse) Reset() {
	*x = ListLemmasResponse{}
	mi := &file_dict_v1_lemma_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLemmasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLemmasResponse) ProtoMessage() {}

func (x *ListLemmasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dict_v1_lemma_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLemmasResponse.ProtoReflect.Descriptor instead.
func (*ListLemmasResponse) Descriptor() ([]byte, []int) {
	return file_dict_v1_lemma_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListLemmasResponse) GetLemmas() []*Lemma {
	if x != nil {
		return x.Lemmas
	}
	return nil
}

func (x *ListLemmasResponse) GetPagination() *v1.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListSnapshotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LemmaId       int64                  `protobuf:"varint,1,opt,name=lemma_id,json=lemmaId,proto3" json:"lemma_id,omitempty"`
	Pagination    *v1.PaginationRequest  `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsRequest) Reset() {
	*x = ListSnapshotsRequest{}
	mi := &file_dict_v1_lemma_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsRequest) ProtoMessage() {}

func (x *ListSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dict_v1_lemma_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*ListSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_dict_v1_lemma_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListSnapshotsRequest) GetLemmaId() int64 {
	if x != nil {
		return x.LemmaId
	}
	return 0
}

func (x *ListSnapshotsRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListLemmaSnapshotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*LemmaSnapshot       `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	Pagination    *v1.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLemmaSnapshotsResponse) Reset() {
	*x = ListLemmaSnapshotsResponse{}
	mi := &file_dict_v1_lemma_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLemmaSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLemmaSnapshotsResponse) ProtoMessage() {}

func (x *ListLemmaSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dict_v1_lemma_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLemmaSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*ListLemmaSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_dict_v1_lemma_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListLemmaSnapshotsResponse) GetSnapshots() []*LemmaSnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

func (x *ListLemmaSnapshotsResponse) GetPagination() *v1.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_dict_v1_lemma_service_proto protoreflect.FileDescriptor

const file_dict_v1_lemma_service_proto_rawDesc = "" +
	"\n" +
	"\x1bdict/v1/lemma_service.proto\x12\adict.v1\x1a\x15common/v1/types.proto\x1a\x13dict/v1/lemma.proto\"k\n" +
	"\x11ListLemmasRequest\x12<\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1c.common.v1.PaginationRequestR\n" +
	"pagination\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\"{\n" +
	"\x12ListLemmasResponse\x12&\n" +
	"\x06lemmas\x18\x01 \x03(\v2\x0e.dict.v1.LemmaR\x06lemmas\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.common.v1.PaginationResponseR\n" +
	"pagination\"o\n" +
	"\x14ListSnapshotsRequest\x12\x19\n" +
	"\blemma_id\x18\x01 \x01(\x03R\alemmaId\x12<\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1c.common.v1.PaginationRequestR\n" +
	"pagination\"\x91\x01\n" +
	"\x1aListLemmaSnapshotsResponse\x124\n" +
	"\tsnapshots\x18\x01 \x03(\v2\x16.dict.v1.LemmaSnapshotR\tsnapshots\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.common.v1.PaginationResponseR\n" +
	"pagination2\xaf\x01\n" +
	"\fLemmaService\x12E\n" +
	"\n" +
	"ListLemmas\x12\x1a.dict.v1.ListLemmasRequest\x1a\x1b.dict.v1.ListLemmasResponse\x12X\n" +
	"\x12ListLemmaSnapshots\x12\x1d.dict.v1.ListSnapshotsRequest\x1a#.dict.v1.ListLemmaSnapshotsResponseB\x8f\x01\n" +
	"\vcom.dict.v1B\x11LemmaServiceProtoP\x01Z0github.com/eslsoft/vocnet/pkg/api/dict/v1;dictv1\xa2\x02\x03DXX\xaa\x02\aDict.V1\xca\x02\aDict\\V1\xe2\x02\x13Dict\\V1\\GPBMetadata\xea\x02\bDict::V1b\x06proto3"

var (
	file_dict_v1_lemma_service_proto_rawDescOnce sync.Once
	file_dict_v1_lemma_service_proto_rawDescData []byte
)

func file_dict_v1_lemma_service_proto_rawDescGZIP() []byte {
	file_dict_v1_lemma_service_proto_rawDescOnce.Do(func() {
		file_dict_v1_lemma_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dict_v1_lemma_service_proto_rawDesc), len(file_dict_v1_lemma_service_proto_rawDesc)))
	})
	return file_dict_v1_lemma_service_proto_rawDescData
}

var file_dict_v1_lemma_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dict_v1_lemma_service_proto_goTypes = []any{
	(*ListLemmasRequest)(nil),          // 0: dict.v1.ListLemmasRequest
	(*ListLemmasResponse)(nil),         // 1: dict.v1.ListLemmasResponse
	(*ListSnapshotsRequest)(nil),       // 2: dict.v1.ListSnapshotsRequest
	(*ListLemmaSnapshotsResponse)(nil), // 3: dict.v1.ListLemmaSnapshotsResponse
	(*v1.PaginationRequest)(nil),       // 4: common.v1.PaginationRequest
	(*Lemma)(nil),                      // 5: dict.v1.Lemma
	(*v1.PaginationResponse)(nil),      // 6: common.v1.PaginationResponse
	(*LemmaSnapshot)(nil),              // 7: dict.v1.LemmaSnapshot
}
var file_dict_v1_lemma_service_proto_depIdxs = []int32{
	4, // 0: dict.v1.ListLemmasRequest.pagination:type_name -> common.v1.PaginationRequest
	5, // 1: dict.v1.ListLemmasResponse.lemmas:type_name -> dict.v1.Lemma
	6, // 2: dict.v1.ListLemmasResponse.pagination:type_name -> common.v1.PaginationResponse
	4, // 3: dict.v1.ListSnapshotsRequest.pagination:type_name -> common.v1.PaginationRequest
	7, // 4: dict.v1.ListLemmaSnapshotsResponse.snapshots:type_name -> dict.v1.LemmaSnapshot
	6, // 5: dict.v1.ListLemmaSnapshotsResponse.pagination:type_name -> common.v1.PaginationResponse
	0, // 6: dict.v1.LemmaService.ListLemmas:input_type -> dict.v1.ListLemmasRequest
	2, // 7: dict.v1.LemmaService.ListLemmaSnapshots:input_type -> dict.v1.ListSnapshotsRequest
	1, // 8: dict.v1.LemmaService.ListLemmas:output_type -> dict.v1.ListLemmasResponse
	3, // 9: dict.v1.LemmaService.ListLemmaSnapshots:output_type -> dict.v1.ListLemmaSnapshotsResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_dict_v1_lemma_service_proto_init() }
func file_dict_v1_lemma_service_proto_init() {
	if File_dict_v1_lemma_service_proto != nil {
		return
	}
	file_dict_v1_lemma_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dict_v1_lemma_service_proto_rawDesc), len(file_dict_v1_lemma_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dict_v1_lemma_service_proto_goTypes,
		DependencyIndexes: file_dict_v1_lemma_service_proto_depIdxs,
		MessageInfos:      file_dict_v1_lemma_service_proto_msgTypes,
	}.Build()
	File_dict_v1_lemma_service_proto = out.File
	file_dict_v1_lemma_service_proto_goTypes = nil
	file_dict_v1_lemma_service_proto_depIdxs = nil
}
