// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: dict/v1/linguistics.proto

package dictv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LexemeSense is a reusable lexical sense representation.
type LexemeSense struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Gloss         string                 `protobuf:"bytes,2,opt,name=gloss,proto3" json:"gloss,omitempty"`
	Examples      []string               `protobuf:"bytes,3,rep,name=examples,proto3" json:"examples,omitempty"`
	Provider      string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	TrustWeight   float64                `protobuf:"fixed64,5,opt,name=trust_weight,json=trustWeight,proto3" json:"trust_weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LexemeSense) Reset() {
	*x = LexemeSense{}
	mi := &file_dict_v1_linguistics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LexemeSense) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LexemeSense) ProtoMessage() {}

func (x *LexemeSense) ProtoReflect() protoreflect.Message {
	mi := &file_dict_v1_linguistics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LexemeSense.ProtoReflect.Descriptor instead.
func (*LexemeSense) Descriptor() ([]byte, []int) {
	return file_dict_v1_linguistics_proto_rawDescGZIP(), []int{0}
}

func (x *LexemeSense) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *LexemeSense) GetGloss() string {
	if x != nil {
		return x.Gloss
	}
	return ""
}

func (x *LexemeSense) GetExamples() []string {
	if x != nil {
		return x.Examples
	}
	return nil
}

func (x *LexemeSense) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LexemeSense) GetTrustWeight() float64 {
	if x != nil {
		return x.TrustWeight
	}
	return 0
}

// LemmaForm is a reusable inflected form representation.
type LemmaForm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Surface       string                 `protobuf:"bytes,1,opt,name=surface,proto3" json:"surface,omitempty"`
	FormType      string                 `protobuf:"bytes,2,opt,name=form_type,json=formType,proto3" json:"form_type,omitempty"`
	IsIrregular   bool                   `protobuf:"varint,3,opt,name=is_irregular,json=isIrregular,proto3" json:"is_irregular,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LemmaForm) Reset() {
	*x = LemmaForm{}
	mi := &file_dict_v1_linguistics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LemmaForm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LemmaForm) ProtoMessage() {}

func (x *LemmaForm) ProtoReflect() protoreflect.Message {
	mi := &file_dict_v1_linguistics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LemmaForm.ProtoReflect.Descriptor instead.
func (*LemmaForm) Descriptor() ([]byte, []int) {
	return file_dict_v1_linguistics_proto_rawDescGZIP(), []int{1}
}

func (x *LemmaForm) GetSurface() string {
	if x != nil {
		return x.Surface
	}
	return ""
}

func (x *LemmaForm) GetFormType() string {
	if x != nil {
		return x.FormType
	}
	return ""
}

func (x *LemmaForm) GetIsIrregular() bool {
	if x != nil {
		return x.IsIrregular
	}
	return false
}

// Lexeme is a reusable POS-grouped lexical representation.
type Lexeme struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pos           string                 `protobuf:"bytes,1,opt,name=pos,proto3" json:"pos,omitempty"`
	Senses        []*LexemeSense         `protobuf:"bytes,2,rep,name=senses,proto3" json:"senses,omitempty"`
	Forms         []*LemmaForm           `protobuf:"bytes,3,rep,name=forms,proto3" json:"forms,omitempty"`
	Phonetics     []*Phonetic            `protobuf:"bytes,4,rep,name=phonetics,proto3" json:"phonetics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lexeme) Reset() {
	*x = Lexeme{}
	mi := &file_dict_v1_linguistics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lexeme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lexeme) ProtoMessage() {}

func (x *Lexeme) ProtoReflect() protoreflect.Message {
	mi := &file_dict_v1_linguistics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lexeme.ProtoReflect.Descriptor instead.
func (*Lexeme) Descriptor() ([]byte, []int) {
	return file_dict_v1_linguistics_proto_rawDescGZIP(), []int{2}
}

func (x *Lexeme) GetPos() string {
	if x != nil {
		return x.Pos
	}
	return ""
}

func (x *Lexeme) GetSenses() []*LexemeSense {
	if x != nil {
		return x.Senses
	}
	return nil
}

func (x *Lexeme) GetForms() []*LemmaForm {
	if x != nil {
		return x.Forms
	}
	return nil
}

func (x *Lexeme) GetPhonetics() []*Phonetic {
	if x != nil {
		return x.Phonetics
	}
	return nil
}

// SemanticRelation is a reusable semantic relation representation.
type SemanticRelation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RelationType   string                 `protobuf:"bytes,1,opt,name=relation_type,json=relationType,proto3" json:"relation_type,omitempty"`
	TargetTerm     string                 `protobuf:"bytes,2,opt,name=target_term,json=targetTerm,proto3" json:"target_term,omitempty"`
	TargetRef      string                 `protobuf:"bytes,3,opt,name=target_ref,json=targetRef,proto3" json:"target_ref,omitempty"`
	Provider       string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	Strength       float64                `protobuf:"fixed64,5,opt,name=strength,proto3" json:"strength,omitempty"`
	SenseMapped    bool                   `protobuf:"varint,6,opt,name=sense_mapped,json=senseMapped,proto3" json:"sense_mapped,omitempty"`
	TargetResolved bool                   `protobuf:"varint,7,opt,name=target_resolved,json=targetResolved,proto3" json:"target_resolved,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SemanticRelation) Reset() {
	*x = SemanticRelation{}
	mi := &file_dict_v1_linguistics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticRelation) ProtoMessage() {}

func (x *SemanticRelation) ProtoReflect() protoreflect.Message {
	mi := &file_dict_v1_linguistics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticRelation.ProtoReflect.Descriptor instead.
func (*SemanticRelation) Descriptor() ([]byte, []int) {
	return file_dict_v1_linguistics_proto_rawDescGZIP(), []int{3}
}

func (x *SemanticRelation) GetRelationType() string {
	if x != nil {
		return x.RelationType
	}
	return ""
}

func (x *SemanticRelation) GetTargetTerm() string {
	if x != nil {
		return x.TargetTerm
	}
	return ""
}

func (x *SemanticRelation) GetTargetRef() string {
	if x != nil {
		return x.TargetRef
	}
	return ""
}

func (x *SemanticRelation) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *SemanticRelation) GetStrength() float64 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *SemanticRelation) GetSenseMapped() bool {
	if x != nil {
		return x.SenseMapped
	}
	return false
}

func (x *SemanticRelation) GetTargetResolved() bool {
	if x != nil {
		return x.TargetResolved
	}
	return false
}

var File_dict_v1_linguistics_proto protoreflect.FileDescriptor

const file_dict_v1_linguistics_proto_rawDesc = "" +
	"\n" +
	"\x19dict/v1/linguistics.proto\x12\adict.v1\x1a\x12dict/v1/word.proto\"\x9a\x01\n" +
	"\vLexemeSense\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x14\n" +
	"\x05gloss\x18\x02 \x01(\tR\x05gloss\x12\x1a\n" +
	"\bexamples\x18\x03 \x03(\tR\bexamples\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12!\n" +
	"\ftrust_weight\x18\x05 \x01(\x01R\vtrustWeight\"e\n" +
	"\tLemmaForm\x12\x18\n" +
	"\asurface\x18\x01 \x01(\tR\asurface\x12\x1b\n" +
	"\tform_type\x18\x02 \x01(\tR\bformType\x12!\n" +
	"\fis_irregular\x18\x03 \x01(\bR\visIrregular\"\xa3\x01\n" +
	"\x06Lexeme\x12\x10\n" +
	"\x03pos\x18\x01 \x01(\tR\x03pos\x12,\n" +
	"\x06senses\x18\x02 \x03(\v2\x14.dict.v1.LexemeSenseR\x06senses\x12(\n" +
	"\x05forms\x18\x03 \x03(\v2\x12.dict.v1.LemmaFormR\x05forms\x12/\n" +
	"\tphonetics\x18\x04 \x03(\v2\x11.dict.v1.PhoneticR\tphonetics\"\xfb\x01\n" +
	"\x10SemanticRelation\x12#\n" +
	"\rrelation_type\x18\x01 \x01(\tR\frelationType\x12\x1f\n" +
	"\vtarget_term\x18\x02 \x01(\tR\n" +
	"targetTerm\x12\x1d\n" +
	"\n" +
	"target_ref\x18\x03 \x01(\tR\ttargetRef\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12\x1a\n" +
	"\bstrength\x18\x05 \x01(\x01R\bstrength\x12!\n" +
	"\fsense_mapped\x18\x06 \x01(\bR\vsenseMapped\x12'\n" +
	"\x0ftarget_resolved\x18\a \x01(\bR\x0etargetResolvedB\x8e\x01\n" +
	"\vcom.dict.v1B\x10LinguisticsProtoP\x01Z0github.com/eslsoft/vocnet/pkg/api/dict/v1;dictv1\xa2\x02\x03DXX\xaa\x02\aDict.V1\xca\x02\aDict\\V1\xe2\x02\x13Dict\\V1\\GPBMetadata\xea\x02\bDict::V1b\x06proto3"

var (
	file_dict_v1_linguistics_proto_rawDescOnce sync.Once
	file_dict_v1_linguistics_proto_rawDescData []byte
)

func file_dict_v1_linguistics_proto_rawDescGZIP() []byte {
	file_dict_v1_linguistics_proto_rawDescOnce.Do(func() {
		file_dict_v1_linguistics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dict_v1_linguistics_proto_rawDesc), len(file_dict_v1_linguistics_proto_rawDesc)))
	})
	return file_dict_v1_linguistics_proto_rawDescData
}

var file_dict_v1_linguistics_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dict_v1_linguistics_proto_goTypes = []any{
	(*LexemeSense)(nil),      // 0: dict.v1.LexemeSense
	(*LemmaForm)(nil),        // 1: dict.v1.LemmaForm
	(*Lexeme)(nil),           // 2: dict.v1.Lexeme
	(*SemanticRelation)(nil), // 3: dict.v1.SemanticRelation
	(*Phonetic)(nil),         // 4: dict.v1.Phonetic
}
var file_dict_v1_linguistics_proto_depIdxs = []int32{
	0, // 0: dict.v1.Lexeme.senses:type_name -> dict.v1.LexemeSense
	1, // 1: dict.v1.Lexeme.forms:type_name -> dict.v1.LemmaForm
	4, // 2: dict.v1.Lexeme.phonetics:type_name -> dict.v1.Phonetic
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_dict_v1_linguistics_proto_init() }
func file_dict_v1_linguistics_proto_init() {
	if File_dict_v1_linguistics_proto != nil {
		return
	}
	file_dict_v1_word_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dict_v1_linguistics_proto_rawDesc), len(file_dict_v1_linguistics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dict_v1_linguistics_proto_goTypes,
		DependencyIndexes: file_dict_v1_linguistics_proto_depIdxs,
		MessageInfos:      file_dict_v1_linguistics_proto_msgTypes,
	}.Build()
	File_dict_v1_linguistics_proto = out.File
	file_dict_v1_linguistics_proto_goTypes = nil
	file_dict_v1_linguistics_proto_depIdxs = nil
}
